### ISSUE TITLE
consolidate local metadata-related configurations

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#107]

**Comment by hackmastera** [comment]
There are a couple of locations I won't be able to change:
* config/authorities/ directory (currently contains only languages.yml)
* config/locales/en.yml (changing the label of a field, also the tooltips are in here)

**Comment by hackmastera** [comment]
Everything else I've put in 
* config/initializers/chufia.rb

**Comment by catlu** [comment]
Hahaha, awesome.

**Comment by hackmastera** [comment]
TODO:
* external ID dropdown options
* date start / end qualifier values?

**Comment by hackmastera** [comment]
Okay there is enough logic bound up with the date start, end qualifiers that I'm not comfortable moving those. They can go through a developer if they need to be changed. Otherwise, I've got everything settled and will push momentarily.

**Comment by hackmastera** [comment]
@catlu unfortunately I had to change the filenames, so the chufia.rb initializer is gone. Here is the full list of files:

* config/authorities/ directory (currently contains only languages.yml)
* config/locales/en.yml (changing the label of a field, also the tooltips are in here)
* config/initializers/sufia_amendments.rb

**Comment by catlu** [comment]
Awesome, thanks!
