### ISSUE TITLE
change schema.org URIs?

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#108]
We have purl urls in there, but sufia now ships with schema.org urls. Not too late to change if we want to... opinions?

**Comment by catlu** [comment]
Does it actually make a difference for us if both are permanent? I can keep an eye on any namespace recs that might come out of metadata discussions, but I don't really have an opinion otherwise.

**Comment by hackmastera** [comment]
No difference; I just think the purl ones are ugly / less semantically useful.

**Comment by hackmastera** [comment]
No difference; I just think the purl ones are ugly / less semantically
useful.

**Comment by catlu** [comment]
Cool, if it's an easy change, I'm for it.

**Comment by hackmastera** [comment]
Okay I was wrong!! It's not that we have different URIs for schema objects, it's that they use schema.org for resource_type and we use DC. So no changes necessary.
