### ISSUE TITLE
Replace VIAF with FAST for Maker field autocomplete

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#111]

**Comment by catlu** [comment]
Personal and corporate subheadings if possible.

**Comment by hackmastera** [comment]
Okay personal + corporate for all depends on #81 -- for now I can either do personal on some and corporate on others, or I can do all of FAST on all of them. Let me know which!

**Comment by catlu** [comment]
Oh yeah, in that case, let's do full FAST on all of them.
