### ISSUE TITLE
error on metadata save

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#116]
Not yet reproduced...

I, [2015-11-16T10:00:19.096141 #31809]  INFO -- : Completed 200 OK in 23ms (Views: 1.0ms | ActiveRecord: 2.1ms)
I, [2015-11-16T10:00:46.476938 #31809]  INFO -- : Started POST "/files/pk02cd10r" for 75.151.128.169 at 2015-11-16 10:00:46 -0500
F, [2015-11-16T10:00:46.480912 #31809] FATAL -- : 
ActionController::BadRequest (Invalid request parameters: expected Array (got Rack::Utils::KeySpaceConstrainedParams) for param `generic_file'):
  rack (1.6.4) lib/rack/utils.rb:154:in `normalize_params'
  rack (1.6.4) lib/rack/multipart/parser.rb:77:in `block (2 levels) in parse'
  rack (1.6.4) lib/rack/multipart/parser.rb:250:in `get_data'
  rack (1.6.4) lib/rack/multipart/parser.rb:74:in `block in parse'
  rack (1.6.4) lib/rack/multipart/parser.rb:56:in `loop'
  rack (1.6.4) lib/rack/multipart/parser.rb:56:in `parse'
  rack (1.6.4) lib/rack/multipart.rb:25:in `parse_multipart'
  rack (1.6.4) lib/rack/request.rb:375:in `parse_multipart'
  rack (1.6.4) lib/rack/request.rb:207:in `POST'
  actionpack (4.2.2) lib/action_dispatch/http/request.rb:308:in `POST'
  actionpack (4.2.2) lib/action_dispatch/http/parameters.rb:14:in `parameters'
  actionpack (4.2.2) lib/action_dispatch/http/filter_parameters.rb:37:in `filtered_parameters'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:22:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  /opt/sufia-project/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-137c6524069d/lib/active_fedora/ldp_cache.rb:26:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  passenger (5.0.10) lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
  passenger (5.0.10) lib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
  passenger (5.0.10) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.10) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.10) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

**Comment by hackmastera** [comment]
This seems relevant; mess around mixing existing and new nested objects to try to replicate.

http://stackoverflow.com/questions/11445831/how-to-submit-multiple-new-items-via-rails-3-2-mass-assignment

**Comment by hackmastera** [comment]
closing until/unless we see this again.

**Comment by hackmastera** [comment]
We have seen it again!! Here's a gist.
https://gist.github.com/hackmastera/cece8cf8486f8a280c4f

**Comment by hackmastera** [comment]
Two things I can think of. One is that in both cases a number of form fields were filled out. According to @catlu she filled out title, bib, division, resource type, genre, rights, rightsholder, file creator. I've tried batch uploads with all these fields filled out and am not able to recreate the error.

my other thought is that that only happens on a newly-built server? Or a newly-wiped fedora instance? I have a vague memory of @MDiMeo testing right after an event of some kind on Nov 11. And Cat's upload was definitely the first one on that prod server. Maybe I should try a bulk upload with lots of fields fill out after wiping fedora & solr.

Will plan to do that on the staging server tomorrow. tagging @sanfordd also for good measure!

**Comment by MDiMeo** [comment]
@hackmastera I don't remember if it was a new machine or not. Seems possible, but I can't remember...

**Comment by hackmastera** [comment]
@catlu @MDiMeo @sanfordd Was unable to replicate. I tried:

1. Wipe all fedora, solr, and relevant postgres data
1. turn services back on
1. upload set of 21 tiffs (found on the digitization drive)
1. fill out all the form fields cat mentioned to me, plus a subject.

Everything submitted fine and got the expected metadata.

I'm going to try writing the hydra-tech list to see if anyone else has had this error or has ideas on how to replicate it.

**Comment by hackmastera** [comment]
I have achieved replication!!!

This error occurs when you select a maker field type but then select blank again for that maker field type before submitting the form. Definitely a javascript bug.

I also observe the secondary error of the object ID now coming through on 2nd submission. Not sure if that is worth exploring more, since using a browser back button into a form is not usually recommended.
