### ISSUE TITLE
Add 'Place of Creation' to Place field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#119]
Use https://s3.amazonaws.com/VRA/ontology.html#placeOfCreation okay?

We can revisit the predicates if we switch over to using events.

**Comment by hackmastera** [comment]
@catlu That predicate has a range vra/Place. We need something with range literal.

**Comment by hackmastera** [comment]
@catlu All the other places are mark relators. What about the marc relator for 'production place' (prp)? https://www.loc.gov/marc/relators/relaterm.html

**Comment by hackmastera** [comment]
@catlu please reopen if you don't like http://id.loc.gov/vocabulary/relators/prp.html and want me to use a local predicate.

**Comment by catlu** [comment]
I like that one, though initially I thought users might get confused over production vs. manufacture. Using that predicate, but keeping Place of creation as the label works great.
