### ISSUE TITLE
Geonames autocomplete for Place field display issues

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#131]
Duplication and extra spaces and commas when a broader place/location is chosen. For example:

San Francisco, California, United States
vs

California, California, United States
United States, , United States
South America, , Brazil - ??

**Comment by hackmastera** [comment]
@catlu Thanks for finding this. Can you add to your comment what you typed in to generate each of those results?

**Comment by catlu** [comment]
Yep:

"California"
"United States"
"South America"

**Comment by catlu** [comment]
Another issue I've found--I'm unclear if it's entirely display related, so just noting it here for discussion:

Typed in "bed stuy" > returns Bed-Stuy, New York, United States
Typed in "bed stuy " > returns Bedford–Stuyvesant, New York, United States

At first I thought that was an authority issue, but when I go to Geonames.org, Bedford–Stuyvesant is the only result. I'm not sure if Bed-Stuy is showing up as an alternate but has the same ID as the authority entry, or if it's another entry. Either way, two different labels would mean two different entries in chufia at this point. I'm also unclear why typing "bed stuy" doesn't return both results in the first place.

**Comment by hackmastera** [comment]
We've decided to go back to fast, but include all fields instead of just geographic. This covers the use case without having to mess with geonames problems.
