### ISSUE TITLE
record view renders html in title

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#142]
see http://staging.hydra.chemheritage.org/files/b2773v68h

list view does not do this. best practice is to escape these types of characters.

**Comment by hackmastera** [comment]
Looks like this may have just been resolved upstream. see https://github.com/projecthydra/sufia/pull/1548/files

**Comment by jrochkind** [comment]
Related to #242, not neccessary as a separate issue, no longer does this. @hackmastera please re-open if I'm wrong! Trying to clear out some issues!
