### ISSUE TITLE
create rescued Ldp::Gone

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#152]
@catlu reported error on upload at 12:24. sent screenshot:

![uploaderror](https://cloud.githubusercontent.com/assets/845363/12893697/95cbfbd2-ce60-11e5-929c-f318a19797fb.jpg)

Found error in log; it's on the staging server in ~/upload_error_2016-02-08-noonish.txt

Reminds me of this thread: 
https://groups.google.com/forum/#!searchin/hydra-tech/active_fedora-noid$201.0.3/hydra-tech/AiDWzHpi6dc/znXeW6ACAwAJ

**Comment by hackmastera** [comment]
This happened because the statefile was accidentally deleted.

New statefile was created on Feb 5th around noon.  If previous statefile were found, it could theoretically be replayed onto new statefile.

- [ ] Implement code fix referenced in above hydra-tech thread
- [ ] move statefile to /var/sufia/minter-state and record new location in rails config. Note: this will require downtime deployment.
- [ ] see if we can find the old statefile. If we can, see if we can find out when it was created.
- [ ] see if we can find the new statefile's seed. Presumably if we have this and lose the statefile we can start a new one at a predetermined spot in the sequence.

First objects were added to prod on Jan 20th.

relevant IRC conversation: http://irc.projecthydra.org/2016-02-09.html

**Comment by hackmastera** [comment]
Dan recovered the old statefile. it was created Jan 20 at 1:56 p.m. and runs until the morning of the 28th 2 am.

**Comment by sanfordd** [comment]
Statefile's location in /tmp means that with default Ubuntu behavior any reboot of the system erases the statefile. Likely it was lost due to a reboot during some configuration. 

This can be fixed by setting the $TMPTIME  variable  in /etc/default/rcS to -1 (never erase /tmp files on a boot) if we run into issues with moving it from /tmp.

**Comment by hackmastera** [comment]
So now we have two different state files covering different sets of objects in the repo. Further investigation reveals that it is impossible to combine them.

**Comment by hackmastera** [comment]
Here's how to get the seed out of a statefile (using the rails console)

>> f = File.new('/var/sufia/minter-state', 'r')
>> state =  Marshal.load(f.read)
>> r = Marshal.load(state[:rand])
>> r.seed

can't fix formatting right now; you get the idea.

**Comment by hackmastera** [comment]
If the statefile is lost, the app tries to generate it but currently cannot due to a permission error. the app crashes because /var/sufia is owned by root. We could and down the line may want to chown /var/sufia to the deploy user and group, however we should wait until the bug is fixed upstream. the upstream proposal includes work to error out if the file is not found in a production environment. For now I will leave things as-is, so that if we *were* to lose the statefile again (which we shouldn't since it's now in a reasonable location) everything would stop until we recovered it, which is desired behavior.
