### ISSUE TITLE
add creator/maker field to collection

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#155]
will have different choices than the one in generic_file.

**Comment by catlu** [comment]
Choices:


Creator - dc:creator (if that's the one we're using with generic_file)
Collector - http://id.loc.gov/vocabulary/relators/col
Compiler - http://id.loc.gov/vocabulary/relators/com
Donor - http://id.loc.gov/vocabulary/relators/dnr

maybe... Photographer (I have to see if there are enough use cases)

**Comment by MDiMeo** [comment]
@catlu Still something we need/want? Might be worth revisiting as we think about redesigning the Collection page.

**Comment by MDiMeo** [comment]
no use case for now
