### ISSUE TITLE
Update text for Help tab

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#162]
Main body text at https://hydra.chemheritage.org/help should read: "Frequently Asked Questions are forthcoming. Please submit a Help Desk ticket via to the Contact Form". Reference to "Contact Form" should link to page https://hydra.chemheritage.org/contact

**Comment by hackmastera** [comment]
I don't think we should say "help desk ticket" in case people confuse it with the central helpdesk ticketing system. I'll say something like "please submit questions or problems."

**Comment by sanfordd** [comment]
That's a good idea.

**Comment by MDiMeo** [comment]
Actually, I originally thought the opposite and intentionally used the words "Help Desk ticket" because that's what people around here say and I figured they'd use the same language for Hydra. That said, I absolutely see your point and am happy to see what language you've suggest instead.
