### ISSUE TITLE
Only an admin should be able to create accounts

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#163]
i.e. only an admin can view / submit the signup page

**Comment by hackmastera** [comment]
If only an admin can create accounts, there is no way to create an initial account. 
need: a rake task to assign an existing account admin status (for setting first admin on existing installs of the application)
need: a rake task to create an initial admin account (for clean installs of the application).

**Comment by hackmastera** [comment]
related to https://github.com/chemheritage/chf-sufia/issues/2

**Comment by hackmastera** [comment]
spotlight rake tasks: https://github.com/sul-dlss/spotlight/blob/master/lib/tasks/spotlight_tasks.rake

**Comment by hackmastera** [comment]
rake tasks created. now to find the right spot to insert these permissions.

**Comment by hackmastera** [comment]
Hitch in our plan: If you try to navigate to the 'sign up' page while logged in you are sent back to the dashboard and told you are already signed in.

**Comment by hackmastera** [comment]
- [ ] disable devise :registerable.
- [ ] build a form for admins to make accounts
- [ ] figure out where to put a link to this form
- [ ] add to login page 'request login' - goes to contact form
- [ ] add 'request login' to contact form dropdown

**Comment by hackmastera** [comment]
https://github.com/scambra/devise_invitable looks useful as an alternative

**Comment by hackmastera** [comment]
i had this attached to my trello card; leave it here in case it's useful: http://stackoverflow.com/questions/6969494/rails-nameerror-uninitialized-constant-registration

**Comment by jrochkind** [comment]
Maybe turn off the UI for account creation altogether, and let admins create account with a rake task? Not sure. 

I don't like the admin using the signup UI to create an account for someone else, meaning they are tempted to know and share their password over email. Plus I'm not sure the existing signup UI will let you be logged in as an admin but then create an account for someone else! 

Or we could let anyone create accounts, but require them to be 'approved' by an admin somehow.

**Comment by hackmastera** [comment]
Yeah, I had a whole plan at once point that I'd looked into, but we almost never have account creation.

A rake task will require one of us or @sanfordd to run it, but I think that's perfectly acceptable.

There's a password validation on user save that we'll need to turn off to use the flow you proposed earlier: create the account and then trigger password reset email.

I think, though, that we will also want a rake task that accepts a password for dev use; I don't have email stuff set up on my dev server and I don't intend to do that.

**Comment by hackmastera** [comment]
Okay new checklist:
- [ ] write a rake task to create accounts with passwords
- [ ] write a rake task to create accounts without passwords (or maybe with a randomly-generated password?), which sends the password reset email
- [ ] Remove 'create account' link
- [ ] disable 'create account' page
