### ISSUE TITLE
Transfer of Ownership delays load of main page

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#174]
When a user has many transfered files in the Transfer of Ownership section of the main page it causes a notable slow down to logging in as Sufia populates the list. This can be 20-40 seconds when the page is connected too such as logging in or moving back there.

Would it be possible to either disable that view or make it some sort of click to view to avoid the load times it imposes?

**Comment by hackmastera** [comment]
here's how i created a bunch of test data in my dev instance:

 ```
   200.times do |i|
      receiver = User.find_by_email "aheadley@chemheritage.org"
      sender = User.find_by_email "person@example.com"
      file = GenericFile.new
      file.apply_depositor_metadata sender
      file.save
      pdr = ProxyDepositRequest.new(generic_file_id: file.id, sending_user: sender,
        receiving_user: receiver, sender_comment: "transfer #{i}", status: 'accepted')
      pdr.save
      puts "proxy deposit request #{i} created"
    end
```

**Comment by hackmastera** [comment]
The slowdown is not caused by the display; it's caused by the retrieval. So I can't fix this by disabling the view; will look into how the data is pulled.

**Comment by hackmastera** [comment]
also note the slowdown only affects the user with all the transfers; other users aren't affected.

**Comment by hackmastera** [comment]
okay i've changed it to only pull pending transactions. also added a link to view all transactions. just finishing up a test and then it will be ready.
