### ISSUE TITLE
quick and dirty metadata stats

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#184]
just judge completion based on title and description fields. title shouldn't contain '.tif' and should have a description. report per division with a total at the end, e.g.:
```
metadata completion report
Archives: X / Y (ZZ%) records have titles
Archives: X / Y (ZZ%) records have titles and descriptions
```

**Comment by hackmastera** [comment]
@catlu here's what the report looks like when i run it on staging. comments?
```
Archives: 0 / 6 (0%) records have titles
Archives: 0 / 6 (0%) records have titles and descriptions
Center for Oral History: 0 / 0 (100%) records have titles
Center for Oral History: 0 / 0 (100%) records have titles and descriptions
Museum: 0 / 0 (100%) records have titles
Museum: 0 / 0 (100%) records have titles and descriptions
Othmer Library of Chemical History: 11 / 11 (100%) records have titles
Othmer Library of Chemical History: 6 / 11 (54%) records have titles and descriptions
Uncategorized: 18 / 115 (15%) records have titles
Uncategorized: 0 / 115 (0%) records have titles and descriptions
All divisions: 29 / 132 (21%) records have titles
All divisions: 6 / 132 (4%) records have titles and descriptions
```

**Comment by catlu** [comment]
@hackmastera, looks great to me!

**Comment by hackmastera** [comment]
The report picks up more objects than the interface reports having. On production, it processed 1047 objects whereas the site only indicates 812. deleted objects? need to figure this out.

**Comment by catlu** [comment]
It's possible that they're private records, like from Beckman. I remember that being a count discrepancy in another instance.

**Comment by hackmastera** [comment]
I think you're right. I did some testing and deleted records are in fact gone enough to not be picked up by this report. the discrepancy on my dev instance exactly lined up with the number of private records. would it help to add some logic into the report regarding visibility? if so let me know how that should affect the numbers.
