### ISSUE TITLE
Multiple description separators

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#188]
Right now when multiple description entries are added, the separator is a pipe character.  With longer entries it leads a text blob which is hard to read.

Ex. record: https://hydra.chemheritage.org/files/jm214p20f

![capture](https://cloud.githubusercontent.com/assets/11876037/17906317/ca7a4576-6944-11e6-8633-b91cef25be05.JPG)

**Comment by hackmastera** [comment]
closing in favor of #246
