### ISSUE TITLE
override max upload size (again)

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#190]
implementation of this changed in sufia 7. best strategy would be to write this into sufia as a configurable value so this doesn't happen again!

https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/uploader.js

https://github.com/projecthydra-labs/hyrax/blob/master/app/assets/javascripts/hyrax/uploader.js

https://github.com/projecthydra-labs/hyrax/issues/119

**Comment by jrochkind** [comment]
There is an outstanding Hyrax Issue. https://github.com/projecthydra-labs/hyrax/issues/119

**Comment by jrochkind** [comment]
There are no further expected releases of sufia, so PR'ing to sufia seems not a useful way to spend time. 

And I don't know if it's productive to pr to hyrax, since we dont' know when we'll be on it, and I'm not really familiar with it yet. 

So just fix locally for now after all?

**Comment by hackmastera** [comment]
@jrochkind that sounds right, although it occurs to me that I haven't heard anyone asking about this in a while. It may be the 500mb is actually sufficient. Shall we wait and see if @catlu or @archivistsarah have been bumping up against this at all?

**Comment by jrochkind** [comment]
@catlu, @archivistsarah , can you confirm if we need maximum file size upload increased past 500mb? If so, I'll make it so! If not, I'd like to close this issue and move on to others. Thanks!

**Comment by archivistsarah** [comment]
We have bumped into the 500MB limit a few times, but we just split the ingest into 2 batches & we're good as long as everything ultimately sorts correctly within works (which it has). More of a problem for @catlu & library materials, I think. 

tl/dr: If it's a huge hassle/expense to up the limit, we're ok continuing to work within it. But we also wouldn't say no to more.

**Comment by jrochkind** [comment]
It's a semi-problem because sufia makes this hard to change, especially with sufia being end-of-lifed and people moving on to hyrax. 

So if it's not needed, I might skip it, and move on to some of the other 100+ open tickets! I'd like to try to get that number much smaller. 

But can do it if it's needed! @catlu, opinion?

**Comment by hackmastera** [comment]
@archivistsarah it sounds like you've bumped up against the 1GB limit (for an entire batch of uploads) as opposed to the 500MB limit (for a single file). The single file limit I believe would be impossible to work around.

**Comment by jrochkind** [comment]
aha, good clarificaiton @hackmastera .  In that case, I think I'm going to close this issue for now. If it is a problem in the future (or the 1G entire-batch limit is), we can open another issue no problem!

**Comment by archivistsarah** [comment]
aha! Ok, then yes we're definitely fine with that. I don't think we're going to have any 300dpi images that would take up 500MB.

**Comment by catlu** [comment]
nope, I've not run into this yet at all @hackmastera @jrochkind.

**Comment by catlu** [comment]
spoke too soon! i have a file that comes in a 1.03 gb, it's a pull out book so the entire length is 14 pages.

**Comment by jrochkind** [comment]
ok we'll figure out how to do it!

**Comment by jrochkind** [comment]
@catlu If needed in the interim, I can add individual files programmatically for you, if you need them right away.

**Comment by catlu** [comment]
No hurry, because I think this might still be a rare occurrence (at least until a/v stuff). Adding one-offs programmatically for now works for me. @jrochkind do you have access to the M: Digitization drive? If not, I'll move the file somewhere you can access it.

**Comment by jrochkind** [comment]
@catlu Do not have access to `M:`, do have access to `P:`.

**Comment by hackmastera** [comment]
The `M` drive is called 'digitization' on my machine. You could probably put in a helpdesk ticket to get access.

**Comment by MDiMeo** [comment]
I think technically I have to put in a ticket to get him access since I'm the "owner". I can do that now. Thought it might be faster for Cat to just share it via P:Drive. But since she's not here yet and Chuck can be pretty fast, I'll file the ticket. May help in the future.

**Comment by catlu** [comment]
It looks like if I were to copy a tiff over from M: to P:drive, the file undergoes "property loss" - not sure what Windows means by that but I'm not going to risk it. So looks like getting access to M: is the way to go.

**Comment by catlu** [comment]
For when you get access to the M: Digitization drive @jrochkind, the file path is M:\Modern Library\b10256337, the file is b1025633_002full.tif, and the Hydra id is cf95jb915.

**Comment by jrochkind** [comment]
I have access to the digitization drive via a method Chuck showed me using Citrix... but if I try to copy something out of there, I get the very same "property loss" warning you got.  Because I'm doing the exact same thing you are to copy it, essentially!

So.... ?

**Comment by jrochkind** [comment]
maybe we should just figure out a way to override max file upload size after all.

**Comment by catlu** [comment]
Still not working for me unfortunately (cleared cache and all)--not really an impact on my workflow at all, though will want that one file in the work for soft launch.

![capture](https://cloud.githubusercontent.com/assets/11876037/25237047/9475c86c-25b7-11e7-80bb-80b16bd59730.PNG)

**Comment by hackmastera** [comment]
My bad; I didn't realize your file was larger than 1gig; this issue was to restore the previous limit override which was lost in the upgrade to sufia 7.0.

So do we want to make it 1.25?

**Comment by jrochkind** [comment]
I'll just make it 5G and call it a day? Only staff are using this form, unlike the original Sufia imagined use case where you had all sorts of people doing self deposit.
