### ISSUE TITLE
FAST lookup error in Sufia 7

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#205]
In Sufia 7 entering characters into a metadata field with a FAST lookup causes the lookup to stop working as you get closer to a match. An example would be King, Stephen (or Stephen King). Stephen K gets values, but Stephen Ki does not. King, S gets results, King, St does not.

Sufia 6 does not have the same issue and seems to be able to look up the example without any problems.

**Comment by hackmastera** [comment]
The problem is that questioning_authority switched to a different http client which does encoding differently, and the FAST api expects slightly non-standard encoding. So I have to write a custom encoder for the new client to use with the FAST authority in QA.

**Comment by hackmastera** [comment]
resolved upstream in https://github.com/projecthydra-labs/questioning_authority/commit/f4f55fac181a30e07fbee4a37348c82138aa972a
