### ISSUE TITLE
fields not available for batch edit

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#219]
maker, place, genre, medium, extent, description, series, rights, credit (based on sufia 6)

**Comment by hackmastera** [comment]
@catlu please confirm whether this is a blocker for bringing our sufia 7 app into production

**Comment by catlu** [comment]
@hackmastera yep i think so--i will probably be using batch edit more with multi-file works too.

**Comment by hackmastera** [comment]
credit can't really be edited so it probably shouldn't be in there; it's only in the other form as context for  additional credit (which isn't in this form because it can't do nested fields)
