### ISSUE TITLE
specialized field form/s for physical container

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#22]
separate inputs for series, box, folder

**Comment by catlu** [comment]
Splitting series arrangement from this, so only numerical inputs for box, folder, and/or volume. Changed predicate to bf:materialOrganization.

**Comment by hackmastera** [comment]
@catlu I have box, folder, volume, and part. Is this right? And the content will always be numeric?

**Comment by catlu** [comment]
Yup. I think this will mostly be used in an either/or scenario (box/folder or volume/part), but it will be optional regardless, so catalogers can fill in whichever is relevant to them.
