### ISSUE TITLE
Fix rights statements and URIs

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#226]
See https://github.com/chemheritage/chf-sufia/pull/171; @catlu I think it makes sense to do this as part of the upgrade to sufia 7; I can write it into the data migration scripts.

**Comment by catlu** [comment]
Sounds good.

__________________________________

Cathleen Lu
Digital Projects and Metadata Librarian
Othmer Library of Chemical History
P: +1.215.873.8216
F: +1.215.629.5216

Chemical Heritage Foundation
LIBRARY � MUSEUM � CENTER FOR SCHOLARS
315 Chestnut Street  �  Philadelphia, PA 19106 � U.S.A.
chemheritage.org<http://www.chemheritage.org/>


On Nov 3, 2016, at 9:52 AM, hackmastera <notifications@github.com<mailto:notifications@github.com>> wrote:


See #171<https://github.com/chemheritage/chf-sufia/pull/171>; @catlu<https://github.com/catlu> I think it makes sense to do this as part of the upgrade to sufia 7; I can write it into the data migration scripts.

�

**Comment by hackmastera** [comment]
blocked until i finish the data migration scripts and local customizations thereof
