### ISSUE TITLE
date created not showing in show page

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#232]

**Comment by hackmastera** [comment]
we use date_of_work instead.

**Comment by MDiMeo** [comment]
Is there a use case for why we need this showing? @catlu or @archivistsarah?

**Comment by archivistsarah** [comment]
I would find it useful as a staff user, and I could see the researchers wanting to view/sort by newly added items.

**Comment by jrochkind** [comment]
You can sort by this already. "date uploaded". But it's true the thing you are sorting by does not show up on show page, regardless of whether you are logged in. Oddly it doesn't seem to have ever been in default sufia.
