### ISSUE TITLE
Data missing from Inscription field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#238]
One of the inscription entries ("On lock") seems to be missing--

https://hydra.chemheritage.org/files/6h440s49d

http://54.174.234.148/concern/generic_works/6h440s49d

**Comment by hackmastera** [comment]
related to #237

**Comment by hackmastera** [comment]
the data is in the export, but the other two are mushed together, which is maybe a different issue:

```
  "inscription": [
    {
      "id": "4t64gn280",
      "location": "On lock",
      "text": "EAGLE LOCK CO / TERRYVILLE, CONN / U.S.A."
    },
    {
      "id": "g445cd210",
      "location": "Plaque",
      "text": "WESTON / MODEL No / ADJUST FOR ZERO (around screw) / WESTON ELECTRICAL INSTRUMENT CORP. / NEWARK, N.J. U.S.A."
    }
  ],
```

**Comment by hackmastera** [comment]
My theory is that whoever entered the inscription entered the 'plaque' and 'around screw' values into a single inscription field. Please create a ticket if you observe some other behavior.

**Comment by hackmastera** [comment]
The data was imported; it's just not displaying as desired.
