### ISSUE TITLE
titles wrap in the middle of words

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#239]
![title-line-break-sufia7](https://cloud.githubusercontent.com/assets/845363/20577989/0170765e-b193-11e6-8441-d74d7575b783.gif)

**Comment by MDiMeo** [comment]
If this is still happening, is it on public-facing or private pages? If public facing, we should fix this as part of our redesign process.

**Comment by MDiMeo** [comment]
@archivistsarah and @catlu - Is this still happening after the redesign? And is it on public pages or just admin pages?

**Comment by archivistsarah** [comment]
I just did a quick check & don't see it happening anymore

**Comment by catlu** [comment]
I still see it in the admin 'My works' tabs, but it's pretty inconsequential to me.

**Comment by jrochkind** [comment]
only on admin pages right now, not a priority.
