### ISSUE TITLE
HTML markup in Title field no longer rendering

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#242]
http://54.174.234.148/concern/generic_works/5138jd899

**Comment by jrochkind** [comment]
I think we've decided to leave this for now -- you can not put HTML in a title field, for various reasons. 

Is this acceptable, and to close this issue for now?  @catlu @archivistsarah ?

**Comment by archivistsarah** [comment]
I'm fine with that

**Comment by catlu** [comment]
Works for me. @jrochkind, is there a way to look for any records with html markup in the title still, and grab me a list of hydra IDs? I imagine there might be a handful that I could easily update manually.

**Comment by jrochkind** [comment]
@catlu I believe it is only these 5:

3b5918613
pv63g029t
x633f1065
zg64tm017
zk51vg816

Closing this issue, thanks!
