### ISSUE TITLE
create new 'additional_title' field

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#244]
@clu predicate needed

**Comment by catlu** [comment]
@hackmastera: http://purl.org/dc/terms/alternative

**Comment by hackmastera** [comment]
perfect, thank you. @catlu there are currently 2 records with more than 1 title. I'm not sure alternate works for them; should we do subtitle? see 1544bp19x and 2z10wq27b

**Comment by hackmastera** [comment]
Discussion with @catlu; she confirmed alternate title works for these.

**Comment by hackmastera** [comment]
here's the current reference for this: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata

**Comment by hackmastera** [comment]
@catlu when you get a chance could you write up a help text for this field?

**Comment by hackmastera** [comment]
- [ ] config/locales/en.yml
- [ ] spec/models/generic_work_spec.rb
- [ ] spec/features/support/batch_edit_actions.rb
- [ ] spec/views/curation_concerns/base/show.html.erb_spec.rb
- [ ] spec/forms/batch_edit_form_spec.rb
- [ ] spec/lib/chf/import/work_builder_spec.rb
- [ ] spec/concerns/forms/work_form_behavior.rb
- [ ] app/models/solr_document.rb
- [ ] app/models/concerns/generic_metadata.rb
- [ ] app/views/records/edit_fields/_admin_note.html.erb
- [ ] app/views/curation_concerns/base/_attribute_rows.html.erb
- [ ] app/forms/curation_concerns/generic_work_form.rb
- [ ] app/forms/batch_upload_form.rb
- [ ] app/forms/batch_edit_form.rb
- [ ] app/presenters/curation_concerns/generic_work_show_presenter.rb

**Comment by hackmastera** [comment]
also @catlu where do you want this in the order? after identifier to keep required fields together? before identifier to keep titles together? It doesn't seem like this will be the more frequently-used field of all time.

**Comment by catlu** [comment]
i think it should be fine after title. right now the title/identifier required labels are filled out anyway by the time most of the records get to curators.
