### ISSUE TITLE
pull fixes for derivative generation problems

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#248]
one was resolved by changing characterizationjob to call create derivatives as perform_now in cc. the other was resolved by ensuring each file in /tmp has a unique filename - @sanfordd there may be disk space implications here.

Need to pin cc to 1.6 stable to get derivatives generation job timing fix; bundle update sufia and cc

**Comment by sanfordd** [comment]
@hackmastera The /tmp space is just for the import step itself correct? That should be easy enough to have enough temporary space.

**Comment by hackmastera** [comment]
also, i forgot that the script is supposed to be cleaning up after itself here. so shouldn't be an issue; false alarm!!
