### ISSUE TITLE
reorganize add/remove buttons for multi-value fields

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#25]
[-] [text box] [+]

notes: 
- [-] not needed if there's only one text box and it is empty.
- [-] removes box if there is more than one value; clears box if it's the only one
- [+] only exists after the last text box
- clicking [+] puts focus / cursor in newly-created box

**Comment by hackmastera** [comment]
this is where the 'always empty' box is created
https://github.com/projecthydra/hydra-editor/blob/master/app/inputs/multi_value_input.rb#L78
it should only add an empty array if there was nothing in the collection.

**Comment by hackmastera** [comment]
move to backend UI

**Comment by catlu** [comment]
Related user feedback on slight confusion around the add buttons--thought add buttons were for saving data instead of adding another new field.

**Comment by hackmastera** [comment]
^ moved to a different ticket

**Comment by hackmastera** [comment]
improvements made in sufia 7
