### ISSUE TITLE
Lightbox broken for sub-work in item list

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#255]
i tried creating a work in sufia 7 that includes both files (text pages without additional descriptive metadata) and sub-works (images with its own metadata)

a bit of clicking around though overall it worked as i'd expected, but i noticed the lightbox image doesn't work for the sub-work (edited)

it does work when you click through though

reported by @catlu

**Comment by catlu** [comment]
Thinking higher priority for this one as we'd want lightbox working for public users.

**Comment by hackmastera** [comment]
cool - this one is slotted for may; post-minneapolis, where iiif is a topic.
