### ISSUE TITLE
Filename display inconsistency in items list

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#256]
by default in the list of thumbnail titles, sub-work will show the metadata title, and the files will show the filename

screenshot:
![screen shot 2016-12-07 at 10 41 22 am](https://cloud.githubusercontent.com/assets/845363/20974322/cd708ce0-bc69-11e6-8488-fc2f8cee6086.png)

reported by @catlu

**Comment by hackmastera** [comment]
@catlu I'm not sure about this. By default the files will show filename because that's their default title, but i believe if you give them a title that will show.

Also, I'm seeing one sub-work (the ponies one) show what looks like a title. Is it possible the other has its default title (i.e. the filename) as well?

**Comment by hackmastera** [comment]
@catlu clarified that current behavior makes sense; this is an item for future discussion w/r/t workflow.

**Comment by hackmastera** [comment]
oops closed accidentally

**Comment by catlu** [comment]
While this is still the way it is, the inconsistency is no longer an issue (of possible confusion for public users) bc filenames no longer display on the public side, thanks to @jrochkind. Closing this.
