### ISSUE TITLE
Batch share / visibility tab not working

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#260]
Tried to batch add user to works, but the account name doesn't populate.

**Comment by hackmastera** [comment]
I assume this is something you can do in our current version? I may need you to show me or post more detailed replication info / screen shots.

**Comment by hackmastera** [comment]
@catlu does this look like the same issue? https://github.com/projecthydra/sufia/issues/2450

**Comment by catlu** [comment]
It might be related but it looks like that issue is more directly related to visibility (Public/Private) where ours is with adding users.

**Comment by hackmastera** [comment]
looks like we have both problems and the psu fixes both. I'll try porting it over.

**Comment by hackmastera** [comment]
Fix for this is ready; waiting on #278

**Comment by hackmastera** [comment]
not quite as ready as i thought; getting a SystemStackError in testing.

**Comment by hackmastera** [comment]
Here's a gist of the stack at this SystemStackError:

https://gist.github.com/hackmastera/b826a4c79048dc10d0e6f9c0c055b871

Get this gist by inserting into the template:
```
    <% begin %>
      <%= render 'representative_media', presenter: @presenter %>
    <% rescue SystemStackError %>
      <% caller.each { |l| Rails.logger.debug l } %>
    <% end %>
```

**Comment by hackmastera** [comment]
Turned out this error was somehow caused by an unrelated commit to a config file I changed to increase the number of resque workers on dev. Improving the syntax of that config file resolved the issue.
