### ISSUE TITLE
only an admin should be able to delete objects

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#267]

**Comment by jrochkind** [comment]
Does "admin" mean something different than "logged in user" here and in associated issues?

**Comment by catlu** [comment]
I think so--this came up because we wanted to separate collection management/deletion abilities from "cataloger" logged in users (currently, if you can edit, you can delete, and there is no separation in type of logged in user). This probably also gets into what we want for admin user functionality, a conversation we started but haven't returned to just yet.

**Comment by jrochkind** [comment]
Thanks @catlu!  @catlu and @hackmastera: Do we need more discussion before tackling this issue and others in https://github.com/chemheritage/chf-sufia/labels/gantt%3A%20admin%20%2F%20authorization , should I not start on them yet?

**Comment by MDiMeo** [comment]
We haven't really talked about this for a year(!), so I think a brief revisit might be best first. I know @hackmastera got close on this, but then we put it down for other priorities.

**Comment by MDiMeo** [comment]
@jrochkind We previously discussed the authorization strategy on Basecamp, then turned it into GitHub tickets. Here's some background, but this is OLD and should be revisited https://basecamp.com/1929213/projects/8498313/todos/158824002

**Comment by hackmastera** [comment]
The unfinished work is on the admin-role branch; see https://github.com/chemheritage/chf-sufia/wiki/List-of-WIP-branches

**Comment by hackmastera** [comment]
setting the permissions in `ability` work to prevent the behavior, but the buttons still show up and should be removed from the UI:
- 'delete' action on 'my works' listing
- 'delete' action when a batch is selected in 'my works' listing
- 'delete' button on work show page
- 'delete' action in item list on work show page
- 'delete this file' button button on fileset show page

currently you can activate any of these, approve the confirmation, and then you get a confusing / wrong error message:
![screen shot 2017-04-25 at 2 09 34 pm](https://cloud.githubusercontent.com/assets/845363/25400704/62067f80-29c1-11e7-9620-b8c320a2e11d.png)
