### ISSUE TITLE
new dev build

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#275]

**Comment by hackmastera** [comment]
note that phantomjs 2.1.1 is required; not available from apt

**Comment by sanfordd** [comment]
I sadly don't see that they have a repo, so we'd just have to build it. It will make updates a bit more involved in the future.

**Comment by hackmastera** [comment]
we can download binaries

**Comment by hackmastera** [comment]
http://phantomjs.org/download.html

extract with `tar -xjf` place in `/usr/bin/` owned by root

**Comment by sanfordd** [comment]
Sounds good.

**Comment by hackmastera** [comment]
Not really relevant to this repo; more a matter of the ansible repo.
