### ISSUE TITLE
File manager changes not saving

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#277]
If I go into File Manager and change both the sorting and the thumbnail/representative media at the same time, it only saves the sorting/ordering.

**Comment by hackmastera** [comment]
I'm not seeing this on dev.

**Comment by catlu** [comment]
sorting + changing thumbnail/preview and pressing save = only saves sort
sorting first, pressing save, then changing thumbnail/preview = save button doesn't light up again

changing thumbnail/preview first + then sorting = this seems to save correctly
changing thumbnail/preview first, saving, then sorting + saving = works also

I can also show you in person if this is confusing, just let me know.

**Comment by hackmastera** [comment]
resolved by 575fc7a429e4f3fb304d237f90097cfb26f2c96d
