### ISSUE TITLE
SystemStackError / broken works

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#278]

**Comment by hackmastera** [comment]
I'm able to trigger a SystemStackError on dev by uploading 27 files to a single work and then reloading the work view page while the background jobs are still running. Never having entered the file manager.

This resolves when I stop / start the rails server (in the meantime I believe the queue completed so that may be relevant).

**Comment by hackmastera** [comment]
The broken work on staging does not resolve on apache restart. restarting resque-pool also does not resolve it.

**Comment by hackmastera** [comment]
I triggered the error on dev again by changing thumbnail/representative in the file manager and going back to view the work.

**Comment by hackmastera** [comment]
just a note there's nothing magic about 27; I also get the error by changing the thumbnail / rep image for a 19-file work.

**Comment by hackmastera** [comment]
If I don't force the shutdown I get this error:

```
^C[2017-01-05 11:59:10] INFO  going to shutdown ...
[2017-01-05 12:00:44] ERROR Errno::ETIMEDOUT: Connection timed out
        /usr/local/lib/ruby/2.2.0/webrick/httpresponse.rb:460:in `write'
        /usr/local/lib/ruby/2.2.0/webrick/httpresponse.rb:460:in `<<'
        /usr/local/lib/ruby/2.2.0/webrick/httpresponse.rb:460:in `_write_data'
        /usr/local/lib/ruby/2.2.0/webrick/httpresponse.rb:432:in `send_body_string'
        /usr/local/lib/ruby/2.2.0/webrick/httpresponse.rb:306:in `send_body'
        /usr/local/lib/ruby/2.2.0/webrick/httpresponse.rb:208:in `send_response'
        /usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:110:in `run'
        /usr/local/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
[2017-01-05 12:00:44] INFO  WEBrick::HTTPServer#start done.
Exiting

```

**Comment by hackmastera** [comment]
There is no problem on a 3-file work. At some point there are more works than the system can handle. maybe look at ulimit -s? http://dalibornasevic.com/posts/5-ruby-stack-level-too-deep-systemstackerror

**Comment by sanfordd** [comment]
Right now we're sitting at around 8 MB of stack space. I don't see a problem with doubling to quadrupling it if we need more, but it does impose some real concerns about the code's portability across systems.

**Comment by hackmastera** [comment]
I don't get this error when i only reorder in file manager. i only get it when i change thumbnail and rep. media.

**Comment by hackmastera** [comment]
Also, I can no longer replicate on dev.

**Comment by hackmastera** [comment]
This issue is still difficult to replicate, but i can occasionally make it happen. i got a full stack trace on dev.

the issue is in line 56 of curation_concerns: app/presenters/curation_concerns/work_show_presenter.rb

Looks like somewhere the work is being added as a member of itself? causing this recursion later on. Now need to search for where that may be happening.

https://gist.github.com/hackmastera/2d2d03e45f09288502e6e097cf484214

**Comment by hackmastera** [comment]
bookmarking this link: https://rossta.net/blog/debugging-systemstackerror.html

**Comment by hackmastera** [comment]
Work not a member of itself. FileSet is getting a representative_id only id to use here is its own; doesn't make sense for FileSet to have a representative_id.

**Comment by hackmastera** [comment]
either:
- filesets should not be allowed to have representative_id (or thumbnail_id)
- presenter should stop recursing once it hits a fileset

**Comment by hackmastera** [comment]
It looks like this would all work fine except that something about the UI makes it possible for a work's fedora record and solr record to be inconsistent. in the example I'm looking at on dev fedora reports 27 members and solr reports 10. 

here's how to get the file_sets from solr:
```
file_set_ids = ActiveFedora::SolrService.query("{!field f=has_model_ssim}FileSet",
   fl: ActiveFedora.id_field,  
 fq: "{!join from=ordered_targets_ssim to=id}id:\"#{w.id}/list_source\"").flat_map { |x| x.fetch(ActiveFedora.id_field, []) } 
```

**Comment by hackmastera** [comment]
according to jcoyne solr returns 10 results unless you tell it otherwise. We should be able to fix this simply by adding `rows: 10000` into the solr query. works in a rough test on dev. i shall patch curation concerns.
