### ISSUE TITLE
'external ID' form field should have a dropdown-box with ID sources

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#28]
Data is stored with the source prepended to id.

**Comment by hackmastera** [comment]
@catlu can you get me a list of ID sources?

**Comment by catlu** [comment]
Object IDs (varied) assigned to PastPerfect objects and photos: 2008.043.002; IG99:04A-G; PROP 134
Bib or Item numbers from Sierra/OPAC: b10337957; i11201022
Accession numbers for Archives collections (spreadsheet): 2015.002
ArchivesSpace Reference numbers: aspace_0396a206bcecfe8a2a70b7f59e7af082

**Comment by catlu** [comment]
Oral history interview numbers: 0265 (assigned 4-digit number but completed transcripts also have Bib/Item numbers.

**Comment by hackmastera** [comment]
@catlu Thanks! What do you want the drop-down label to be for each?

**Comment by catlu** [comment]
How about: Object ID, Bibliographic No., Item No., Accession No., ASpace Reference No., and Oral History Interview No.? Open to other suggestions as well, like if they need to be shorter.

**Comment by hackmastera** [comment]
That sound be fine; I'll keep you posted. I always double take on "ASpace" in this context, haha.

I'm going to shorten them for the actual structured / encoded string prefix. Do you have opinions on those? e.g. an Object ID could be stored as 'object-2008.043.002' or 'pp-2008.043.002' or any number of other ways. Here's a first pass:

Object ID => 'object'
Bibliographic No. => 'bib'
Item No. => 'item'
Accession No. => 'accn'
ASpace Reference No. => 'aspace'
Oral History Interview No. => 'interview'

**Comment by hackmastera** [comment]
alternatively, we could combine Bib and Item numbers into just one label ('Sierra' or 'OPAC') and they would encode like 'opac-b10337957', 'opac-i11201022'

I'm a little concerned that people will be confused about whether to include the leading 'b' or 'i' the way it's currently specified.

**Comment by catlu** [comment]
(Me too about ASpace, haha.) Those shortenings work for me, and I share your concerns about the bib/item labels. I'm thinking it's safer to keep them separate, just to drive home the idea that item numbers are different. That will be a tricky one already, because so far it seems like the only way to retrieve an item number is to log into Sierra.
