### ISSUE TITLE
Sharing permissions with an additional user erases first user

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#283]
![capture](https://cloud.githubusercontent.com/assets/11876037/21694653/52afc3b6-d354-11e6-8109-4315ff515e44.PNG)

After I hit save, Jim's user ID disappears.

**Comment by catlu** [comment]
I think adding multiple in one try doesn't work either. It erases everyone but the depositor and the last person added.

**Comment by hackmastera** [comment]
oof

**Comment by catlu** [comment]
I have no idea what's going on, but I'm revisiting this and the issue is gone! Gah. I'll reopen if I see it again.

**Comment by catlu** [comment]
Never mind--definitely still happening but seems arbitrary as sometimes one record will save okay and the next won't. I can tell it's happening when the "Apply changes to contents?" message doesn't show up. Going back in and removing a permissions, saving, and then resharing seems to work.

**Comment by hackmastera** [comment]
Here's where the "would you like to apply changes?" screen was added in: https://github.com/projecthydra/sufia/pull/2700

**Comment by hackmastera** [comment]
I suspect this issue is linked to #301 and therefore is similarly blocked

**Comment by hackmastera** [comment]
I believe this is resolved as part of sufia upgrade (pr #407). @catlu please let me know if you see any more permissions bugs
