### ISSUE TITLE
Many thumbnails and preview derivatives contain tiny version of image in upper left corner

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#288]
It's so far unclear how to predict when this does / doesn't happen.

**Comment by sanfordd** [comment]
I don't have any evidence for this, but I suspect there's a composite option that's getting called somehow to overlay this smaller image.

**Comment by sanfordd** [comment]
It looks like this is due to some of the tiff files being tiled pyramid images with two layers, one full size and a second small thumbnail style tile.

**Comment by sanfordd** [comment]
I've confirmed that the tiffs were tiled in Sufia 6 so the change is in how the derivative generation treats the layers.

**Comment by hackmastera** [comment]
replicated in dev. must be in the code somewhere.

**Comment by hackmastera** [comment]
I can see the 2 pyramid layers when I do this

```
[aheadley testing 12:40:37]$ identify 2012-002_928.tif 
2012-002_928.tif[0] TIFF 2226x1650 2226x1650+0+0 8-bit sRGB 11.08MB 0.000u 0:00.000
2012-002_928.tif[1] TIFF 160x119 160x119+0+0 8-bit sRGB 11.08MB 0.000u 0:00.000
```

**Comment by hackmastera** [comment]
I think I can make it always only use layer 0. I don't know whether it's safe to assume that layer 0 is always the one we want.

**Comment by jrochkind** [comment]
@hackmastera I believe this has been fixed and can be closed?

**Comment by hackmastera** [comment]
I'd like to wait until I've actually run the job to close. Spoke with @sanfordd on Friday about running it on staging first. Not sure whether we'll wait until I get back to do that.

**Comment by jrochkind** [comment]
Is the job to run simply the `rake chf:create_derivatives` job?  Want me to try running it on staging, and then maybe production?  Should we run on production, once we get there, only with maintenance mode?

**Comment by hackmastera** [comment]
Yes that's the job but we're not sure whether it will clean up after itself or fill up the tmp drive. So either I should look at whether that will be an issue or we should keep an eye on /tmp while running it on staging. We want to make sure not to fill the drive on prod and crash the server.

**Comment by hackmastera** [comment]
finished on staging in `350m32.328s` (nearly 6 hours) with no errors.

**Comment by hackmastera** [comment]
Took twice as long on production. `Time: 12:46:27`
