### ISSUE TITLE
revise monthly metadata completion report

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#295]
Instead of checking how many objects have a title and description, search for how many objects in each department have the visibility set to "CHF-Only" versus how many are "Public". This should run at the first of every month.

**Comment by hackmastera** [comment]
Keep the two entries for each department, replace title test with visibility test.

**Comment by hackmastera** [comment]
Try to get this in place for the March 1st report.

**Comment by hackmastera** [comment]
There are other options besides 'CHF-Only' and 'Public'. I think we can implement this just as 'public' and 'not-public'.

Pretty sure 'private' and 'CHF-Only' (restricted) should both be considered incomplete. If you want more complex logic I can group 'lease' and 'embargo' with 'public' for the completion count. @catlu ?

**Comment by hackmastera** [comment]
note: https://github.com/projecthydra/hydra-head/blob/7a911e54a7cc0c49ca0e9cc8da1c6d47f9a467bb/hydra-access-controls/app/models/concerns/hydra/access_controls/access_right.rb#L4-L13

**Comment by catlu** [comment]
i agree on grouping 'private' and 'chf-only' as incomplete @hackmastera. i think we can leave out 'lease' and 'embargo' until we actually start using them.

**Comment by hackmastera** [comment]
before:
```
Archives: 1690 / 2122 (79%) records have titles
Archives: 1541 / 2122 (72%) records have titles and descriptions
Center for Oral History: 0 / 0 (100%) records have titles
Center for Oral History: 0 / 0 (100%) records have titles and descriptions
Museum: 174 / 174 (100%) records have titles
Museum: 128 / 174 (73%) records have titles and descriptions
Othmer Library of Chemical History: 63 / 156 (40%) records have titles
Othmer Library of Chemical History: 56 / 156 (35%) records have titles and descriptions
Rare Books: 130 / 434 (29%) records have titles
Rare Books: 81 / 434 (18%) records have titles and descriptions
Uncategorized: 246 / 368 (66%) records have titles
Uncategorized: 5 / 368 (1%) records have titles and descriptions
All divisions: 2303 / 3254 (70%) records have titles
All divisions: 1811 / 3254 (55%) records have titles and descriptions
```
After:
```
Archives: 1567 / 2122 (73%) records are published
Archives: 1518 / 2122 (71%) records are published with descriptions
Center for Oral History: 0 / 0 (100%) records are published
Center for Oral History: 0 / 0 (100%) records are published with descriptions
Museum: 174 / 174 (100%) records are published
Museum: 128 / 174 (73%) records are published with descriptions
Othmer Library of Chemical History: 63 / 156 (40%) records are published
Othmer Library of Chemical History: 56 / 156 (35%) records are published with descriptions
Rare Books: 127 / 434 (29%) records are published
Rare Books: 80 / 434 (18%) records are published with descriptions
Uncategorized: 5 / 368 (1%) records are published
Uncategorized: 1 / 368 (0%) records are published with descriptions
All divisions: 1936 / 3254 (59%) records are published
All divisions: 1783 / 3254 (54%) records are published with descriptions
```

Looks like a big change in 'uncategorized' for the most part, which probably means we are more accurately tracking completion.
