### ISSUE TITLE
Shared works page needs a visibility toggle/filter for "CHF-only"

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#296]
Once works are shared with a curator, they need to be able to see only the objects with visibility set to "CHF-only" so they can see their metadata backlog. We need to discuss how a toggle or filter would look in the UI and how to most easily achieve this on the backend.

**Comment by catlu** [comment]
On the UI end, my suggestion would be somewhere next to the "Sort by" and "Show" functions near the top of the various tabs.

**Comment by jrochkind** [comment]
I think we may already have this now, as a result of adding the facet to the general search, I think it magically appeared in this places requested here too. 

@catlu can you confirm this is now present?

The values in the facet are a bit confusing: "open" (means public), "authenticated" (means CHF only), "restricted" (means private). I know @catlu and @archivistsarah said they could handle that, but confirm that it will be handlable by other curators, or do we need to improve?

**Comment by catlu** [comment]
Would it be hard to change the values? If it's not a time-consuming fix, I think it'd benefit the other curators.

**Comment by archivistsarah** [comment]
while my daily workflow doesn't specifically use this facet, I think it will be helpful for everyone! 

also +1 to changing the values to "public," "chf only," and "private"

**Comment by jrochkind** [comment]
@archivistsarah can you confirm that feature is already there?

I will look into changing the labels, should be do-able, and I'll leave this open til I change them. 

Keep in mind "chf-only" _really_ means "anyone with an account only".... at least I think it does. Currently we only give accounts to CHF people.

**Comment by archivistsarah** [comment]
Yep, it's there under the label "Visibility (Staff-only)"
