### ISSUE TITLE
 Edit URI location

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#302]
To move Fedora out to another server, we will need to change the URIs of currently ingested objects to refer to the new Fedora machine. 

URIs should use internal IPs.

As a sysadmin I need to be able to run script to change all content URIs to use a new IP so that I can successfully migrate the fedora data to a new machine.

We'll need to make sure sufia's fedora.yml also uses the new URI

**Comment by hackmastera** [comment]
I believe this will be a job for https://github.com/fcrepo4-labs/fcrepo-import-export

It is marked as WIP and a list of open issues is here https://jira.duraspace.org/browse/FCREPO-2369?jql=project%20%3D%20FCREPO%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened%2C%20%22In%20Review%22%2C%20Received)%20AND%20component%20%3D%20f4-import-export

@sanfordd do you want to comb through those open issues and pick out any potential dealbreakers? Esme says the biggest missing feature is there is not support for versions; only the most recent version of any object will be migrated. I think for us that is not actually a problem, but should probably check with @MDiMeo and @catlu to make sure.

**Comment by sanfordd** [comment]
I'll dig through the issues to see what I can find.

**Comment by hackmastera** [comment]
Thanks @sanfordd. I just took a look through the list as well.

**Comment by sanfordd** [comment]
The only thing I see offhand is the note about unicode escaped characters, but I don't think any of our naming schemes use anything that would hit that.

**Comment by hackmastera** [comment]
Great. Yeah, all the validation-related tickets are a little doubt-inducing but I think we should test this out. hooray, data migration!

**Comment by sanfordd** [comment]
@hackmastera That's the nice part of staging and keeping a backup of the data. Next week should be a good time to try this out.

**Comment by hackmastera** [comment]
@sanfordd I looked at this code with my code reading group today. It looks good; straightforward. I had a followup question for Esme about the predicate and to export the whole repo we should just accept the default. If we want to export one work and all its files we would do `--predicate http://pcdm.org/models#hasMember,http://www.w3.org/ns/ldp#contains`

**Comment by sanfordd** [comment]
After talking about this issue Friday and looking things over, I think we can just migrate the disk over to a new machine (along with the database) and have things resolve by using the internal IP of the machine. No need to import/export data.
