### ISSUE TITLE
upgrade to rails 5

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#306]

**Comment by hackmastera** [comment]
one issue is that rails 5 uses puma as its default webserver. puma is multithreaded and this sometimes results in locking issues with SQLite. However you can still use webrick just by passing it as an argument to `rails s`

**Comment by hackmastera** [comment]
or we could use postgres in development.

**Comment by jrochkind** [comment]
Tagged as before soft launch, but prob not til after we get sufia upgrade merged, so I'm going to mark 'blocked' til then.

**Comment by hackmastera** [comment]
will be required for hyrax 2.x

**Comment by hackmastera** [comment]
duplicate of #545
