### ISSUE TITLE
Facets overhaul / configuration

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#308]

**Comment by catlu** [comment]
Hey @hackmastera, in the absence of any other high priority tickets, I would say maybe this one could be medium for me, mostly for metadata cleanup purposes and to get a sense of how we can bring together works for the frontpage.

**Comment by hackmastera** [comment]
@catlu I was just about to start looking at it. Here is the list (copied from basecamp):

- Subject/Topic
- Maker/Creator
- Genre
- Type
- Division
- Date
- Rights

Lower priority facets:
- Language
- Place
- Medium
- Collection

**Comment by hackmastera** [comment]
@catlu is that the right order?

**Comment by hackmastera** [comment]
@catlu we are getting rid of the collection / work facet?

**Comment by MDiMeo** [comment]
@catlu @hackmastera I think we should keep Collection for now. But instead of faceting on Type of Work, can it just be called Collection and show collections?

**Comment by hackmastera** [comment]
@MDiMeo I assume that's what's meant by the last one on the list, 'collection'.

I was asking about the facet which in the interface is called 'type of work'. sorry I wasn't clear.

**Comment by MDiMeo** [comment]
@hackmastera Right, yes. Thanks. I had assumed we were replacing Type of Work with just Collection, so yes we'd get rid of that Type of Work facet, but I'll leave @catlu to confirm.

**Comment by hackmastera** [comment]
@MDiMeo that makes sense, as a collection facet will essentially list all the collections, plus we can always provide a link to that sort of results page if desired down the line. Currently the lack of nice images for collections makes listing them all not super appealing.

**Comment by MDiMeo** [comment]
@hackmastera Agreed!

**Comment by hackmastera** [comment]
Note: a reindex will be required on deploy.

**Comment by catlu** [comment]
Yep, agree with you guys!

**Comment by catlu** [comment]
Here's a rough order so far. Open to discussion, and I'm curious to see how they look after they're configured, too. I think we may shift them around a bit (based on counts and the actual ability of the data as entry points into our records).

Subject/Topic
Maker/Creator
Genre
Type
Medium
Place
Language
Date slider?
Rights
Division
Collection

**Comment by MDiMeo** [comment]
I agree that we may have to adjust this once we actually see what it looks like and test them.

For starters, I like this list and the order, but I think the Date Slider and Rights should go towards the bottom.  I've seen these two towards the bottom on other digital collection facets and have come to expect them there. What do you think of that suggestion @catlu?

**Comment by catlu** [comment]
Yep, that makes sense @mdimeo. Let's go with:

Subject/Topic
Maker/Creator
Genre
Type
Medium
Place
Language
Division
Collection
Date slider?
Rights

__________________________________

Cathleen Lu
Digital Projects and Metadata Librarian
Othmer Library of Chemical History
P: +1.215.873.8216
F: +1.215.629.5216

Chemical Heritage Foundation
LIBRARY • MUSEUM • CENTER FOR SCHOLARS
315 Chestnut Street  •  Philadelphia, PA 19106 • U.S.A.
chemheritage.org<http://www.chemheritage.org/>


On Feb 23, 2017, at 9:30 AM, Michelle DiMeo <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree that we may have to adjust this once we actually see what it looks like and test them.

For starters, I like this list and the order, but I think the Date Slider and Rights should go towards the bottom. I've seen these two towards the bottom on other digital collection facets and have come to expect them there. What do you think of that suggestion @catlu<https://github.com/catlu>?

**Comment by hackmastera** [comment]
related: #348

**Comment by jrochkind** [comment]
"Format instead of Resource Type, and Department instead of Division" => should this apply to Admin/editing/back-end interface too?  

@hackmastera Do you think we should try to change the actual underlying field names too, or just leave them with names not completely matching?  Not sure what I think, I'd rather not do it, but it could end up confusing for us.

**Comment by hackmastera** [comment]
I would rather not change the underlying fields.

**Comment by MDiMeo** [comment]
I don't have a strong opinion about the admin side because I'm mostly concerned with end users. @clu can weigh in on whether she thinks it will be confusing not to change it. My assumption is that it would be easier not to change on the metadata ingest form, right?

**Comment by catlu** [comment]
Could be confusing, but since it's gonna be a pain, let's not change the admin stuff now? I can either explain to people or revisit the issue later if it comes up more often.

**Comment by jrochkind** [comment]
It's possible it will a pain _not_ to change it in admin. I think it should prob be changed in admin, I'll do it if I can, cool?

It think it will be confusing in the future for us developers to not change the underlying internal field names, but i agree with @hackmastera that's probably not feasible to deal with at the moment, is what it is.

**Comment by catlu** [comment]
Cool, that sounds good.
