### ISSUE TITLE
Relevance tuning

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#310]
- [x] Determine baseline relevance tuning: e.g. boost title, subject, creator above everything else
- ~Make sure stemming is happening in the right places (more aggressive stemming: #480)~ decided not to do for now. 
- [x] Review stopwords list -- i.e. do we have one?

(not for now: Maybe boost collections and parent works over other stuff. )

**Comment by catlu** [comment]
Initial thoughts: **Title** and **alternate title** ranked highest; then **creator** (I'd want Louis Pasteur notes to show up before stamps about him) and **genre** (I'd want things that are scientific instruments to show up before things about them); **subjects**; **description**; rest of fields (can't currently think of medium, place, language, or department keywords that should be weighted more than description).

It would also be cool if collections and parent works came up higher than the rest of the works, but not sure if that fits in here.

**Comment by jrochkind** [comment]
Shall I work on this to @catlu 's "initial thoughts", or wait for more discussion?

**Comment by hackmastera** [comment]
@jrochkind go for it!

**Comment by jrochkind** [comment]
Re: Make sure stemming is happening in the right places

I think our search fields are all [*_tesim](https://github.com/chemheritage/chf-sufia/blob/d9c0b999e8dc7529e2403a6c2617f2faa873fd05/solr/config/schema.xml#L211), which is type `text_en`. 

[text_en uses the EnglishMinimalStemFilterFactory](https://github.com/chemheritage/chf-sufia/blob/d9c0b999e8dc7529e2403a6c2617f2faa873fd05/solr/config/schema.xml#L134-L146)

"EnglishMinimalStemFilterFactory is less aggressive than PorterStemFilterFactory" .  EnglishMinimal seems to be a newer addition to Solr than PorterStem, so perhaps is preferred as a basic default? Something generated it into our schema.xml, so someone chose it, whether Solr or BL/Hydra. I can't find any docs on the differences what they actually do. 

But stemming does seem to be happening according to config. But I can't actually find any searches that demonstrate this. Not sure why stemming isn't happening if it's not. 

Should we try the more aggressive PorterStemFilterFactory and see if we like it better?  I think I've used PorterStemFilterFactory in the past, I don't think EnglishMinimal existed when I worked on this previously. Would require a solr restart. 

@hackmastera

**Comment by jrochkind** [comment]
Re: "Review stopwords list -- i.e. do we have one?"

It looks to me like we do not, and that that is fine. I just searched for "and" as a query, no problem, and got proper results. I think that's fine. 

Check that checkbox off @hackmastera ?

**Comment by hackmastera** [comment]
@jrochkind Sure, give it a shot. I think I have heard people complain about not getting the stemming behavior they expect, although it's possible that was a conflation of stemming with the fact that almost nothing was getting searched.

Also, 👍  re: stopwords

**Comment by jrochkind** [comment]
You can investigate stemming in the Solr 'analysis' thing, it will show you what gets stemmed... I can't find _anything_ that gets stemmed, nothing I enter gets stemmed, doh!

http://hydra.chemheritage.org:8983/solr/#/collection1/analysis?analysis.fieldvalue=description&analysis.fieldtype=text_en&verbose_output=1

**Comment by jrochkind** [comment]
Ah, EnglishMinimal _does_ take off plurals. Sometimes. It removes the 's' to normalize singular/plural. It does do _something_.  I think the more aggressive porter one is what people want. 

Will probably require a reindex with downtime. After the solr type is changed, the index will behave unpredictably until reindex. (If we had master/slave solr index, this would be easier to do without downtime).

**Comment by jrochkind** [comment]
The PorterStemmer is going to do weird things to non-English text though. We can try it on staging I guess. Maybe we should wait until we have other relevancy things tuned a bit more, so people trying it with Porter can have a better starting place to see if it makes things terrible. And get some German-language speakers to enter queries, if we care about that. (We've got a lot of German I think). 

In an ideal world, we'd have our text strings tagged as to language, so we could do the proper stemming and other analysis based on language... but we don't.

**Comment by hackmastera** [comment]
Oh yeah I forgot about solr's analysis tool!

In general where we have other languages it is probably just titles (@catlu can correct me if I'm wrong) and they'll have translated titles as well. I think it's okay to treat this as an English-language catalog. We can also include a couple of German title searches in our formal eval to see how it goes.

Not sure what you mean by "other relevancy things tuned a bit more" -- you mean do a round of eval before changing the stemming?

**Comment by jrochkind** [comment]
I think I basically meant merging and deploying #457. If that's on production, and we do equivalent but with PorterStemFilter factory on staging, then the two can be easily compared. 

Is there any easy way to refresh staging with production data, @sanfordd ?

**Comment by hackmastera** [comment]
I propose moving the last check box to its own issue and discussing whether it might be something we could do between soft / hard launch with other user testing
