### ISSUE TITLE
Failed FileSetAttachedEventJobs lead to ArgumentError in polymorphic_routes

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#315]
https://gist.github.com/sanfordd/98499bb8b8db5b3695832515517e60d1
https://gist.github.com/hackmastera/db4015ed9f80439083e92428a1d2ffcc

User saved a work after uploading some large number of files. 100?

Then what happened? @catlu can you provide a play-by-play of what you did after saving?

**Comment by hackmastera** [comment]
FileSets other than the 3 which listed in the resque log are failing to load, however.

**Comment by catlu** [comment]
Uploaded 100 files, waited till they completed, saved record. As they were processing, went into record to edit metadata and then also add another 28 files, waited till they completed, and saved record.

**Comment by hackmastera** [comment]
After saving the metadata and additional files, @clu waited until all the thumbnails were generated. Then went into file manager to sort the files. Saved file manager and went back to the work. It was at this point she noticed that all the files between numbers 38 and 89 were missing. Later, @sanfordd went to check if they had been added and found that many filesets do not load. Missing files never appeared.

**Comment by hackmastera** [comment]
I've replicated the first portion of this timeline on dev. Added 54 files, saved, then followed up with metadata edits and adding 3 more files. 4 files near the start of the original set failed to fully attach to the work. I can see in the console, e.g.

```
> f = FileSet.find 'n583xv002'
ActiveFedora: loading fedora config from /home/ubuntu/chf-sufia/config/fedora.yml
ActiveFedora: loading solr config from /home/ubuntu/chf-sufia/config/solr.yml
Attempted to init base path `dev`, but it already exists
=> #<FileSet id: "n583xv002", label: "edible-spoons.jpg", relative_path: nil, import_url: nil, part_of: [], resource_type: [], creator: ["aheadley@chemheritage.org"], contributor: [], description: [], keyword: [], rights: [], rights_statement: [], publisher: [], date_created: [], subject: [], language: [], identifier: [], based_near: [], related_url: [], bibliographic_citation: [], source: [], head: [], tail: [], depositor: "aheadley@chemheritage.org", title: ["edible-spoons.jpg"], date_uploaded: "2017-02-01 16:05:45", date_modified: "2017-02-01 16:05:45", access_control_id: "339f7cd7-837c-4bac-8f97-3976d947bcaa", embargo_id: nil, lease_id: nil>
[5] pry(main)> f.parent
=> nil
[6] pry(main)> f.in_works
=> []
```

**Comment by hackmastera** [comment]
@catlu I'm replicating this first part of the problem even without adding additional files. Just editing metadata interferes with the file attachment jobs.

**Comment by hackmastera** [comment]
next step: replicate on a base sufia instance.

**Comment by hackmastera** [comment]
replicated on sufia 7.2.0 / curation concerns 1.6.3 with sidekiq

**Comment by hackmastera** [comment]
this issue actually covers two different errors. split out; closing this in favor of #316 and #317
