### ISSUE TITLE
ArgumentError (Nil location provided. Can't build URI.): actionpack (4.2.7.1) lib/action_dispatch/routing/polymorphic_routes.rb:213:in `polymorphic_method'

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#317]
This initially seemed linked to #316 but I haven't been able to replicate it in the process of working on that bug. This needs more investigation.

https://gist.github.com/sanfordd/98499bb8b8db5b3695832515517e60d1

See #315 for more background. https://hydra.chemheritage.org/concern/generic_works/sb3978325 is still affected.

**Comment by hackmastera** [comment]
Looks like another bug due to solr's default rows returned being 10. see `def parent` in sufia: app/presenters/sufia/file_set_presenter.rb

**Comment by hackmastera** [comment]
Hm, that is actually not what's happening.

Somehow the fileset displays on the work's item list, but is not actually in the work's item list in solr or in fedora.

**Comment by hackmastera** [comment]
The work has 62 members saved in fedora/solr. The presenter gets 78.

**Comment by hackmastera** [comment]
I'm inclined to assume that once we disallow the type of overwriting saves as reported in #316 that we won't see this anymore.

I'm leaning towards just repairing the data manually, probably by removing the discrepancies from the ordered_member list and then re-adding them.

**Comment by hackmastera** [comment]
hilariously, there are discrepancies in both directions.
```
> ordered_discrepancies = w.ordered_member_ids - w.member_ids
irb(main):057:0> ordered_discrepancies.count
=> 20
> unordered_discrepancies = w.member_ids - w.ordered_member_ids
irb(main):060:0> unordered_discrepancies.count
=> 4
```

**Comment by hackmastera** [comment]
All filesets now load.

gathered all the ids from both lists into one array, deduplicated the array, then removed them all from both lists, then added them back on as ordered_members, using this as a model: https://github.com/projecthydra/curation_concerns/blob/master/app/actors/curation_concerns/actors/add_to_work_actor.rb#L16

Currently searching for other file sets by title that have been saved in fedora but not attached to the work.

**Comment by hackmastera** [comment]
@catlu I found another 47 files that were in fedora but not attached to the work. I've added them and now the work has 129 members / ordered members. Please confirm that everything is there and if it is please close this issue. Thanks!

**Comment by hackmastera** [comment]
for future reference
```
files1 = []
FileSet.find_each do |fs|
  begin
    files1 << fs if fs.title.first.starts_with? '2008.043.001_'
  rescue NoMethodError
    puts fs.id
  end
end
```
Then get the ids and diff them against the members on the work to get files to add.

**Comment by catlu** [comment]
all there! thanks @hackmastera!
