### ISSUE TITLE
Additional works that may have orphaned files in Fedora/files that led to errors

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#319]
https://hydra.chemheritage.org/concern/generic_works/ft848q626
all files would be 'b1064821_###.tif'

https://hydra.chemheritage.org/concern/generic_works/pn89d658s
all files would be 'b10512093_###.tif'

https://hydra.chemheritage.org/concern/generic_works/kh04dp745
all files would be 'b10512093_###.tif'

https://hydra.chemheritage.org/concern/generic_works/9593tv15x
'b10680056_###.tif'

Re: the orphaned files--if there were any missing, I reuploaded them to the record without realizing it errored out, so they could probably be deleted?

**Comment by hackmastera** [comment]
@catlu I ran a list of all file sets with no parent. here's what I came up with. what do you think?

```
> orphan_files.each { |fs| puts "#{fs.id}: #{fs.title}" } ; nil
z029p5015: ["2002.12_b112_f87_008.tif"]
q524jp117: ["2012-002_328.tif"]
vh53wv994: ["2012-002_330.tif"]
f4752g966: ["2012-002_327.tif"]
kh04dq03d: ["2012-002_329.tif"]
dv13zt57k: ["2012-002_326.tif"]
n296wz145: ["b10680056_008.tif"]
9z902z939: ["2008.047.172G.tif"]
nk322d35b: ["2008.047.172I.tif"]
rv042t11v: ["2008.047.172K.tif"]
474299185: ["2008.047.172L.tif"]
```

**Comment by catlu** [comment]
awesome! so all the 2012-002 ones are beckman, heads up @archivistsarah. also maybe the first file is yours as well?

n296wz145: ["b10680056_008.tif"] is part of one of the books above, and i had reuploaded the file, so that's probably a duplicate at this point.

these are from a museum work i didn't catch, so attaching them would be great!
9z902z939: ["2008.047.172G.tif"]
nk322d35b: ["2008.047.172I.tif"]
rv042t11v: ["2008.047.172K.tif"]
474299185: ["2008.047.172L.tif"]

**Comment by hackmastera** [comment]
@catlu sure which work should I attach the museum objects to?

**Comment by catlu** [comment]
0r9673780 @hackmastera

**Comment by catlu** [comment]
https://hydra.chemheritage.org/concern/generic_works/0r9673780

**Comment by archivistsarah** [comment]
neither megan nor I have access to those works, and according to our tracking, those filenames belong to files that were successfully ingested and are children of this parent work: https://hydra.chemheritage.org/concern/generic_works/w9505077h

it may be safe to delete those files?

**Comment by hackmastera** [comment]
refs #317

**Comment by hackmastera** [comment]
The 4 museum ones have been added to the work and the rest have been deleted. Go forth and carefully wait for files to be processed before updating works in any way!
