### ISSUE TITLE
date created / modified not displaying for migrated works

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#322]
They were copied over as strings and cannot be indexed that way.

run through all works, check the class of each date and parse them if needed
```
work.date_uploaded.class == String
work.date_uploaded = DateTime.parse(work.date_uploaded)
work.date_modified = DateTime.parse(work.date_modified)
```
brought to our attention by PSU
https://github.com/psu-stewardship/scholarsphere/compare/i%23574?expand=1#diff-c5f78d950658d0c37e52fc25fc0938baR22

**Comment by jrochkind** [comment]
The github link "brought to our attention by PSU" alas no longer resolves to anything, perhaps PSU rewrote history in their git repo.

**Comment by hackmastera** [comment]
Reopening to remind us to run the task.

**Comment by jrochkind** [comment]
task has been run
