### ISSUE TITLE
Work is broken

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#324]
The following work:
https://hydra.chemheritage.org/concern/generic_works/bv73c051k
is broken and cannot be accessed. Trying to go to it generates the following error:

F, [2017-02-09T10:15:41.413432 #2783] FATAL -- : 
SystemStackError (stack level too deep):
  app/views/curation_concerns/base/show.html.erb:16:in `_app_views_curation_conc
erns_base_show_html_erb__2356227276365167806_70082306772020'

**Comment by hackmastera** [comment]
The files weren't all attached. The file that is designated as the thumbnail in particular is not attached and that is what causes this stack error.

**Comment by hackmastera** [comment]
fixed it.
