### ISSUE TITLE
Description field: data cleanup and presentation

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#327]
- [x] Replace instances of `<p>` with "\r\n\r\n"
- [x] Whitelist selected html tags at save time (render time maybe?)
- [x] Render field as html_safe (whitelisted html tags).
- [x] Convert line breaks at display time

Discussed with @jrochkind

**Comment by jrochkind** [comment]
@hackmastera remind me our whitelist of allowed tags?

I think `<b>`, `<i>`, `<cite>`, and `<a>`? Don't allow explicit `<p>` or `<br>`, but translate line breaks accordingly. Is this right?

**Comment by hackmastera** [comment]
I think also `<em>` and `<strong>`. Probably we should put this list in config/application.rb

**Comment by jrochkind** [comment]
I think we should make people use either `<em>` and `<strong>`, _or_ `<b>`, `<i>`, there's no reason to allow both. I think they'll usually want to be formatting in a case where they actually _want_ to specify bold or italic (for citation formatting or something), so that makes more sense. 

But no big deal, we can allow both too, probably not worth as much time as I'm spending on it, sorry!

**Comment by hackmastera** [comment]
Then maybe convert one to the other? I am mostly thinking that different people may know different bits of html and it would be nice to accommodate that.

**Comment by jrochkind** [comment]
Okay we'll allow both then!  I would have said tell them what's allowed and they can learn to use it, but you know our users better than me!

**Comment by jrochkind** [comment]
if people are assuming that `<strong>` always means "bold face" etc though, they're doing it wrong, and may have their assumptions violated in the future.

**Comment by hackmastera** [comment]
that's a good point; we don't want to limit our own usage of these tags by allowing them here.

okay I'm convinced; let's just do `<b>` and `<i>`

This was one case where I found out what people were doing and I had no idea; so in this case my caution is borne of not knowing the users :\

**Comment by catlu** [comment]
Do you want me to ask around and see what curators are using for easier converting?

**Comment by jrochkind** [comment]
Are we converting existing entered text? How so?

**Comment by hackmastera** [comment]
currently we have "replace `<p>` with `\r\n\r\n` maybe we should add replacing `<br>` with `\r\n`.

Do we want to run a report to see what tags are in there? would probably help us make a better decision moving forward

**Comment by catlu** [comment]
I need to check but I'm pretty sure I saw `emph` at one point.

**Comment by jrochkind** [comment]
Is `emph` even a tag? Okay, I've got to bunch to do here before I get there, but you can check, or I can check, or whatever, we can add another bullet point for "check" if you want. I didn't realize we were planning on doing that.

**Comment by hackmastera** [comment]
I don't think we were planning to, or even necessarily are. I just thought it might help inform these decisions. What are our options?

- pull a report of tags used in description field to help us determine whitelist
  - optionally convert some of these if we think they translate to whitelisted values
- or, simply create a whitelist from what we have and anything else continues to show up as if it were part of the data / text.

am I missing an option? I don't feel strongly about this. 2 would be easier. And it's probably fine; I don't think people have been doing a ton of html.

And yeah, I don't think <emph> is a tag. I also don't see i in there. I did a search for 'br' and definitely turned up results drawing from the description field. nothing comes up when you search 'emph'

**Comment by hackmastera** [comment]
`strong` is not in use. `em` definitely is.

**Comment by jrochkind** [comment]
1. You don't always actually need to put an `<a>` in, if you just put a `http` or `https` URL in, sufia will automatically turn it into a link. This may or may not be desirable behavior, but it's there: 
![screen shot 2017-03-16 at 2 23 39 pm](https://cloud.githubusercontent.com/assets/149304/24012392/3469848c-0a54-11e7-8dbe-908c58d6b6ed.png)

2. Allowing HTML interferes poorly with the previous truncation feature. Now we need HTML-safe truncation, to avoid truncating eg after a `<b>` tag but before it's `</b>` tag. I guess we just need that, I don't see any way around it. This is do-able, I've done it before, but it's kind of hacked together, I should probably go ahead and make a gem for my hacky code.

**Comment by jrochkind** [comment]
So each place the description is displayed seems to need a separate intervention to make sure it's formatted right. 

I have have the 'index' (search results), and 'show' (what you get when you click on a record) --- are there any others?

**Comment by hackmastera** [comment]
I believe that's it but I'll tag @catlu to confirm

**Comment by catlu** [comment]
Yeah I think that's it for description displays.

**Comment by jrochkind** [comment]
Reopened for bug:

~~~
not sure if related but looks like description truncation affects the record view too, https://hydra.chemheritage.org/concern/generic_works/5138jd91b and https://hydra.chemheritage.org/concern/generic_works/6t053g02h for reference
~~~

**Comment by jrochkind** [comment]
Fixed, thanks @catlu
