### ISSUE TITLE
Update fields displayed for search results

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#330]
Specifications needed.

**Comment by catlu** [comment]
Currently, it displays:
(test record: https://hydra.chemheritage.org/concern/generic_works/w37636967/)
Title on top, then 1) description 2) subject, 3) maker (all), 4) owner, 5) language, 6) rights, 7) resource type.

New display: Title on top, 1) alternate title, 2) description (3 lines max?), 3) date, 4) maker (all), 5) subject, 6) genre.

@MDiMeo do you have any thoughts? do we still want resource type or rights in the display?

**Comment by jrochkind** [comment]
Hmm, maybe "contained in generic work" too?  

I think that's pretty significant info for understanding what you're looking at?

I don't like that label or the way it's displayed currently -- I think it needs more than just the title to identify the work. But until we get to improving that (probably post soft launch)...

@catlu?

**Comment by hackmastera** [comment]
I like that idea. "Part of"?

**Comment by catlu** [comment]
good call @jrochkind i think that's important. maybe after alternate title (1.5) or near the end?

**Comment by jrochkind** [comment]
okeydoke. I can change the label "contained in generic work" to something else, like anna's suggested "part of", if it's obvious what to change it to. Otherwise we can leave that for later -- I do think this display needs more work than just changing the label, but prob not til after soft launch.

**Comment by jrochkind** [comment]
Okay, so after much banging my head against code, I've determined that, believe it or not, it's very challenging to add "Contained in generic work" to the search results page. Because hydra architecture. 

I still think it's important, and still want to do it, but I think it's probably out of scope not only for this issue but for pre-soft launch timeline. :(

**Comment by hackmastera** [comment]
Curation concerns 2.0 (and by extension hyrax) reverses collection membership such that these relationships would be stored on the child. That will make this much easier. Unfortunately, the required data migration script for this upgrade does not yet exist.

**Comment by jrochkind** [comment]
Well, we can write it ourselves, if we have to, when we get there.
