### ISSUE TITLE
Implement rights / usage disclaimer

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#332]
Design needed.

**Comment by MDiMeo** [comment]
At the[ DCC meeting on Feb 23, 2017](https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/45911262/DCC+Minutes+2017+2+23), we discussed adding RightsStatement.org buttons or Public Domain icons next to the Download Button. This is in addition to having the full Rights information in the metadata.

I've attached two mock-ups to start the discussion. The potential issue I found is that Public Domain mark is smaller and can fit at the side and the full Rights Statement icon is larger and will need to go below. Assuming we are fine with either design, the next step is probably to go back to DCC and see if they have a preference. 
![download rights 1- public domain mark](https://cloud.githubusercontent.com/assets/11823009/24658635/475213a2-1918-11e7-9ed6-940f445c01de.jpg)
![download rights 2 - noc-us](https://cloud.githubusercontent.com/assets/11823009/24658639/4a16f2a6-1918-11e7-97ed-d4d044b0e4bf.jpg)

**Comment by hackmastera** [comment]
Another option would be to put the pub. domain below, as well, with the words "Public Domain" next to it (with some styling to make them the right size)

**Comment by hackmastera** [comment]
These don't look like the assets on rightsstatements.org. Do we need to contact them to get the actual graphics?

**Comment by MDiMeo** [comment]
Yes, I agree about putting PD below with some words if folks like how it looks below. Personally, I think I prefer seeing it underneath, and I think the added text is helpful.

Those are the images I got when I right clicked on the image. I also thought it was weird that they looked slightly different. When I tried downloading and saving I got an SVG file that was unusable. But now I see there are PNGs here so I can try redoing it with these: http://rightsstatements.org/en/documentation/assets.html I'll look for a full PD icon too and see what that looks like below.

**Comment by MDiMeo** [comment]
Please use the white background and blue text files as can be found in the comment above. Use full button with text and make it roughly the size of the Download button, appearing directly 
![page with smaller in copyright blue text](https://cloud.githubusercontent.com/assets/11823009/24669652/34266492-1939-11e7-864c-ff6cf152199f.jpg)
below it. The image should be hyperlinked to the URL in the same way that the text already is in the Rights metadata field. We are exploring options for Public Domain, but this should work for everything that uses RightsStatements.org.

**Comment by jrochkind** [comment]
> When I tried downloading and saving I got an SVG file that was unusable. 

I think the SVG's aren't unusable, they are just white text on a transparent background, so they looked invisible. We can supply our own background in CSS. SVG is a nice format for this kind of thing, recommend using the SVG's after all.

**Comment by MDiMeo** [comment]
The SVGs weren't usable for me, but you should definitely feel free to use them! We agreed that we would like to use the Public Domain "no copyright" icon that matches the "c" being crossed out that the user would see when they click on the Public Domain link. We would prefer that it has a white background and blue text that says Public Domain that appears similar to those used for RightsStatements.org. I don't think I have a graphic program that can create an SVG though.

**Comment by jrochkind** [comment]
> Please use the white background and blue text files as can be found in the comment above. 

You mean this one: http://rightsstatements.org/en/documentation/assets.html

So we still don't have a "public domain" one to use, yes? I know @MDiMeo is on vacation, but anyone else know?

**Comment by MDiMeo** [comment]
Correct @jrochkind -- this is where we left off. Thanks for emailing them and CCing me today. I think the issue is that the Public Domain link/symbol we're using is controlled by Creative Commons and everything else we've used is under RightsStatements.org. It'd be great if we could get the font and color so we can make our own PD symbol to make the ones provided by Rights Statements. If not, we an take our best guess and try to match as closely as possible.

**Comment by jrochkind** [comment]
We can also just use their graphics without text (they have the c and the anti-c), and provide our _own_ text, just in HTML.  Make logotypes ourselves in HTML. That way all the fonts will match, with whatever font we choose -- and be text visible to screen-readers etc too. I might try that.

**Comment by hackmastera** [comment]
@jrochkind I like this idea

**Comment by jrochkind** [comment]
Their logos, I think, use the Gotham font, which is not free. I think just a Helvetica is going to work fine, although there are some free alternatives which are closer. I don't see any reason the font in our rights statements needs to match theirs exactly, as long as all ours match each other.

**Comment by hackmastera** [comment]
agree. actually I think it might be better to just use something that works with our own site; whatever the header font is, e.g., and give it our internal link color. Just use the appropriate small logo instead of trying to mimic their whole thing.
