### ISSUE TITLE
Place facet

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#346]
Place facet should draw from 3 different properties; values should probably be copied into a 4th field to be used for faceting.

**Comment by hackmastera** [comment]
this would be done exactly the same way the maker facet was done.

**Comment by jrochkind** [comment]
@hackmastera what are the three different properties? Do they currently exist, or need to be created?

I actually see four potential already ones: `place_of_interview`, `place_of_manufacture`, `place_of_publication`, and `place_of_creation` -- are those them, you want those four aggregated into a single facet?

**Comment by hackmastera** [comment]
@jrochkind yes there are 4; sorry there were originally 3 so that was stuck in my mind I guess.

**Comment by hackmastera** [comment]
Let's keep it open until the reindex runs so we don't forget to do that?

**Comment by jrochkind** [comment]
I am not certain if this has been run or what happened with this. @hackmastera any idea?

**Comment by hackmastera** [comment]
No it hasn't been run; I don't recall either of us doing a full reindex.

However, when you ran the other tasks last night every single record that saved was also reindexed, so the facet is pretty well populated, ha! It's just the records that didn't need to be changed for any of those data tasks that didn't reindex.

**Comment by jrochkind** [comment]
reindexed
