### ISSUE TITLE
Grab Hydra ids of records with bracketed text in title

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#347]
I will move the translations to alt title field after ordering update.

**Comment by hackmastera** [comment]
@catlu Here is the report: https://gist.github.com/hackmastera/0ea9825875b2a0d134022b7c05e32200

each id shows `title`, `additional`, and `rest`. This is just how I pulled them, assuming anything before a bracket would become the new title, anything in brackets would become a new additional title, and anything after would... I don't know exactly but I was pretty sure you'd want to see it if it was there. The current title actually looks like "title [additional] rest" -- let me know if you have any questions.

From a brief scan, I don't think all of these will be treated the same. It occasionally looks like brackets were used for something other than translation, or that the translation is only partial.

But if there is a rule you can tease out I would be glad to do an automated update; just let me know.

**Comment by catlu** [comment]
Thanks for this, @hackmastera! I can pretty easily spot the ones where brackets have been used for translation with `rest` and I think editing them manually makes more sense. There aren't too many, so should be fine.
