### ISSUE TITLE
'creator' will be used for digitizer

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#35]
make sure this is coming through with a label that makes sense

**Comment by hackmastera** [comment]
@catlu - I don't see this one on the application profile; do you want me to surface it in the form / display?

**Comment by catlu** [comment]
Is this the Sufia 'creator' that we decided to mean depositor? If that's the one, let's not display it.

**Comment by hackmastera** [comment]
Well, depositor is its own field which uses http://id.loc.gov/vocabulary/relators/dpt

In sufia, this creator is being used more or less as author -- here's the help text:
"The person or group responsible for the file being uploaded. Usually this is the author of the content. Personal names should be entered with the last name first, e.g. &quot;Smith, John.&quot; &lt;em&gt;This is a required field&lt;/em&gt;."

This is the field that was being auto-filled with the logged-in username.

We had talked about using it more literally as file creator -- i.e. the person who scanned the image.

**Comment by hackmastera** [comment]
Cat is going to look into a digitized_by field / predicate.  A new ticket will be created for the addition of that field.
