### ISSUE TITLE
List of fields that should be searched with keyword 'all fields' search

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#351]

**Comment by catlu** [comment]
re: convo with @hackmastera on additional fields to be indexed:

- Maker fields
- date
- place fields
- genres
- medium
- extent
- inscription
- division
- series
- physical container
- related url
- rights
- rights holder
- additional credit
- file creator
- admin note

(used this record for reference: https://hydra.chemheritage.org/concern/generic_works/w37636967)
I listed every single field that didn't come up in a keyword search, but maybe worth discussing if some fields like physical container or related url should be indexed?

**Comment by hackmastera** [comment]
Okay it looks like the way to do this is to add them all as "show fields" which I've always pretty much ignored because we don't use the blacklight show page.
https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#show-view

https://github.com/chemheritage/chf-sufia/blob/master/app/controllers/catalog_controller.rb#L134

**Comment by jrochkind** [comment]
> Okay it looks like the way to do this is to add them all as "show fields"

That doesn't actually make sense to me. But have you tried it and it worked? I don't think 'show fields' should effect indexing. If not, I think you a) have to make sure it's being indexed in some field, which involves solrizer/GenericWork configuration, and b) make sure the field it's indexed into is included in the search query, which if it's a new field instead of just dumping it into an existing field, involves search_field and/or solr defualt params config in CatalogController.

**Comment by hackmastera** [comment]
@jrochkind I changed the title to reflect that this isn't actually about indexing, but about what fields are being searched in the 'all fields' default search. does that make more sense?

**Comment by hackmastera** [comment]
Alternately we could change the way 'all fields' gets its list of fields. I guess using the show fields was just a convenient shortcut.

**Comment by jrochkind** [comment]
ah, it's already indexed, just not being searched? Yeah, I think there's a better way to get it into the fields being searched than adding it to show_fields, but haven't looked at the details yet myself. But whatever works!

**Comment by jrochkind** [comment]
one could certainly imagine wanting more fields indexed than are included in `show_fields`. We're not using `show_fields` at all now, but still makes sense to keep it tidy and sensible, rather than abuse it for something it wasn't intended for. Maybe. But also, whatever works.

**Comment by hackmastera** [comment]
@catlu It'd be great if you and whomever else is relevant could go ahead and think about whether any of these fields should be excluded from search before I work on including all of them.

**Comment by catlu** [comment]
@hackmastera I think extent can be excluded for now--can't really think of a good use case for searching dimensions or size. Checked in about box/folder stuff, and there's some labels in those fields that could be searchable, so let's include physical container with the rest.

**Comment by hackmastera** [comment]
@catlu what about date?

**Comment by catlu** [comment]
Yeah, I think that can be excluded too, feel like faceting would suffice.

**Comment by hackmastera** [comment]
check rights holder; @clu reports it wasn't working (thanks for testing!)

**Comment by jrochkind** [comment]
make a separate issue to make admin_note _not_ searched unless one is logged in user? What do you think @hackmastera ? Should be possible.

**Comment by jrochkind** [comment]
I have some basic idea of how it would be done, in the "search builder" class, I think, which does have access to the controller 'context' including logged in user.
