### ISSUE TITLE
Rights facet should display as text, not uri

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#353]

**Comment by hackmastera** [comment]
doesn't look hard; we can pass a helper_method to add_facet_field:

https://github.com/projectblacklight/blacklight/wiki/Configuration---Facet-Fields

**Comment by hackmastera** [comment]
Alternately, transform at time of indexing (and reindex)

**Comment by hackmastera** [comment]
This is blocked pending confirmation from @clu and @MDiMeo that the desired outcome is translation from URIs to Strings as configured in this conf file: https://github.com/chemheritage/chf-sufia/blob/master/config/authorities/licenses.yml

If some other result is desired, please specify!

**Comment by catlu** [comment]
Yep, I vote for the full text. I don't think the abbreviations will be helpful for facet users.

**Comment by MDiMeo** [comment]
@hackmastera Yes, you've got it! I agree with you and @catlu.

**Comment by MDiMeo** [comment]
That said, I realize the full text will be long and may look clunky in a facet. No promises that I won't change my mind upon seeing it, but I would like to try full text and see.
