### ISSUE TITLE
Unable to close out of facet

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#359]
When i click on "more" for any facet and open the pop up, then click on a facet link, and then click back on the browser, i'm then unable to exit the popup, not by x-ing out or clicking outside of it. I have to reload the page.

**Comment by catlu** [comment]
@jrochkind said in Slack: that sounds like a turbolinks interaction bug. Personally, I tend to just remove turbolinks in my apps.

**Comment by jrochkind** [comment]
So yeah, way for a developer to troubleshoot/diagnose: Reproduce bug. Remove turbolinks, see if bug stops reproducing. 

http://blog.steveklabnik.com/posts/2013-06-25-removing-turbolinks-from-rails-4

Then, if that gets rid of the bug, confirming it's a turbolinks interaction bug, we can decide if we can just dispense with turbolinks in chf-sufia, or need to fix the bug.

**Comment by jrochkind** [comment]
Reproduced bug in dev. 

Removed turbolinks.  Bug is gone with turbolinks removal -- when you press the 'back' button, the 'more' popup is not displayed as open at all.  I don't know if this is really better, but I think it is the non-buggy "intended" behavior, the feature was not designed taking account of turbolinks, that it is still open on back button is a consequence of turbolinks, and that it's not closeable is a consequence of working buggy with turbolinks. 

@hackmastera okay with removing turbolinks entirely? 

Turbolinks is Javascript code that effects your whole app, such that clicks don't always really use a new page, but use AJAX to load in just part of the page. Theoretically it provides some perceived browser performance increase, but the actual improvements are questionable, and it does frequently break JS that hasn't been written accounting for it. It's not uncommon to simply turn it off.

**Comment by hackmastera** [comment]
@jrochkind Yes that plan sounds good! Thanks!
