### ISSUE TITLE
Change 'maker' to 'creator'

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#363]
basically a full-on find / replace

**Comment by jrochkind** [comment]
There's already a "creator" property. 

~~~
property :creator, predicate: ::RDF::Vocab::DC.creator do |index|
      index.as :stored_searchable
    end
~~~

This remains unchanged, it's really just about the label on the collection of the multiple current 'maker' properties?

**Comment by hackmastera** [comment]
Yes, UI / display labels only. It will be confusing for us but I'm not sure there's really a way around it.
