### ISSUE TITLE
'Medium' facet should only show for logged-in users

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#364]
but keep it as a facet so we can link to any given set

**Comment by catlu** [comment]
Is there a way to make it available for staff? Or generate a list every few months or so? Realizing using facets is the easiest way for me to clean up data, as I'm going through the terms right now.

**Comment by hackmastera** [comment]
Make it show up for logged-in users only.

**Comment by hackmastera** [comment]
Also make sure we keep it as a link from a record view page.
