### ISSUE TITLE
Public/private fields

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#367]
These fields don't need to be available to public:

- [x] Identifier
- [x] File creator
- [x] Admin note

**Comment by hackmastera** [comment]
If we want box / folder to be non-viewable, but the rest of the physical container fields to be yes-viewable, then we need to break that physical container field out into its constituent parts. That means adding 5 new (single-value) fields and migrating the data.

**Comment by jrochkind** [comment]
@hackmastera why is this "data update required", what are you thinking?

I'm thinking we just fix the front-end to not show these. 

Oh, wait, they're currently in the _index_ too, and we need to take them out?  Shouldn't be able to search by them -- even staff users don't need to be able to search by them? (We can prob have differentiated search for staff users if we want). 

Actually, even that I'm not seeing a data update required for. What are your thoughts on approach?

**Comment by jrochkind** [comment]
oh wait, it's your comment above about "we need to break that physical container field out into its constituent parts. That means adding 5 new (single-value) fields and migrating the data."

Okay! That's beyond my understanding for now without some examples.

**Comment by hackmastera** [comment]
We're going to leave box/folder viewable for now because it's a bigger job, lower priority.
