### ISSUE TITLE
Add edit access for Beckman records

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#370]
Give edit permissions to @catlu for existing Beckman records in Hydra. @archivistsarah will do it going forward for new uploads.

**Comment by hackmastera** [comment]
@clu any reason this should be limited to beckman? I'm thinking it's simpler to go through all works and add you as an edit_user if you're not already there.

**Comment by catlu** [comment]
No reason! Only put Beckman as I've not been part of that workflow at all, but I'm sure there's a few stragglers in there somewhere, so going through all works makes sense.

**Comment by jrochkind** [comment]
All works meaning every work in there?

**Comment by catlu** [comment]
Yep, I think so.

**Comment by jrochkind** [comment]
@hackmastera can you give me any hints as to what this looks like in the sufia/hydra/fedora data structures, or what methods on an AF object are relevant, how I do this?

**Comment by hackmastera** [comment]
@jrochkind I think it would be like 

```
GenericWork.find_all.each do |w|
  unless w.edit_users.include? "clu@chemheritage.org"
    # You can double-check but I'm pretty sure `<<` doesn't work directly on the property; I think a recent patch to ActiveFedora adds it.
    tmp = w.edit_users << 'clu@chemheritage.org'
    w.edit_users = tmp
    w.save
  end
end
```

**Comment by jrochkind** [comment]
Medium-er term, would it make sense for us to establish a group of 'admin' users that just have edit access to all documents? I think that can be done?

**Comment by hackmastera** [comment]
Yes; definitely the plan!

**Comment by jrochkind** [comment]
task has been run
