### ISSUE TITLE
Display additional titles with main title in browse view

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#377]

**Comment by hackmastera** [comment]
@catlu by 'browse view' do you mean the work detail / show page?

**Comment by catlu** [comment]
@anna yeah, basically the view of a record that's non-edit.

**Comment by hackmastera** [comment]
oh yeah it does call it 'browse view' on the edit screen.

**Comment by jrochkind** [comment]
Additional title already shows up on show/browse view. 

![screen shot 2017-03-20 at 9 42 14 am](https://cloud.githubusercontent.com/assets/149304/24102197/8ba84738-0d51-11e7-99a0-78c2d2936d5c.png)

Are you saying you want it in a different part of the page or formatted differently?

**Comment by catlu** [comment]
yeah, more of a display thing. before we changed the model, additional titles would show up before the 'relationships' section. they looked like:

**Title 1 | Title 2**

Relationships

**Comment by hackmastera** [comment]
So I don't think anyone liked the bar format; this probably needs some additional specification. What should it look like?
