### ISSUE TITLE
Rights should be indexed as the string, not the URI

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#383]
Otherwise people can only search it by knowing the full URI.
refs #351 

This will also obviate pr #369; so that should be reverted.

**Comment by jrochkind** [comment]
I'd actually leave the URI in the facet, translated to label on display, but index the string separately. This will prevent need for a reindex if a label changes (but not a URI), and strikes me as best practice. So I would not revert #369. 

But not a big deal either way if you'd rather.

**Comment by hackmastera** [comment]
Sounds good!

**Comment by jrochkind** [comment]
Blocked waiting for discussion of rights facet values

**Comment by jrochkind** [comment]
Doesn't need to be blocked really, I'll just make em indexable. Leave the URIs in the index, but index the things too. Oh, but really should be done on top of #457 to avoid conflicts, so I'll do that.

**Comment by hackmastera** [comment]
reopen until reindex happens

**Comment by jrochkind** [comment]
Reindex completed, tested, you can search for rights statement labels, and get proper results.
