### ISSUE TITLE
Strip blank spaces before or after a heading

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#385]
@catlu had found that there were headings (subject and possibly others) which have been mismatched in Solr due to spaces at the start of end of a phrase ex: " Beckman" "Beckman" and "Beckman ". 

Would it be possible to have the form automatically strip leading or trailing spaces in a string? It doesn't seem like those would ever been meaningful enough to hold onto.

@hackmastera @jrochkind Do you have any thoughts on the difficulty of adding this?

**Comment by jrochkind** [comment]
should not be difficult.

**Comment by jrochkind** [comment]
Can you give me a list of which fields need spaces stripped? Or basically all of them that are string/text type?

**Comment by sanfordd** [comment]
I think this is something to loop @catlu in on as she's been cleaning the metadata and can better guess if there's ones we may or may not want to do the cleanup on. My instinct would be all of them.

**Comment by catlu** [comment]
@daniel i think the dropdowns can be avoided, but seems like all of the fields could benefit from this

**Comment by jrochkind** [comment]
not nearly as 'not difficult' as I thought, cause hydra. but it's doable, doing it.

**Comment by hackmastera** [comment]
@sanfordd @catlu I just realized -- @jrochkind is I believe implementing this at form submission time. Is that what you intended or are you asking about data that's already in hydra?

**Comment by jrochkind** [comment]
i'm doing both, form submission time, and also a data cleanup task to get existing stuff.

**Comment by hackmastera** [comment]
reopen until we run the task

**Comment by jrochkind** [comment]
task has been run
