### ISSUE TITLE
New Maker dropdown label: After

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#393]
For fine art cataloging where work is a copy of a known artist by an unknown one. The term is from Getty and ARLIS cataloging standards, but there's no predicate that corresponds, so mint our own?

**Comment by jrochkind** [comment]
@hackmastera want to work on this together, so I can learn how to properly use/mint a newly minted URI?

**Comment by hackmastera** [comment]
Because of the rebranding (and because we haven't published any of the RDF) all our URIs are somewhat temporary. We've been using `http://www.chemheritage.org/ns/[whatever_term]`.
