### ISSUE TITLE
Add non-required, multi-valued 'medium' field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#42]
dcterms:medium, http://purl.org/dc/terms/medium
AAT vocabulary control

**Comment by hackmastera** [comment]
needs a new predicate with range: literal

**Comment by catlu** [comment]
Ebucore:medium seems to have no range, but I'm reluctant to use that since ebucore is more a/v and broadcasting based (also a possibility PCDM will use it for technical metadata). There's a VRA option (https://s3.amazonaws.com/VRA/ontology.html#material), but that has a range that's a class (similar to dcterms). Thinking we mint our own for this one until a better URI for reuse comes up?
