### ISSUE TITLE
Have solrconfig and schema copied over to a second machine

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#421]
If we want to break the Solr requirements off to another machine we'll need to be able to copy/link/share the fles
`/opt/sufia-project/current/solr/config/schema.xml`
`/opt/sufia-project/current/solr/config/solrconfig.xml`
From the front end machine to a solr box automatically when we deploy.

**Comment by hackmastera** [comment]
The question is whether this can be done via capistrano. Or do we need to put an ansible script in the repo that capistrano can trigger? Or some other solution?

**Comment by jrochkind** [comment]
It can def be done via capistrano. There might be other ways to do it and cap might not be the best way, but you can do it via cap -- doing it via cap would prob get a whole copy of the repo on the solr machine, even though only the ./solr dir is actually used, but that does not seem disastrous to me. 

The benefit of doing it via cap, is that sometimes there might be changes to solr config that go along with changes to Rails app, and both need to be deployed simultaneously, doing it via cap means they both always will be (including rollbacks etc, including staging, whatever). 

If there are chagnes deployed to ./solr config via cap, we'll have to restart/reload solr usually. Maybe an optional flag to cap for restarting solr on deploy, or even a fancy script that notices a diff between deploys in `./solr` and automatically restarts/reloads solr.

**Comment by hackmastera** [comment]
We've decided to run solr on web machines for now; closing this unless / until there is a clear reason to break it out.

**Comment by hackmastera** [comment]
Reopening per discussions 5/30. We'll need to deploy the codebase but not run bundler, etc. Ideally a solr machine will not have ruby on it.
