### ISSUE TITLE
Put filesets and child works in alpha sort order

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#423]
For this record: https://hydra.chemheritage.org/concern/generic_works/ft848q626

File manager interface doesn't work because the child works have had titles added, so the filenames are no longer part of the titles, but they're still in their own file sets. Child works then clumped to the bottom after editing the parent record due to a bug (fixed in Sufia 7.3).

Low priority for me, and fixing after we're on Sufia 7.3 works too if that makes more sense.

**Comment by hackmastera** [comment]
This is a single work that got messed up when saving a work bumped its works down below its files in the ordered_member list. Just needs to be fixed as a one-off.

**Comment by hackmastera** [comment]
```
> w = GenericWork.find 'ft848q626'
> new_order = w.ordered_members.to_a
> w.ordered_members.to_a.each { |member| member.delete }
irb(main):039:0> w.thumbnail_id = nil
=> nil
irb(main):040:0> w.representative_id = nil
=> nil
irb(main):041:0> w.save
=> true
irb(main):042:0> new_order.each do |member|
irb(main):043:1*   w.ordered_members << member
irb(main):044:1>   w.save
irb(main):045:1> end
```
