### ISSUE TITLE
Admin notes should not be searchable to guest users

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#425]
Only logged in users should be able to search this field.

I'm not sure how to accomplish this; this is initially an issue to discuss feasibility.

**Comment by jrochkind** [comment]
I have some basic idea of how it would be done, in the "search builder" class, I think, which does have access to the controller 'context' including logged in user.

**Comment by hackmastera** [comment]
ah, okay yes that makes sense.
