### ISSUE TITLE
Ldp::BadRequest (RDF was not parsable: [line: 22, col: 1 ] Broken token (newline): ;)

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#427]
Record cannot be saved

https://gist.github.com/hackmastera/1f92d26e908ef404733ef8467a3beb40

**Comment by hackmastera** [comment]
record ID: 1j92g785h

User removed description and saved successfully. Added description back and saved, again successful.

**Comment by catlu** [comment]
Just happened again with record ID: m039k545g

But managed to save successfully after going back and redoing the steps above.

**Comment by hackmastera** [comment]
Not sure how to replicate and haven't seen it since. We'll close and reopen if we see it again.
