### ISSUE TITLE
Add non-required, multi-valued, free text 'extent' field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#43]
dcterms:extent, http://purl.org/dc/terms/extent

**Comment by hackmastera** [comment]
needs a new predicate with range:literal

**Comment by catlu** [comment]
For this, I think we could either go with chf:extent and do owl:sameAs dcterms for later, or split up extent, size, and duration into three separate fields/predicates (bf: extent; bf:dimensions; ebucore/bf:duration) with properties that are more specific. Thoughts?

**Comment by hackmastera** [comment]
I think we talked about this and couldn't really come up with a use case for separating into three fields. correct me if i'm wrong!

**Comment by catlu** [comment]
The only benefit I can think of for splitting them out would be to control the input, and repurposing measurement data right now seems pretty unrealistic. With all the variability, keeping this as one free-text extent field would make things much easier.
