### ISSUE TITLE
Homepage category: Health & Medicine

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#434]
Aggregate using metadata from:

-  Keyword (not exact, but part of longer headings)
o   In title or subject field – Health: 7
o   In title or subject field – Medicine: ~30
o   In title or subject field – Medical: ~60

-  Subject
o   Toxicology: 2
o   Gases, Asphyxiating and poisonous--Toxicology: 13
o   Biology: 2
o   Biochemistry: 4
o   Hearing aids: 1

**Comment by catlu** [comment]
*Not sure if using a keyword search like that is possible. If not, let me know and I'll see if I can find more appropriate subjects to pull from.

**Comment by jrochkind** [comment]
So, a keyword search _might_ be possible, but I'm not sure if it's going to really work right. 

It would be better if we could find exact facet values to use -- I can look for all existing ones including the words 'Health', 'Medicine', 'Medical' if you like. 

Or I can see if I can figure out a way to do this by keyword. Not sure if I can really. I guess this wouldn't be relevance ranked at all, a thing is either "in" or "out" of this category, and anything with those words in title or subject would be 'in'.  I think I can do that, not sure how good the results are going to be, but I can try and we can see if you want.

**Comment by catlu** [comment]
I can find more exact facets for you @jrochkind. If you want to hold off on this one for last maybe, I should be able to sort them out in a day or so.

**Comment by jrochkind** [comment]
ok, if that's fairly straightforward, that'll be best. I can give you a list of all currently indexed subjects with words 'health', 'medical', or 'medicine' if you want. I think I can do that somehow. :)

**Comment by jrochkind** [comment]
Here they are from subjects in current production:

Bayer HealthCare LLC
Electronics in space medicine
Harvard Medical School
Infants--Health and hygiene
Medical botanists
Medical education
Medical electronics
Medical electronics--Equipment and supplies
Medical instruments and apparatus
Medical laboratories--Equipment and supplies
Medical laboratories--Equipment and supplies--Standards
Medical laboratory equipment industry
Medical physics
Medical sciences
Medical students
Medical technologists
Medical technology--Vocational guidance
Medicine
Medicine bottles
Medicine bottles, Victorian
Newborn infants--Medical care
Public health
Space medicine
USAF School of Aerospace Medicine
United States. Army. Medical Corps
United States. Public Health Service. Office of the Surgeon General
Women in medicine
World Health Organization

**Comment by catlu** [comment]
Thanks for the list @jrochkind! Let's add these additional subjects in place of the keyword stuff:

Drugs
Electronics in space medicine
Infants--Health and hygiene
Medical botanists
Medical education
Medical electronics
Medical electronics--Equipment and supplies
Medical instruments and apparatus
Medical laboratories--Equipment and supplies
Medical laboratories--Equipment and supplies--Standards
Medical laboratory equipment industry
Medical physics
Medical sciences
Medical students
Medical technologists
Medicine
Medicine bottles
Newborn infants--Medical care
Public health
Space medicine
Women in medicine
