### ISSUE TITLE
Homepage category: Instruments & Innovation

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#437]
Aggregate using metadata from:

-  Genre
o   Scientific apparatus and instruments: 29

-  Subject
o   Artillery: 77
o   Machinery: 313
o   Chemical apparatus: 40
o   Laboratories--Equipment and supplies: 41
o   Chemical laboratories--Equipment and supplies: 4
o   Glassware: 22

**Comment by jrochkind** [comment]
Does this mean it has to be in that _genre_ _and_ simultaneously be in one of those subjects? Or either is good enough, if it has one of those subjects but no genres at all or other genres, it's still included?

**Comment by catlu** [comment]
@jrochkind should be that genre OR those subjects. The goal here was to include works at are instruments but filter out the large amount of Beckman materials that have that same subject heading.

**Comment by catlu** [comment]
@jrochkind, I'm looking through this collection right now, but I don't see the museum instruments in here? Currently there should be 37 of them that fall under the scientific instruments genre.

**Comment by jrochkind** [comment]
@catlu can you give me an example document that you believe should be showing up in the "Instruments & Innovation" category, but is not?

**Comment by catlu** [comment]
Yep, the stuff from this search: https://hydra.chemheritage.org/catalog?_=1493746057393&f%5Bgenre_string_sim%5D%5B%5D=Scientific+apparatus+and+instruments&q=&search_field=all_fields
