### ISSUE TITLE
Fields that aren't clickable or linked in record view

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#441]
- [x] Artist
- [x] Author
- [x] Addressee
- [x] Engraver
- [x] Interviewee
- [x] Interviewer
- [x] Manufacturer
- [x] Photographer
- [x] Printer of plates
- [x] Publisher
- [x] Place (all four fields)
- [x] Genre
- [x] Medium
- [x] Division

**Comment by hackmastera** [comment]
@jrochkind Judging from your comment maybe this auto-closed prematurely?

**Comment by jrochkind** [comment]
I think it's all good with the PR that got merged!
