### ISSUE TITLE
missing 'in generic work' listing

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#444]
https://hydra.chemheritage.org/concern/generic_works/vt150j62m

Original problem: After adding the child works, all the children were viewable from the parent show page, but one of the children did not show its parent from the its show page.

After troubleshooting in the UI: All the show pages looked right, but the metadata form does not show the relationships at all.

Need replication criteria

**Comment by catlu** [comment]
Marking this one higher priority because it seems like it is related to and affects the attaching and removing of child works.

**Comment by hackmastera** [comment]
This was a work with inconsistent member lists; it's now been repaired.

**Comment by jrochkind** [comment]
Is there a validation we could/should add to prevent inconsistent member lists from being saved?

**Comment by hackmastera** [comment]
Theoretically you're supposed to be allowed to have membeers that aren't ordered members. In practice I  don't think we have that use case. So we could ensure that `members` and `ordered_members` (or `member_ids` and `ordered_member_ids`) contain the same elements.
