### ISSUE TITLE
search bar dropdown should not say "all of sufia"

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#447]
"All digital collections"?

**Comment by jrochkind** [comment]
Should it be there at all? There's only one choice in the dropdown -- I'm not sure what the other potential choices would be, what this select bar would be for. Do we want this select bar at all?

**Comment by hackmastera** [comment]
Good point; there are more options when you're logged in.

Separate issue to remove drop-down for non-logged-in users?

**Comment by jrochkind** [comment]
Ah, I see! I'd be fine with leaving that til after soft launch, I'm still anticipating a major overhaul of end-user-facing UI after soft launch.

**Comment by jrochkind** [comment]
It could just say "All", no noun required.  :)

**Comment by hackmastera** [comment]
I like that; fewer words. I'll go ahead and do that and if @MDiMeo wants something else we can change it later.
