### ISSUE TITLE
Flip collections relationship (by upgrading to cc2 or migrating to hyrax)

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#453]
required for #349

**Comment by hackmastera** [comment]
As mentioned on slack, Sufia 7.3 does not run on cc2.

We have 2 options: upgrade now to hyrax or release a version of Sufia that does run on cc. I forayed very briefly into each option and I don't think either will be particularly less time-consuming than the other.

Upgrade to hyrax requires rails 5; that's pretty much where I stopped.

Releasing Sufia requires some code changes in Sufia to account for the flipped collections relationship. I made one such change and started testing the app a little; another one popped up and that's where I stopped.

We  need to decide if this feature is worth the time it will take to pursue one of these paths and, if so, which path we want to take. I'm setting this aside for now to avoid spending too much time on it in the meanwhile.

**Comment by jrochkind** [comment]
@hackmastera Ah, so sufia can't be upgraded to CC2 without changes, it will require changes to sufia code beyond just updating the dependency? 

Ack, all of these options are terrible. 

Another option is I can continue figuring out how to do the collection facet under current sufia/CC. I started down that path, trying to figure out how to use callbacks to get solr index for works updated when a work is added/removed from a collection. After spending basically a whole day on it and not making much headway, I left it. The hydra code is convoluted. 

I think it's possible we'll just have to give up on a collection facet for soft launch, the hydra stack does not make it feasible -- until we update to hyrax.

**Comment by hackmastera** [comment]
wontfix for now
