### ISSUE TITLE
subject headings autocomplete not working in first field

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#459]
Autocomplete isn't working in the first box available for subject headings in the edit form (single and multi-file works, ingested pre- and post-migration). It does work in all subsequent, added boxes though. The first box never works -- adding more doesn't enable autocomplete on the first one.

**Comment by catlu** [comment]
Low to medium for me--minor annoyance to catalogers but a few of them know about it already. I can give more people a heads up and it's pretty easy to workaround for now.

**Comment by MDiMeo** [comment]
Anna is going to look into this for an hour and if it's not a quick fix she'll backlog it.

**Comment by hackmastera** [comment]
I haven't gotten to this yet but I noticed it's working now. Maybe due to some javascript reconfiguration @jrochkind did for another ticket. @archivistsarah I'm closing this but please reopen if it's still not working for you.

**Comment by archivistsarah** [comment]
not reopening, just documenting that there's still flakiness & inconsistency with the autocomplete as of 4/26/2017. autocomplete not working for a few minutes then starting suddenly working again.

**Comment by hackmastera** [comment]
thanks @archivistsarah 

probably refs #396
