### ISSUE TITLE
Permissions aren't shared when users are added during creation of new work

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#462]

**Comment by catlu** [comment]
Medium priority, but can work around this.

**Comment by catlu** [comment]
Tried it more on staging, and looks like they also aren't shared when doing a batch create.

**Comment by hackmastera** [comment]
I've done a ton of debugging and haven't figured out why yet. Going to keep looking.

In the meantime I've confirmed this is an upstream bug (exists in a clean sufia 7.3 installation)

**Comment by hackmastera** [comment]
breaking news! Fixed in CC some time ago, backported to the 1.7 branch but not actually released.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hydra-tech/scvfgmwVqdo/g-Z9ZsZWEwAJ
