### ISSUE TITLE
Batch editing: works were put under a lease when they should've been public visibility

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#463]
Was batch adding user permissions to a group of works, the users were added but then the works were put under a lease when they should've been public visibility.

**Comment by catlu** [comment]
Tested this on staging with different kinds of batch edits. Doesn't look like it affects Description tab edits, but will turn any Share tab edits into Lease visibility (even if it's marked Open Access or CHF for the current period of time).

**Comment by hackmastera** [comment]
huh. I'm trying it and getting embargo visibility. you got lease? @catlu

**Comment by catlu** [comment]
yeah, mine said the work was under lease. attaching a screenshot:

![capture](https://cloud.githubusercontent.com/assets/11876037/25009458/ba94c274-2034-11e7-8908-b5bb2b5089bf.PNG)
