### ISSUE TITLE
Fix and expand integration tests

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#466]
We'll want to do this before we upgrade to hyrax, but maybe after getting on Rails 5; @jrochkind notes that "theoretically, Rails5 officially supports capybara integration tests now.... I'm skeptical how well it will work, but if we wait til rails5 for integration test bonanza, i'd probably want to try the official rails architecture at least."

in the meantime let's at least keep track of integration tests we want to write but haven't gotten to:
- [x] searchbuilder functionality in `config/initializers/sufia_catalog_search_builder_overrides.rb`
- [x] collection pages
- [x] synthetic categories page
- [x] end-to-end metadata form tests? especially permissions and visibility. Look into whether this is the right way to test this stuff, or we just need to expand unit tests we already have.
- [x] A basic happy path search. Enter a query, get results, click on a result. As both logged in and not logged in user.

**Comment by hackmastera** [comment]
refs #706

**Comment by MDiMeo** [comment]
When doing this, consider the manual workflows written for the QA process:

End User: https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/129892353/QA+Workflow+-+EndUser

Admin Tasks: https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/129925129/QA+Workflow+-+Admin+Tasks

**Comment by jrochkind** [comment]
If we end up needing fits on travis, see: https://github.com/ucsblibrary/alexandria/blob/master/.travis.yml#L24-L27

**Comment by jrochkind** [comment]
We're not going to have everything in manual QA workflows for now, but enough to make me a lot more confident in CI verifying our app still works for basic use cases, especially end-user use cases.

**Comment by jrochkind** [comment]
merged to rebrand branch
