### ISSUE TITLE
display of 'decade' date qualifier

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#47]
Hey @catlu 
we had discussed having a date with a 'decade' qualifier display as, e.g., 1920s. However, I realize now that if someone wants to use the first decade of a century it will display as, e.g., 1900s, which means something entirely different. Ideas?

**Comment by catlu** [comment]
Would displaying it like 1900s (decade) work?

**Comment by hackmastera** [comment]
Sure -- sounds good!
