### ISSUE TITLE
rights value cannot be unset

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#477]
If I go to admin UI, and try to set 'rights' to blank on an existing Work, my choice is seemingly ignored when I press 'save', the old value is still there.

**Comment by jrochkind** [comment]
reproduced in dev. 

I assume this is indeed desirable, people _should_ be able to unset rights, set it back to blank? @catlu

**Comment by catlu** [comment]
@jrochkind Yeah I'd say so, because having a non-blank value suggests rights research is done.

**Comment by jrochkind** [comment]
debugging is leading me to think it's a StrongParams issue, which could be effecting other attributes as well. Having trouble figuring out what/where is supposed to be authorizing through StrongParams.

**Comment by jrochkind** [comment]
oops nope not strongparams. fix coming soon.
