### ISSUE TITLE
New predicates needed for date_of_work and date_of_publication

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#49]
Since these needed to be implemented as nested attributes, we can't used dcterms:issued an dcterms:date, which both have range rdfs:literal. We need predicates that accept EDM:TimeSpan.

**Comment by hackmastera** [comment]
Hold off on these; I think they will need to be in the other direction. I will let you know asap.

**Comment by hackmastera** [comment]
Okay I have it working now and the predicates we need will live on the date_of_work and date_of_publication objects. I think I mentioned yesterday this is not the way we'd like the linked data to work, so I'm fine with just keeping the temporary predicates that I stuck in there:
http://chemheritage.org/ns/work_date_of
http://chemheritage.org/ns/publication_date_of
Let me know what you want to do!

**Comment by catlu** [comment]
Let's keep 'em for now!
