### ISSUE TITLE
production machine can't send email

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#491]
@daniel, our production machine isn't set up to send email, which makes sense, since it's on AWS and never was set up. 

Obviously, "I forgot my password, send me an email" links don't work. 

How hard do you think it'd be to get it to send email? Does CHF has an SMTP server that they might allow the app to use, and get through the firewall to access? That'd do it. 

Sending password reset emails isn't neccesarily the most important thing in the world, so if it's gonna be a pain, maybe not. But figured it was worth asking. I'm not sure if there are any other things that are trying to send email.  One could imagine there being such in the future. 

There are also some cloud SMTP services that give you free for small volumes, we could potentially use.

**Comment by jrochkind** [comment]
Oops, nevermind, I did get the 'reset password' email after all! I guess it can send email?

**Comment by sanfordd** [comment]
Not sure why it was so slow, if you used the chf email did Sendio catch it?

**Comment by sanfordd** [comment]
Looks like it was just slow. Problem solved.
