### ISSUE TITLE
Formal solr relevance tuning process

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#494]
One way of doing this would be to create a spreadsheet for evaluators to use. The sheet would have a page for each of a small number of high-value searches and their top-10 results before proposed tuning, and another sheet of same after proposed tuning. We would then get a handful of people to go through each row on each sheet, giving each result a score from 1 (highly relevant) to 5 (not relevant).

**Comment by MDiMeo** [comment]
A stripped down version of this will be addressed as part of usability testing.
