### ISSUE TITLE
Ensure we can retrieve file from S3 with expected checksum

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#495]
Need to skip back over an unknown number of versions to find the one with the right checksum.

refs: #276

**Comment by hackmastera** [comment]
Can this be automated?

**Comment by jrochkind** [comment]
@sanfordd What do you need as 'input' for this process. A location on disk, and a checksum?

**Comment by jrochkind** [comment]
Esme says:

"you can get the SHA1 for a binary either by retrieving its description (fcr:metadata) or it will also be included in the headers of a HEAD or GET response to the binary itself (`ETag: "urn:sha1:XXXX"`)"

And it's the SHA1 that should be used for on-disk location. AND for fixity checks. Unless fedora has been customized. 

WE're not sure why sufia admin is showing md5, the thing sufia admin shows appears to have nothing to do with fedora's fixity functions. :(

**Comment by jrochkind** [comment]
So it turns out the checksum shown in Fedora UI comes from "FITS", and is calculated _pre-ingest_ into fedora, and has nothing to do with fedora at all. :(

https://github.com/projecthydra-labs/hyrax/issues/867

But okay, I'll work on feeding you the on-disk file location, and the actual expected SHA1 checksum (which is what fedora cares about) as input to "try to find a good backup to restore". Make sense @sanfordd ?

**Comment by jrochkind** [comment]
argh typo, meant " it turns out the checksum shown in SUFIA UI comes from "FITS", and is calculated pre-ingest", adding another comment so it will show up in the feeds if you're reading that way. :) @sanfordd 

(I keep typo'ing all these names when writing, sorry!)

**Comment by sanfordd** [comment]
@jrochkind As long as I can get the sha1 sum of the object in Fedora we can use that to replace the corrupted blob. @hackmastera found while the etag is not the sha1 sum, either the fixityservice or the version metadata have the correct sha1sum. 

From there we can just grab one of the backup copies in S3, checksum it to see if it matches and keep going back versions until it does and put the uncorrupted file back in place.

**Comment by jrochkind** [comment]
https://github.com/psu-stewardship/scholarsphere/wiki/Replacing-content-in-a-version

**Comment by hackmastera** [comment]
code for importing versions onto a fileset in sufia 7: https://github.com/projecthydra/sufia/blob/7.2-migration/lib/sufia/import/version_builder.rb

**Comment by jrochkind** [comment]
Pretty much no guidance from fedora-tech. 

https://groups.google.com/forum/#!topic/fedora-tech/2BxkvDwsXqc

I think we should prob ensure we can actually retrieve a known-good backup, but perhaps it's okay to  just ignore figuring out how to actually insert it into fedora until the very very unlikely case when it happens.

**Comment by hackmastera** [comment]
What is the perfect world scenario? To me, there would be something in the fedora API that allows you to replace the file for a specific version. Perhaps we should mention this in the context of the fedora API discussion.

**Comment by hackmastera** [comment]
I think in yesterday's meeting we agreed that once @sanfordd has confirmed that he can retrieve a known-good copy from S3 (and documented that process!) we can close this issue. Adding a link to this on the systems basecamp.
