### ISSUE TITLE
Authority control, Autocomplete, and Form validation

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#5]
Which fields need authority control, and from which sources?
Which fields need autocomplete and from which sources? (the answers may always be the same as above but may not in all cases)
Which controlled fields must require an entry from an authority source, and which may also allow other values?

**Comment by hackmastera** [comment]
(Initial exploration)[https://github.com/chemheritage/chf-sufia/wiki/Exploration:-autocompleting,-using,-and-validating-external-and-locally-stored-authorities,-thesauri] completed, current sufia functionality. Next looking at https://github.com/projecthydra-labs/questioning_authority, which the community supports integrating into sufia as a replacement.

**Comment by hackmastera** [comment]
@MDiMeo @catlu I just deployed an initial implementation of FAST autocomplete on the sandbox. It uses the web service and it seems responsive enough. Click 'edit' on a file you have added and go down to the "subject" field to try it out.

A topic for discussion:
* There are a lot of subject terms. The autocomplete is not going to be a sufficient replacement for actually searching a thesaurus if you don't know exactly what you're looking for. So we may want to have a link to the FAST search page, as well.

And a bunch of notes:
* This uses the 'suggestall' index; Cat and I have talked about where to use other ones and I may need to rearchitect a little to make that work.
* Cat and I also talked about fields where we may want to drew from multiple FAST indexes, but not the whole set. That will probably require using a different autocomplete javascript library so I will look at dropping that in.
* It only works on the first box (i.e. if you add another subject field that field won't have the autocomplete).
* There is a bug when your search term includes parenthesis that I can't exactly figure out. e.g. entering "word (ling" on the [demo page](http://experimental.worldcat.org/fast/assignfast/) gives you a result but we're currently not getting anything for that.
* all of this work could be contributed back to the hydra community (which would welcome it I'm sure) with a little extra effort.

**Comment by catlu** [comment]
Sweet, I tried it with a few subject terms and name authorities and they all worked pretty well for me. Here's a possible bug? I was trying to clock the response time and had typed "alchemy," but it doesn't locate the subject, whether I enter the word fast or slow. Instead, it only retrieves "Alchemy--Religious aspects--Christianity." From that, I'm noticing the suggested results in the autocomplete are all SEE INSTEAD/USE FOR terms. Terms without those don't seem to be coming up. I wonder if that's related to your parenthesis bug as well.

**Comment by hackmastera** [comment]
Hey @catlu yes you're right the bugs were related; I just pushed a fix. Thanks!

**Comment by catlu** [comment]
In some back and forth with the museum folks, they gave some examples where joint ventures/branches/subsidiaries feature often in the name authorities they would need. Especially companies with international or overseas manufacturing sites. There are a few ways to go about this, but so far it looks like VIAF offers a much greater selection for them. So right now leaning toward VIAF over FAST for name authority source.

**Comment by hackmastera** [comment]
- [] #62
- [] #63
- [] #64 
- [] #65

**Comment by catlu** [comment]
The FAST headings are all working great with the 'place' fields. For the 'subject' field, when I try to edit a record that has been updated and saved previously, the autocomplete doesn't seem to come up again when I want to add an entry.

**Comment by hackmastera** [comment]
Related: https://github.com/chemheritage/chf-sufia/issues/81

**Comment by hackmastera** [comment]
this ticket is too big.
