### ISSUE TITLE
expose role management UI

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#500]
so that admins (and only admins) can add / remove other admins.

there is UI for this already; not built-in to the 'admin dashboard' such as it is; see it at `/roles`

**Comment by hackmastera** [comment]
of course, the existing UI doesn't work.

**Comment by jrochkind** [comment]
I wonder if we really need exposed role management UI for now. It might be fine to add/remove admins with a rake task, there will only be a few of them, and they don't change much. 

This is a strategy my last employer often took with our client projects: Start with something that is modified by rake task, add UI for it later if it becomes needed or wanted as a priority.

**Comment by hackmastera** [comment]
Yeah I definitely intend to argue that we de-prioritize this issue.

**Comment by jrochkind** [comment]
I guess a rake task to list all current admins would prob be a good idea (and pretty easy), if command-line rake is to be the only interface, which I agree would be fine for now.

**Comment by hackmastera** [comment]
sure i can go ahead and add a list task to the open PR.
