### ISSUE TITLE
Loss of permissions after editing

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#508]
Need to be replicated. Here is are the steps user performed:
- User A uploads and shares Work with User B.
- User B:
  - Open 'my shared works' in tab 1
  - right-click on 'edit' action to open Work edit screen in tab 2
  - In tab 2, click 'browse view' to look at the image of the item.
  - In tab 2, click browser back button to return to edit screen
  - edit metadata, save.
  - In tab 1, reload 'my shared works'. Work is no longer in the list.

**Comment by catlu** [comment]
Tried this on staging as two different users, can't recreate.

**Comment by hackmastera** [comment]
User tends to work with *lots* of hydra tabs open.

This bug is probably related to bad architecture in background jobs.

Still can't replicate.
