### ISSUE TITLE
Add download tracking to analytics

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#526]
GA out of the box really just tracks page views (and related data).

To track downloads, we have to do either:
- Click tracking: Add some javascript to our download button to send an event to google analytics. There's a google js library, [analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/events); it'm not sure yet whether this is required or optional.
- or Direct download tracking: Add `tracker` call into the download controller. Will require granting GA write permission to our google project credentials. Also requires a new gem, https://github.com/tpitale/staccato (companion to the one in use by Sufia for GA reporting integration, https://github.com/tpitale/legato)

Note, we should use events so as not to inflate pageviews.

**Comment by hackmastera** [comment]
Found some javascript that tracks events in sufia. The id it depended on no longer existed.

**Comment by hackmastera** [comment]
https://github.com/projecthydra-labs/hyrax/issues/968

**Comment by hackmastera** [comment]
This should be backported for 1.0.0 release

**Comment by jrochkind** [comment]
All things being equal, I think I"d lean toward click-tracking, seems simpler. But if there's a reason we want to do it the other way, that's okay too.
