### ISSUE TITLE
Additional title doesn't seem to be alpha sorting

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#527]
Example: https://hydra.chemheritage.org/concern/generic_works/ft848q626

**Comment by jrochkind** [comment]
@hackmastera can you give me any hints about what code in what general area is supposed to alpha sort multiple entries?

**Comment by hackmastera** [comment]
For fields listed in the metadata table, it happens at the renderer layer. Here's the commit where I introduced it (knowing more now about reopening classes I would not have copied over this whole file but that is what I did at the time) https://github.com/chemheritage/chf-sufia/commit/6e7da7d91ec1d4060eec14113ee2bf59bfdd96c8#diff-ccbf0cdadb293f7b347b432b7b33fdb2R29

However in this case it was pulled out of the metadata table to be up below the title; there is no existing logic that I know of that should be used.
