### ISSUE TITLE
Finalize image assets

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#529]
See what we can get out of the pds files using photoshop.

Make sure we're getting double resolution for everything. Write that here.

**Comment by MDiMeo** [comment]
https://docs.google.com/spreadsheets/d/1D4HFGb0Yy4iFDiRrbw9LKN51Dld8YAXklLAbAp0ZRTM/edit?usp=sharing

**Comment by hackmastera** [comment]
All images should be cropped to the size indicated on the spreadsheet, then saved in two resolutions:
- full resolution as `base_filename_full.jpg`
- 144 dpi as `base_filename_144.jpg`

We can then do the compression recommended by google at the command line: https://developers.google.com/speed/docs/insights/OptimizeImages#optimizations-for-gif-png-and-jpeg-images

I tried the recommended command; here are my before/after images:

![molecules_that_matter](https://cloud.githubusercontent.com/assets/845363/26600830/920ed86c-454b-11e7-9f8a-3b332c9b6fdd.jpg)


![molecules_that_matter_converted](https://cloud.githubusercontent.com/assets/845363/26600839/95b20c96-454b-11e7-877b-9c779b1fd50a.jpg)

**Comment by hackmastera** [comment]
We can then do the compression recommended by google at the command line: https://developers.google.com/speed/docs/insights/OptimizeImages#optimizations-for-gif-png-and-jpeg-images

I tried the recommended command; here are my before/after images:

![molecules_that_matter](https://cloud.githubusercontent.com/assets/845363/26600830/920ed86c-454b-11e7-9f8a-3b332c9b6fdd.jpg)


![molecules_that_matter_converted](https://cloud.githubusercontent.com/assets/845363/26600839/95b20c96-454b-11e7-877b-9c779b1fd50a.jpg)

**Comment by MDiMeo** [comment]
Jay will save files to P:OthmerLibrary/DigitalCollections/CropsforHydraRedesign

**Comment by hackmastera** [comment]
Running these again from cropped tiffs to achieve 2x width / height (dpi not useful in web resolution). Here is an example command:

`convert cropped_tiffs/featured_collection_full.tif -resize 1170x966 -quality 85 -interlace JPEG -colorspace RGB web_ready/featured_collection_2x.jpg`

**Comment by hackmastera** [comment]
Here's one for doing a whole directory

`for FILE in `ls cropped_tiffs/categories/`; do convert cropped_tiffs/categories/$FILE -resize 700x700 -quality 85 -interlace JPEG -colorspace RGB web_ready/categories/${FILE%_full.tif}_2x.jpg; done`

**Comment by jrochkind** [comment]
I was pretty sure you could tell `convert` to just do a whole directory, with output filenames based on input. But whatever works!

**Comment by hackmastera** [comment]
Good to know for next time!!

**Comment by hackmastera** [comment]
These are set, aside from the ones that haven't been digitized yet so cannot be cropped / prepped.
