### ISSUE TITLE
Customize Google Analytics

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#531]
**Should be able to answer these questions:**
-How many people have visited the digital collection?
-How many items have been downloaded across the whole digital collection?
-Which items have been downloaded the most?
-Which items get the most page visits?
-How do people find our site?
-Which pages do people stay on the longest?
-On average, how many pages does a visitor view?
-Are there particular pages that are typical entry/exit pages?
-What is the average time per visit?
-What is the average time spent on each page?

**Some additional questions that are desirable:**
-Which items get shared the most on social media? 
-Which items get bookmarked the most?
-How many downloads, page views, and social media shares did this particular item get? [view of particular item, not aggregated]

**Comment by MDiMeo** [comment]
Now that #668 is open, should we close this @hackmastera?

**Comment by hackmastera** [comment]
@MDiMeo I'll close it when that PR is merged.

**Comment by hackmastera** [comment]
@MDiMeo oh, you are right; I didn't look at this closely enough and thought it was #668, and that you were referring to the PR. closing!
