### ISSUE TITLE
Rights field batch edit not working

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#532]
For this record: https://hydra.chemheritage.org/concern/generic_works/j67314089. Wanted to change from Public Domain to No Copyright-US, but record stays PD after save.

Not sure if something's wrong with this particular record or part of a larger issue.

**Comment by hackmastera** [comment]
@catlu I guess you've fixed this one? I looked at the record from the console and the rights field looks good.

**Comment by catlu** [comment]
@hackmastera I didn't--it should've saved as No Copyright US, but it still says Public Domain.

**Comment by hackmastera** [comment]
@catlu right, thanks sorry I misread.

**Comment by jrochkind** [comment]
@catlu does it work if you on an individual work edit, just not batch edit?

**Comment by jrochkind** [comment]
I can't reproduce in dev or staging. Created some works, was able to batch edit 'rights' succesfully. 

Not really sure where to go from here. Any ideas @hackmastera ?

**Comment by catlu** [comment]
Just tried it with the work linked above, and yes it works individually!

**Comment by hackmastera** [comment]
Reproduced on this same object on production, in a batch edit with just this object.

Also looked at this object in the console on production; rights field looked fine.

**Comment by catlu** [comment]
I batch edited a bunch of other records, ran into it again with another record in particular, but the rest worked. An individual edit with that one record worked fine. Not sure why, but since it's not holding up my workflow, backlog or close?

**Comment by hackmastera** [comment]
I'll close since we cannot replicate. thank you, @catlu
