### ISSUE TITLE
Passenger Restart dependant upon machine having http(s) request made

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#533]
So the passenger-config and passenger-status tools won't work until passenger has been started by something trying to access the page. This gives an error 
`*** ERROR: You are not authorized to query the status for this Phusion Passenger instance. Please try again with 'sudo'.`
which is not terribly helpful.
We'll need to add a wget or some request to the server's front page prior to when it calls the passenger-status and restart so it can properly run those when deploying. 

Until that is fixed we can temporarily manage things by going to the server ip address to start passenger and then re-running the deploy.

**Comment by hackmastera** [comment]
@sanfordd are you proposing this be added into capistrano? It only needs to be done once per machine, right?

**Comment by sanfordd** [comment]
@hackmastera I think it is only once per machine. I'm not sure we can add it anywhere prior the capistrano deploy since we won't have passenger on the machine prior to running capistrano on a fresh box, but if I am missing a simpler fix I'm happy to have it go somewhere else.

**Comment by hackmastera** [comment]
Isn't passenger installed in the ansible scripts? Could a curl be added in as part of the passenger install role?

**Comment by sanfordd** [comment]
That's worth a shot. Let me go throw a quick test out and see if that works.

**Comment by sanfordd** [comment]
I gave it a couple attempts, if we do a lookup prior to the capistrano deploy going to the machine at http;//whatever generates a 403 error with the index being forbidden. That doesn't trigger passenger that the site is being used sadly.

**Comment by jrochkind** [comment]
I might try filing a support ticket with Passenger, they're pretty good at giving advice in my experience. This may be a bug, or it may be known/intended in which case they may have advice for how to deal with it.

**Comment by sanfordd** [comment]
It's a known bug, and it looks like one fix would be to try update a newer version of passenger.
See: https://github.com/capistrano/passenger/issues/2
The changelog for 5.0.11 say they fixed the error message
5.0.13 allows a safe exit if passenger isn't running, which would keep capistrano from erroring out, but not actually start passenger to restart things.

**Comment by jrochkind** [comment]
"not actually start passenger to restart things."

If passenger is not running, it'll automatically start on first request that it needs to handle, I believe. There will potentially be some latency while it starts up that first time. I believe there are documented ways around that.

**Comment by sanfordd** [comment]
@jrochkind The issue is that if the restart fails it breaks the cap deploy and anything that happens after that won't run. The 5.0.13 safe exit might work for that then.

**Comment by hackmastera** [comment]
It seems like a catch 22. You can restart passenger until the site has been hit at least one time. But you can't hit the site until the application is being served. So... go back to the old way of restarting the app? Is that way deprecated, or just looked upon with less favor?

**Comment by sanfordd** [comment]
@hackmastera  I think it's looked upon with less favor and we had the issue where the restart could cause some problems with a less than graceful shutdown, ie a user might get an error page.
The old method is better when we need to build a new machine (saves someone from needing to go to the URL after an aborted build to trigger the page enough that a second deploy finishes correctly) but the current method is better when the machine has been built.
I think we can add a simple wget command before the restart in capistrano and it should trigger the start for new deployments.

**Comment by jrochkind** [comment]
A request to 'warm' it is not a bad idea anyway, since Passenger can take a while to start up, better to pre-load it not wait for first real user request to trigger. 

I thought there was a way built into Passenger to make this happen, but a `wget` externally is fine too.

**Comment by hackmastera** [comment]
Currently this is blocked by a need for firewall rules to allow machines to access themselves via DNS

**Comment by sanfordd** [comment]
An exception has been added. It should work now @hackmastera

**Comment by hackmastera** [comment]
The best solution is to add `PassengerPreStart` to the apache conf in the build scripts. A systems issue has been created.
