### ISSUE TITLE
Design Discussion Document for Work "Show" page

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#535]
We need to redesign our work "show" page (what you get when you click on a work in search results or from a collection; or from google or facebook or a bookmark) to meet our understanding of user needs. While we can redesign it in the smallest ways possible or more significantly, _some_ redesign is needed to meet goals expressed in #312, which I'd also summarize as:

* Better interactive experience for dealing with multi-page works, including good ways to skim/browse/get an overview/skip around. 
* In-browser full-resolution zoom-in to our high-res scans. 
* Multiple download options in various formats
* Understanding 'extracted work' relation to parent work (I'm actually mostly punting on this one for now at this moment)

And:

* Maybe just some better all around UI/UX -- the visual prominence/hieararchy of things currently does not match their importance or frequency of use to the users. 

Because of the 'in-browser zoom' requirement, our page will need to involve a JS-based pan-and-zoom viewer, which is _probably_ tile-based (IIIF, DZI, etc), since our individual full-res images even encoded as JPG are, I _think_ too big to deliver to the browser effectively all at once. (3M and up I think, for full-res jpgs of our images, which I think is probably too large to just deliver in whole without tiling). 

When I consider possible designs from examples and our discussions, I think there are two major categories:  1) The JS "Viewer" embedded directly on the page you see as soon as you get to it; vs 2) An additional click on the initial page is needed to open the 'viewer'. 

Both have advantages and disadvantages. I think one key question, is: Are most users most of the time (possibly weighted by personas/user groups of higher priority for us) coming to the individual Work page (by click on search results, google, facebook, etc):

1. Wanting to immediately view and explore the scanned images/photos, or
2. Needing context beyond the images themselves (primarily the textual metadata we supply) to _identify_ whether this is the item they were looking for or an item of interest, or otherwise understand it's context properly before diving into the images. 

I'm going to show a few basic wireframe mock-ups of different possibilities in both these categories. The intention is to stay away from the individual micro-details of each, but focus on these general macro-approaches as alternatives, and start thinking about possibilities. Likewise, while I'm listing some brief implementation considerations for context, they are not meant to be the focus. 

It's also possible none of these are in the right direction, or that this document/exersize is not actually helpful to us -- I'm open to that! 

# A page where viewer is NOT on original page, but takes another click

![non-front-viewer full](https://cloud.githubusercontent.com/assets/149304/26174784/7906d428-3b1e-11e7-806c-ae3452740d00.jpg)

I think this can be a very attractive and straightforward (easily comprehensible by users) page, which makes immediate sense to give you an idea of the work on landing on it. BUT it will require an additional click to get actual pan-zoom viewer. You can click on the large 'representative' image, or on the smaller thumbnails for other pages to get a viewer. (ALL pages be on the page, as they are in our current production; or there might be some pagination or limits). 

You can possibly download various formats directly from this page; or from the viewer; or both. 

My hypothesis is that the current "File detaisl" pages (eg https://hydra.chemheritage.org/concern/parent/cn69m4595/file_sets/mg74qm57b) are of use only to staff, not to the end-users. Staff might need a way to get there (from original page or viewer), but end-users don't need these pages -- they need the Work page, and the image viewer. I carry this hypothesis through all the 3 designs shown here. 

Once you click on a thumbnail, you'd get a viewer (perhaps in a 'pop-up' window, perhaps a navigation), that looks something like:

![non-viewer-front viewer](https://cloud.githubusercontent.com/assets/149304/26175018/3b1dc7f6-3b1f-11e7-8db7-4b6ca7334bc9.png)

Note you do still get thumbnail browse on the viewer page; a form of it was also on the original page as important overview. 

The viewer page would look much the same on tiny mobile screens too -- on the smallest screens might have to skip the thumbnail browse and just have next/previous. 

The original page above will of course have to look somewhat different on a small/mobile screen, since it uses a wide horizontal layout. On a smaller screen, maybe:

![non-front-viewer mobile](https://cloud.githubusercontent.com/assets/149304/26175088/7b4f0bdc-3b1f-11e7-80a8-c57a63e3861e.png)

### Implementation notes

The original page is perfectly straightforward html. The 'viewer' would probably use openseadragon, but not neccesarily "universalviewer" or similar, we should be able to build it ourselves from openseadragon, it's not complicated. 

Especially if using openseadragon directly, we could consider/explore using a cloud hosted image server like imgix instead of a local riiif server. 

# An immediate viewer, fairly basic/naive approach

The Wellcome Library has been suggested as one example. [See example page](https://wellcomelibrary.org/item/b19703181#?c=0&m=0&s=0&cv=14&z=-0.1734%2C-0.0357%2C1.3579%2C0.6554&r=0).

This takes something much like our current design, and just plunks a viewer down near the top of the page. The Wellcome Library happens to use (and have originated) the [Universal Viewer](https://github.com/UniversalViewer/universalviewer) javascript package. 

I personally find this design not very successful:

* I don't like the way the actual 'viewer' area is limited to a certain size, even if my screen is huge. (Unless I recognize and click the 'full screen' button, which takes over my entire screen menu-bar and all, which I tend not to do unless on a web site I'm _really_ invested in)
* On a _smaller_ than typical screen, the "universal viewer" UI/UX starts breaking down. (Grab the corner of your browser window and make it very small to see)
* If scrolling using a mac touchpad, as soon as your finger/pointer is over the viewer area -- you stop scrolling, it's captured it to zoom.  (Not sure what it will do on a touch screen, we need to try it out). In general, I think pages which have _both_ a whole-page scrollbar _and_ a zoomable area are somewhat confusing to users the zoomable area really wants to be the whole page. 
* Is a user who arrives here going to even notice the metadata context below? Do they understand what they're looking at?
* Why is there a "More Information" tab that shows me much the same content (but formatted differently) as is below the main panel?  
* In general, I think the visual layout of the viewer on top of the page is awkward
* I feel like whether it's designers knew it or not, this viewer is really asking us to make it the _whole viewport_, not just an inset on the page. 

One advantage can be it needs little design work -- just plunk the viewer at the top of our existing page, for now. And it at least _hypothetically_ needs little implementation work -- just use the already existing Universal Viewer. 

### Implementation notes

"Just like wellcome library" would naturally use the UniversalViewer JS package. 

Looking _just a bit_ at the UniversalViewer, I'm not actually completely sure how customizable it is. It's somewhat under-documented, but it looks like customization (including theming) is done by _forking_ the source code and customizing, and then using git merges to try to keep up with upstream changes. This is not ideal, but could work. 

It's unclear how hard it will be to customize other parts of the UI -- different 'content' window, different 'download' links, etc. 

I think integrating the UniversalViewer, even just as it is, could take significantly more implementation work than just "install it and turn it on" -- but necessarily will of course be less work than using the UniversalViewer _and_ doing more complex changes to our pages, instead of just plunking it in. 

# Single-page on-screen viewer. 

Following up on the thought that the on-screen viewer above is in a sense "asking" to be the entire viewport, I investigated a design that is more "app-like", where you have a viewer app that takes up your entire browser window and is more 'interactive' than a typical web page (implemented with javascript, naturally).  In a sense, it's the UniversalViewer just blown up to the be the entire page -- this is, recall, what people are going to see when they click on a search result (or arrive from google/facebook) -- but I just did a basic wireframe design that differs in some ways, instead of just copying UV. 

![one-page](https://cloud.githubusercontent.com/assets/149304/26175724/9f2c871c-3b21-11e7-9f6b-df4a1bf459a2.png)

This takes up your whole viewport -- although not neccesarily each column having equal width. On a really large monitor/browser screen, the central image column would probably take up most, giving you a area column to pan and zoom in, with the side columns being narrower. But there is no whole browser-window scroll bars, horizontal or vertical. 

Both side columns do have their own vertical scrollbar.  The left one is more or less the info on our current textual 'work detail' page, perhaps redesigned somewhat -- you can scroll it independently, the image stays where it is.  The right one is your list of all thumbnails, giving you browse/skim/overview and quick navigation. 

You could choose to hide some of the columns, be looking at just one or two instead of all three at once. UI device for this not sure yet, but I bet we can come up with something. 

On a very small (mobile) screen, you couldn't fit all three columns at once, you might only be able to look at one at a time, but still some UI device to switch back and forth. Not sure which would be the initial/default column/tab on a small screen. 

### implementation details

Potentially we could just take the Universal Viewer and manage to make it take up the whole viewport. Not totally sure if this is feasible. We'd probably want to customize the "More Information" tab (eg Wellcome Library), if this really is the entire 'work detail' page it needs to be more carefully designed, not just a list of labels/values.  Again, not sure how feasible customization of UV is in general, but it may very well be. 

We could also probably do this with OpenSeadragon for the central image pan/zoom, and the rest ourselves with our own JS, without too too much trouble. Probably. 

# Thinking outside the box (literally!)

One more, just to push the envelope, as they say. 

All these examples let you skim/browse/navigate through pages by giving you a list of thumbnails (in one format or another), which you click on to load the page. 

What if instead we wanted to support one big scroll through ALL the pages -- like google books for instance, see: https://books.google.com/books?id=x2CqiwsSg_wC&pg=PA18&dq=kropotkin&hl=en&sa=X&ved=0ahUKEwit1K-26vfTAhWpgFQKHZPKAT8Q6AEIMzAC#v=onepage&q&f=false

When you want _also_ to be able to pan/zoom each page, this gets challenging from both implemenatation and UX perspective.  But -- image if it were like one giant canvas with all the pages on it, [prezi](https://prezi.com/)-style?  Believe it or not, this is actually quite feasible -- once you've put an OpenSeadragon tile-based-image viewer in, you can totally have an enormous prezi-style canvas that you move from page to page on. Although it would get tricky figuring out which page you are currently on for your 'download' links. 

Overall, I think this approach is probably too "experimental" for us right now, too much uncharted territory, even if theoretically technically possible.  I thought it was cool so wanted to throw it in as a more experimental alternative pushing the boundaries though. 

We could also imagine offering users _multiple_ "Work detail" pages, they can toggle between. But one still has to be the initial/default one (which many/most users are unlikely to change), and I think we probably have to start with one of them anyway and don't want to commit to more than one before soft-launch, so I think that's also a potential future enhancement (which may or may not be a good idea) to put away for now.

**Comment by MDiMeo** [comment]
Some other image viewers to check for comparison (some with personal notes, gathered through conversation with others):

https://wellcomelibrary.org/item/b19703181#?m=0&cv=14&c=0&s=0&z=-0.0787%2C-0.0364%2C1.1575%2C0.7271 (This is the reference to the Wellcome Library in @jrochkind's post above. It was originally cited in #312 and I'm just repasting it here so it's all in one place.)

 http://records.cmoa.org/things/55dd1b6e-9b61-469c-8084-3b52ca69d88b/ 
- viewer stays on page with metadata, intuitive design, only appears to work with two items 

https://www.digitalcommonwealth.org/search/commonwealth:4j03d9202 (single image)
https://www.digitalcommonwealth.org/search/commonwealth:gq67k665h (book)

https://www.wdl.org/en/item/17588/ (book) (Similar to the Digital Commonwealth one.)

https://repository.library.brown.edu/studio/item/bdr:10661/
-  different view options;  clunky zoom (having to click on the plus sign each time and not being able to use the mouse scroll)

http://digital.bodleian.ox.ac.uk/inquire/Discover/Search/#/?p=c+5,t+,rsrs+0,rsps+10,fa+ox%3Acollection%5EWestern%20Manuscripts,so+ox%3Asort%5Easc,scids+,pid+534b84e5-6f04-44ef-9eb6-ceff9b0806ca,vi+043ee5e3-9bf4-4a04-a9f8-717100941d77
- keeps the metadata and search bar intact but design is too busy and hard to use

http://digitallibrary.hsp.org/index.php/Detail/Object/Show/object_id/7742
@catlu worked with this viewer at HSP and is familiar with its problems but always liked the scrolling functionality for flipping through multi-page books

http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=2&xywh=-1%2C-116%2C4872%2C3603
- Universal Viewer was discussed above in great detail in @jrochkind's post, but @archivistsarah also mentioned potential for OCR & searching within works (via keyword search at the bottom)

http://books.northwestern.edu/viewer.html?id=inu:inu-mntb-0005986331-bk
https://collections.nlm.nih.gov/bookviewer?PID=nlm:nlmuid-66310800R-bk

http://digitalcollections.lib.washington.edu/cdm/compoundobject/collection/iww/id/43/rec/5
- thumbnails on the left, with current image highlighted; zooming isn’t smooth – reloads entire image; can’t scroll or click to zoom
 
https://dlc.library.columbia.edu/catalog/ldpd:113779
- metadata parallel to the image, image displayed in the record as something larger than a thumbnail, pop-out viewer is sleek & minimal, like that the thumbnails for multiple files in work (in the pop-out image viewer) disappear/appear on mouse-over, only seems to handle two items

http://library.duke.edu/digitalcollections/hasm_a0011/#info
- info button at the top that jumps you down to the metadata, arrows appear upon mouse-over & let you click through the work, same for the image # that appears bottom left (eg, “3/6”); like filmstrip thumbnails; didn't expect clicking on image takes you to a new tab with just the image & no metadata 

https://digitalcollections.nypl.org/items/510d47da-58b8-a3d9-e040-e00a18064a99#/?uuid=510d47da-58b1-a3d9-e040-e00a18064a99
- Title at the top, filmstrip thumbnail viewer with highlighted image to show you where you are in a multi-file work, images display large by default when viewing the work; if you “view as book” the way to get back to the work record with the metadata is not immediately clear; zoom button instead of click or scroll to zoom (also the button gets bumped off the screen once you click it, so it isn’t immediately clear how to zoom back out); breadcrumbs at the top before the title not terribly informative (“Item”)

**Comment by jrochkind** [comment]
We decided to progress with the first design, "extra click for viewer". 

Some combination of @hackmastera @MDiMeo or others will provide:

* Description of "what the viewers will want to do on this page" use cases, that can be used to evaluate a design in terms of how well it lets them do it

* Some written critiques of the current wireframe, to inform a second wireframe.

**Comment by hackmastera** [comment]
Pulling from the personas, here are are the needs / goals that seem most strongly related to the work show page:

- Andi: Wants to use the books she consulted while a fellow at CHF when she’s back home in Europe
- Andi: Needs a quick download for images to use in a PPT lecture
- Andi: Needs a high resolution image to be used for publication with clear permissions and credit information
- Nadia: Wants to find objects online that she saw in CHF’s Museum and be able to share them with friends
- Nadia: Needs to help her kids find resources for their homework and help them to properly cite those sources
- Nadia: Wants additional context and information about new objects she finds online
- Nadia: Wants to download and print a high resolution image to hang on her wall
- Dennis: Needs to embed link in his blog or easily download a file (image or A/V) to be uploaded into his blog
- Dennis: Needs an easy way to share on social media
- Lionel: Wants to be able to quickly download file for his notes
- Cody: Needs to easily download images for a school oral presentation
- Cody: Needs to easily download images for a school oral presentation
- Frank: Wants to correct CHF metadata by telling staff the name of an instrument he used in a lab which is featured in a photo in the digital collection

Some of these rather duplicate one another. None really go into specific detail about viewer interactions.

Note I didn't include points about linking to other objects, finding more content, etc. That type of stuff is sometimes found on a show page but would probably open up this conversation to new feature considerations we're not ready to have right now.

**Comment by jrochkind** [comment]
@hackmastera thanks! Feel like brainstorming turning those into a few things they want to _do_ on the show page -- not specific implementations, but like, um....  

"Needs to help her kids find resources for their homework and help them to properly cite those sources" -- might turn into "Needs to know how to cite the thing she found", although I'm not sure we're prioritizing that at the moment. 

"Wants to use the books she consulted while a fellow at CHF when she’s back home in Europe" -- might be "needs to READ the book (in browser, or by download, which does she prefer? hard to say)"

I'm actually not sure how useful this is, and I think the ones you pulled out are already quite useful, just trying to see if we can follow the path suggested by my buddy, to identify "things the user needs to _do_ on this page" expressed in general user-centered terms (rather than assuming implementation) -- that we can use to evaluate the design.  This is potentially a difficult thing to do!

**Comment by hackmastera** [comment]
It appears we've settled on the first approach: clicking a thumbnail opens the viewer at that spot in the work.

My thoughts after looking through all the examples.
- I think the title should span the full width at the top of the page to bind the two columns together.
- The proportion of the screen given to each column is a bit unclear from the wireframe. In nearly all the examples given by @MDiMeo the image is given more width than the metadata. In one the image is smaller and in some the image is given full width above the metadata. [The Carnegie Museum of Art example](http://records.cmoa.org/things/55dd1b6e-9b61-469c-8084-3b52ca69d88b/) has a nice layout and seems relevant. I think giving the image more width than the metadata would allow maybe rows of 3 thumbnails below, which would balance nicely with the 2 primary columns.
- Tools area needs to be worked into the design (especially social media buttons)

I've also looked more closely at the [NYPL example](https://digitalcollections.nypl.org/items/510d47da-58b8-a3d9-e040-e00a18064a99#/?uuid=510d47da-58c0-a3d9-e040-e00a18064a99) and I think it could be a possible model for a hybrid approach between the in-browser viewer / click to use viewer. It allows you to change this image is the "big" thumbnail using your arrow keys. However, you cannot zoom until you click 'zoom.' I think we could use this as a way to navigate on the screen and then have a 'zoom' button trigger the full viewer, such that when you're on the main record page your mouse is never captured. Interested in your thoughts, @jrochkind; might save us some design trouble w/r/t the thumbnails list by allowing us to have a little thumbnail ribbon on the page itself.

**Comment by jrochkind** [comment]
An example from a commercial rare book seller. They put the large image (and other images) on the _left_, like Carnegie Museum of Art, which I think is interesting -- the left kind of the more prominent location, really emphasizes the image content. 

http://www.crouchrarebooks.com/books/view/ross-j.c.-grandes-descubrimientos-polares-terrestres-y-maritimos-hechos-des

Also just have social media share buttons at the bottom of the metadata, although the metadata is collapsed in areas so it's not going to scroll probably

**Comment by MDiMeo** [comment]
**Primary Audience's User Personas:**
- Nadia: Intellectually Curious Museum Visitor https://public.3.basecamp.com/p/L61ivni5MMMbtddB4mxiSu2J
- Andi: Scholar/Teacher https://public.3.basecamp.com/p/422ekL6UKJRGmE8oXAL7yCU2
- Dennis: Science Blogger https://public.3.basecamp.com/p/regRDRHc2Dy8gNqSsdroAdk6

**Secondary Audience's User Personas:**
- Frank: Donor/Scientist https://public.3.basecamp.com/p/8uiivXVKJcZCgCH7iEHfff2n
- Lionel: Lawyer/Corporate Client https://public.3.basecamp.com/p/jMch4dPeJNb5wR8vsaK2n43S
- Cody: Student https://public.3.basecamp.com/p/i1tCxi7fmJAS3fqshNWganCe

**Comment by jrochkind** [comment]
@MDiMeo So, in my current viewer prototype, IE 11 seems to work fine.... but the viewer is really broken in IE10.

What are the chances we can decide we just support IE11+?

Not sure whether I'd have to take a completely different CSS approach for viewer to do IE10.
