### ISSUE TITLE
move to single 'date' field - add datetype to TimeSpan object

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#54]
TBD: Predicates
TBD: display details

**Comment by catlu** [comment]
I think we were using dcterm predicates to narrow them down, but for one single 'date' field we'll probably want to use dc11:date. And if I remember correctly, dcterm:dateCreated was the one already in use by Sufia, so we should be good. Let me know if that works.

**Comment by hackmastera** [comment]
With these we had to turn the predicates around, so we actually didn't have a predicate file the file to the date object. We were using chf:work_date_of from the date to the file. I can change that to be chf:date_of.

The predicate we really need is one to hold the 'date type' on the EDM.TimeSpan object. Start and finish are EDM.begin and EDM.end, and the qualifiers are CRM.P79 and P80. So maybe EDM or CRM have a date type predicate? It needs to have a range literal.

Also, I'll need a list of possible date types, unless you want it to be a free text field.

**Comment by hackmastera** [comment]
@MDiMeo it looks like @catlu and I left the meeting with different understandings of the plan -- Maybe you could stop by some time today to help resolve?

**Comment by hackmastera** [comment]
We've decided we don't need a date_type field.
