### ISSUE TITLE
Solr deploy error

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#541]
Another fun issue, when deploying out solr setup to a fresh box we run into an error when it tries to create the default admin setup.

It looks like the simplest fix is to restart solr between deploying the solrconfix.xml and the admin set creation, as restarting solr and redeploying causes it to work fine.

See the full error here: https://gist.github.com/sanfordd/cf966c1c9bdea0c10f95019ded668216

**Comment by hackmastera** [comment]
refs #421; this would be part of that cap task

**Comment by hackmastera** [comment]
Hm, nevermind this is not part of 421. when solr is separated out the admin set creation task won't be run on that box at all.

So solr needs to be restarted no matter what box it is on as a prerequisite of the admin set creation task.

**Comment by hackmastera** [comment]
or instead, the solr box issues a solr restart as part of its deploy. that's better.

**Comment by hackmastera** [comment]
@sanfordd does solr truly need to be restarted or could we hit the rest api with a reload command?

https://wiki.apache.org/solr/CoreAdmin#RELOAD

**Comment by hackmastera** [comment]
reloading doesn't work for the first deploy because the core hasn't been created yet. We need to restart solr. Plan is to provide a flag via capistrano such that if the flag is there, solr restarts; otherwise it just reloads the solr configs.
