### ISSUE TITLE
Clean searches table

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#542]
Prior to soft launch we should start running a task to clean out the searches table in postgres to avoid storing too many old searches. According to the devops channel for Hydra there's a blacklight rake task (https://github.com/projectblacklight/blacklight/blob/master/lib/railties/blacklight.rake) we can use.

Once that's set, a scheduled vacuum task for postgres should keep the database to a manageable size.

**Comment by jrochkind** [comment]
@hackmastera you feel like doing this one?

**Comment by hackmastera** [comment]
sure

**Comment by hackmastera** [comment]
@sanfordd Does the vacuum task already exist or does that need a systems ticket?
