### ISSUE TITLE
Ampersand affecting search

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#544]
For these results: https://hydra.chemheritage.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=benzo, when I click on the Creator link, it facets correctly.

However when I click on the show page for either of the books, and click on the Creator link from there, this happens: https://hydra.chemheritage.org/catalog?f%5Bmaker_facet_sim%5D%5B%5D=Farbenfabriken+vorm.+Friedrich+Bayer+%26amp%3B+Co.

**Comment by jrochkind** [comment]
bah, looks like an escaping error. can look into it.

**Comment by jrochkind** [comment]
This is a bug in CurationConcerns/Sufia. i've submitted a fix to hyrax at https://github.com/projecthydra-labs/hyrax/pull/1027, but probably won't be in a hyrax release until 2.0, which we won't be on for a while. 

Considering best way to backport.
