### ISSUE TITLE
Upgrade to Rails 5.0

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#545]
Before soft launch, if we have time, me and @hackmastera think it might make sense to upgrade to rails 5.  Prob not 5.1 yet. 

Rails 4.2 which we are on is effectively end-of-lifed, and doing it sooner would give us the opportunity to write code now that will work in rails5 without deprecation using new rails5 api. 

@hackmastera thinks it should be fairly straightforward based on our hyrax experiment (we are _not_ suggesting upgrading to hyrax any time soon, before soft launch). 

@MDiMeo fyi

**Comment by hackmastera** [comment]
I expect we could easily lift the relevant commits from this branch https://github.com/chemheritage/chf-sufia/commits/hyrax-upgrade-test
