### ISSUE TITLE
new navbar

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#552]

**Comment by hackmastera** [comment]
About, Help, and Contact all appear to use the homepage layout. The homepage layout is actually used all over the place, basically for anything mildly peripheral to the app:
- https://github.com/projecthydra/sufia/blob/7.3-stable/app/controllers/static_controller.rb
- https://github.com/projecthydra/sufia/blob/7.3-stable/app/controllers/concerns/sufia/contact_form_controller_behavior.rb
- https://github.com/projecthydra/sufia/blob/7.3-stable/app/controllers/pages_controller.rb#L6

application layout doesn't seem to be used at all (after much clicking around with a debug message in there, I never hit the debug).

I don't think we need a new layout. We can customize the header with the `masthead` partial, the navbar (where the search box with the `

**Comment by hackmastera** [comment]
I think the right thing to do is customize the homepage layout for use on the static pages (like about, etc)

Then create our own homepage controller (maybe call it frontpage to make it easier to distinguish from sufia and because that's what we call it), inherit from Sufia's homepage controller but change the layout back to the standard sufia layout.

Customize header via the `masthead` partial and footer via the `shared/footer` partial. I *think* we can ignore the navbar stuff on the frontpage and it just won't show up.

**Comment by hackmastera** [comment]
Or maybe we don't want to inherit from sufia's homepage controller since we don't really want anything it has. Even its recent items functionality seems slightly different from what we would want (I think it may be too broad for our use)

**Comment by jrochkind** [comment]
I don't understand why we'd need/want more than one layout. Don't we want the new branded navbar on _all_ pages?  Is there any reason we need a separate layout for just homepage, or just static pages, or just anything?  Is there any reason we need more than one layout?

I guess if sufia already _is_ for reasons we can't figure out... then I don't really know what to do.

**Comment by jrochkind** [comment]
Looks like sufia supplies an 'admin', a 'homepage', and a 'sufia' layout, where 'admin' and 'homepage' render 'sufia' internally. 

Can we just change all the controllers that use the 'homepage' layout to just use the 'sufia' layout instead?

Or change all controllers everywhere to use a 'chf' layout, that calls out to 'sufia' the same way 'homepage' and 'admin' do?  

We should be able to change what layouts controllers use... probably. But I can't quite figure out what the best design here is either, not clear to me what/why sufia is doing in the first place.

**Comment by hackmastera** [comment]
I'm not sure it would be better to override all the controllers? I think it would also be more brittle.

**Comment by hackmastera** [comment]
I think sufia wants these static pages to look like the home page (with the banner image, etc). But of course we don't have that and just want all internal pages to look the same.

**Comment by jrochkind** [comment]
It _ought_ to be possible to choose what layout(s) you want for your app without it being brittle, but I don't know if that means it _is_ so.  But I would think that would be a common use case, but who nows. 

Okay so if our end goal is we don't _want_ a special homepage layout.... 

another way to approach it, override homepage layout to do nothing but `<%= render template: 'layouts/sufia' %>`... which it was it is?  So we're done with that part? Just have the homepage layout do nothing but defer to the sufia layout, and now everything has the same layout, as desired?

Figuring out how to actually customize that 'same layout' in a non-brittle way to have our desired branded navbar... exersize to the reader. Simply copying over the sufia layout locally would be one way, but that's usually not the 'not brittle' way, but might be the least evil here.

**Comment by hackmastera** [comment]
Yes I think it will work. We'll see what you think of the PR.
