### ISSUE TITLE
Multiple box deploy

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#567]
We will need to make sure the deploy option supports deploying to at least 3 machines, 2 of which will have Ruby (Sufia and a background jobs processing machine) and one (Solr) which will not need to build or run anything and just needs to get the solrconfig file(s).
This is linked to #421

**Comment by hackmastera** [comment]
this is straightforward; can define multiple boxes by role in the relevant `config/deploy/` file/s.

**Comment by hackmastera** [comment]
exemplified in #613; we'll do each one as it comes along.
