### ISSUE TITLE
Content for About, FAQ and Contact pages

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#572]
I will add docs here after they've been approved by appropriate CHF staff members.

**Comment by MDiMeo** [comment]
Content for the About page was approved by the development office. There is a chance that we'll have to edit this again once the site circulates more widely among stakeholders, but here's what's been approved for now:

About

Our Digital Collections offers digitized highlights from CHF's Library, Archival and Museum collections. It represents only a small portion of our entire collection, with new material added every day. More information about our Collections is available here. [Hyperlink to https://www.chemheritage.org/collections] 

The purpose of the Digital Collections is to offer one central location to manage, preserve and provide access to all of CHF’s digital assets. It is built on the open-source technology stack Samvera (formerly Project Hydra), comprised of Fedora 4, Solr, Blacklight and Ruby on Rails. All of our code is freely available on GitHub via an Apache 2.0 license. [Hyperlink to https://github.com/chemheritage/chf-sufia]

This project was made possible in part by the Institute of Museum and Library Services grant SP-02-16-0014-16. We also wish to acknowledge the generous support of the Arnold and Mabel Beckman Foundation and Robert W. Gore. [If possible, please include an approved IMLS logo from here: https://www.imls.gov/grants/manage-your-award/grantee-communications-kit/imls-logos]

**Comment by hackmastera** [comment]
The about page has been reimplemented as a 'content block' page, which means if you visit is as a logged-in admin user you have the ability to edit the page. The contents of the page are stored in the database, so will not be the same from site to site. I can go ahead and put this in on production, though.

**Comment by hackmastera** [comment]
Nevermind the content block business doesn't allow links. I'll have to override this with our own page.

**Comment by MDiMeo** [comment]
New copyedited content for About page: [please replace with this:]

About

The Chemical Heritage Foundation’s Digital Collections offer highlights from its library, archives, and museum collections. Although the Digital Collections include only a small portion of our entire collection, new material is added every day. More information about our collections is available here. [Hyperlink to https://www.chemheritage.org/collections] 

The purpose of CHF’s Digital Collections is to manage, preserve, and provide access to CHF’s digital assets all in one location. It is built on the open-source technology stack Samvera (formerly Project Hydra) [https://projecthydra.org/], composed of Fedora 4, Solr, Blacklight, and Ruby on Rails. All of our code is freely available on GitHub via an Apache 2.0 license. [Hyperlink to https://github.com/chemheritage/chf-sufia]

This project was made possible in part by the Institute of Museum and Library Services grant SP-02-16-0014-16. We would also like to acknowledge the generous support of the Arnold and Mabel Beckman Foundation and Robert W. Gore. [Consider including an approved IMLS logo from here: https://www.imls.gov/grants/manage-your-award/grantee-communications-kit/imls-logos]

**Comment by MDiMeo** [comment]
Contact Us

If you have a request or a question, first check our Frequently Asked Questions page [https://digital.chemheritage.org/help]. If your question is not answered there or you want to report a problem, contact us via e-mail at digital@chemheritage.org. [Use Mailto: for email]A staff member will reply to you shortly.

**Comment by MDiMeo** [comment]
Please use MailTo: each time the email address comes up below. This is the copy edited text, so all punctuation, etc., must stay the same:

Frequently Asked Questions

Why does it say this site is in beta?
We are in a “soft launch” phase in which we are testing the Digital Collections before the full release. Every day our software developers are adding new code to enhance the features and improve the design. The site may look different from one day to the next, and you may experience some errors or downtime.

How do I report a problem?
Please send us an e-mail at digital@chemheritage.org. 

How do I request a copy of the images in the Digital Collections?
All items are freely available for download via the “Download” icon at the bottom of the image. As part of our mission to make our collections available for research and outreach, the Chemical Heritage Foundation provides free downloads of its Digital Collections material for scholarly and general use. However, patrons are solely responsible for determining the copyright status of any materials they wish to use, investigating the ownership of the copyright, and obtaining permission for the intended use.

I want to use the image I downloaded from the Digital Collections for a specific purpose (i.e., future publication or commercial product). Can you give me a rights license to do this?
Possession of a digital reproduction of CHF’s collection materials does not constitute permission to publish, exhibit, or distribute. In most instances CHF does not hold the copyright to its materials and cannot grant or deny permission to use them. CHF staff has applied standardized Rights Statements [http://rightsstatements.org/en/] in an effort to inform patrons of an item’s copyright. Additional information about the Rights Statement is provided by clicking on the link in the Rights field in an object’s metadata record. If you have a question not answered by the information provided with the image, feel free to e-mail us at digital@chemheritage.org 

How do I cite an image?
Please use “Courtesy of CHF Collections” in your credit line. When possible, we ask that you also include the title of the image or name of the collection.

The item I want isn’t in the Digital Collections. How do I request a new reproduction? How long will it take to process?
More information about our Digital Reproduction Services can be found here: https://www.chemheritage.org/rights-and-reproductions. 

I want to see other items in your library or museum that were not digitized.
For more information on how to access the full holdings in our physical collections, see CHF’s Collections page: https://www.chemheritage.org/collections. From there you will be able to search our library catalog and the oral-history catalog, and make an appointment to schedule a research visit.

I believe I own the copyright to an image, but I’m not credited. How do I tell a staff member and/or request that the item be taken down?
CHF makes its collections available for education and research and makes reasonable efforts to present accurate and reliable information about copyright. If you believe you hold the copyright to an item and/or want to request that an item be taken down, please e-mail us at digital@chemheritage.org, and we will consider your request. Please include the URL or the full title of the image.

Can I make recommendations to improve the metadata based on my personal experience with the objects or people represented in the image?
Yes! Please send an e-mail to digital@chemheritage.org. You should include the URL or the full title of the image.

How do you decide what gets included in the Digital Collections?
We add new material on a daily basis, but only a small portion of CHF’s physical collections are represented here. Selection for digitization is guided by CHF’s Digital Collections Policy: https://chemheritage.atlassian.net/wiki/display/HDC/CHF+Digital+Collections+Policy. 

Can I freely download or extract your metadata?
We strive to make our linked open data freely available, and it can currently be accessed in JSON and RDF. Please note that our data are formatted for internal use and have not been cleaned up for distribution. In addition, our data model and API are currently undocumented. If you wish to use the data in their current form, you can get the RDF data via Turtle by adding “.ttl” to the end of a record’s URL. You can get the JSON data by adding “.json” to the end of a record’s URL. You can do the same for search results: just make sure to add “.ttl” or “.json” to the end of the URL before the query string. In general the RDF results give more complete data: more metadata fields are returned with search results, and better item membership information is returned with record results.

**Comment by MDiMeo** [comment]
This should be a childpage under About and not appear in the main navigation. 
Titles to sections should be in Bold. Titles of bullet points should be in Italics.

Digital Collections Policy


Mission
The Chemical Heritage Foundation’s Digital Collections strive to collect, manage, preserve, and increase access to CHF’s born-digital and digitized library, archives, museum, and oral-history collections. The Digital Collections support and encourage researchers, enable collections staff to manage and preserve digital objects, and facilitate public outreach through open access whenever possible. 


Scope
The Digital Collections further CHF’s organizational mission “to foster dialogue on science and technology in society” by building an online collection dedicated to the history of science, medicine, technology, and industry, with an emphasis on chemistry and related areas. Since the Digital Collections will draw from several departments across CHF, the collecting scope of divisions within the Digital Collections may vary and will draw from CHF’s existing collections policy governing physical collections. 


Purpose
The Digital Collections provide long-term preservation and high-quality access to CHF’s digital resources. Inclusion in the Digital Collections must be for one or more of the following reasons:

•	Access
Popular, significant, rare, or unique items would benefit from easier digital access and improved discoverability through cross-collection search and browse. Materials supporting the research of current fellows or those with restricted physical access due to fragility or value may be prioritized.

•	Preservation
Physical object is fragile or deteriorating and curators agree to digitize to reduce handling of physical object. Audiovisual files need bit-level preservation or transfer from obsolete media.

•	Outreach
Digitization supports CHF’s educational outreach and public programming or promotes collaboration with other institutions and individuals who share CHF’s mission. Such projects should be strategic and not on-demand one-off requests.

•	Innovation
Digital projects should increase the technical knowledge of collections and digital collections staff. Priority may be given to projects that encourage collaboration with, or raise our profile among, peer institutions.



Selection Criteria
Priority for digitization must also satisfy at least three of the following criteria but should strive to fulfill as many of the criteria as possible, when relevant:

•	Significance of the Materials
Items have intellectual, cultural, and/or monetary value. 

•	Current or Potential Users
Materials are heavily used and/or digital surrogates are frequently requested. Digitization would increase access to restricted materials or promote underused collections to potential new users.

•	Cataloging and Metadata
Physical items must be cataloged and archival collections must be processed and described before digitization. Staffing must be allocated for additional metadata creation.

•	Relationship to Other Collections
Item relates to other items being digitized within a single division, across other CHF collections, or at external organizations with whom CHF may collaborate.

•	Nonduplication Effort
Prioritize items that are not already freely available online unless a new digitization would improve upon the quality of the existing image or metadata.

•	Funding Sources
Priority for digitization may be given to items or collections that fulfill a grant or donor request, but only if the scope of the materials is consistent with the rest of CHF’s Digital Collections policy.

•	Copyright Clearance
Items in the public domain or with clear rights clearance will be prioritized. Items with dubious rights will be considered on a case-by-case basis, keeping in mind a larger commitment to providing access whenever possible. 

•	Condition of Materials
Select only items that can withstand digitization and that would produce good images (i.e., not books with tight bindings). Curators may consider digitization as a preservation mechanism for fragile items in need of conservation.

•	Representative of Work’s Intellectual Scope
Complete works, including cover-to-cover digitized books and entire archival folders, are preferred. Thoughtful sampling is permitted if item-level metadata would benefit plates in books or if the entire archival folder is not intellectually or visually significant or relevant to project-based selection criteria.

Standards
CHF’s Digital Collections support FADGI-compliant, high-resolution archival-quality images and audiovisual files for long-term preservation. All metadata in the Digital Collections must be consistent with national conventions, controlled vocabularies, Linked Data authorities, and ISO standards as described in detail in CHF’s Metadata Guidelines. Any requests for deviation from the Metadata Guidelines must involve the digital projects and metadata librarian.

Excluded Items
Excluded items may be revisited later for inclusion if capacity increases and priorities shift, but the following materials currently fall outside the scope of CHF’s Digital Collections:
•	Institutional records or educational materials created by CHF that are not part of the library, archives, museum, or oral-history collections (documentary videos, magazine materials, etc.)
•	Websites created by CHF or others
•	Datasets created by CHF, researchers, or others
•	Rights and reproductions requests that do not meet other selection criteria
•	Digital assets that are of poor quality (file too small, unprofessional crop, etc.)
•	Items that only require short-term use and management or that were never intended for a public audience or long-term preservation
•	Unprocessed or uncataloged physical materials


Staffing
Selection of items for inclusion in the Digital Collections will be made by the curator of the appropriate physical collection in conjunction with the director of digital library initiatives. The director of digital library initiatives is responsible for maintaining the repository and for quality assurance of images. Metadata will be pulled from existing collections management systems if possible. Additional metadata will be created primarily by the department responsible for the physical item, but in conjunction with the digital projects and metadata librarian, who is also responsible for metadata quality assurance. 


Deaccessioning
Individual objects or entire collections may need to be deaccessioned for reasons of violation of copyright or copyright dispute, inaccurate data or facts, collection weeding, or storage concerns, or because the material no longer supports CHF’s audience or goals. These decisions will be made in conjunction with the director of digital library initiatives, the curator of the appropriate physical collection, and the director of the appropriate division, and will be handled on a case-by-case basis. 


Changes to the Policy
All revisions to this policy must be approved by the Digital Collections Committee, which includes representatives from each of CHF’s major collecting units.

**Comment by MDiMeo** [comment]
Update to the About Page:
Please add the following sentence as the second to last sentence in the first paragraph (right before "More information..."):

Please see our Digital Collections Policy for more details on the scope and selection criteria. 
[Digital Collections Policy should hyperlink to the /policy page.]
