### ISSUE TITLE
New metadata field: Exhibition

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#573]
URI: http://opaquenamespace.org/ns/exhibit

Repeatable value with dropdowns:
Making Modernity
Transmutations
Things Fall Apart
Second Skin
Science at Play
Books of Secrets
Sensing Change
The Alchemical Quest
Inspiring Youth in Chemistry
Elemental Matters
Marvels and Ciphers
Molecules That Matter

Appear below Department on metadata edit and show page as well as facets.

**Comment by jrochkind** [comment]
Eventually, might we also want an "Exhibition" show page, sort of like the collection show page, with some description or other metadata about the exhibition?

**Comment by MDiMeo** [comment]
It was agreed that this content would live on the website. We plan to use Related URL to link to the exhibit page on the website.

**Comment by jrochkind** [comment]
Okay, good to know. I'd like to find a way to have a link clearly labelled "More about this exhibit" or whatever, to the related URL, instead of just a random unlabelled URL in a "related URLs" section. I think we can find a way to do that, in the post-soft-launch "get the design really good" phase.

**Comment by MDiMeo** [comment]
Also, from the CHF style guide: "For exhibits: Use “exhibition” for a show. An “exhibit” could refer to a single object or case within a show." So far, looks like we're on track by calling this field Exhibition.

**Comment by hackmastera** [comment]
@clu help text for metadata form?

**Comment by catlu** [comment]
"Select any current or past Museum exhibition(s) that the work has been displayed in, if applicable. If a desired entry is not available, contact the Digital Projects and Metadata Librarian."

**Comment by catlu** [comment]
Re-opening because I think we wanted this field in facets too. But feel free to close @MDiMeo if that changed.

**Comment by hackmastera** [comment]
I created a new ticket for that, see #811
