### ISSUE TITLE
Add 'File Creator' field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#59]
Let's use ebucore:hasCreator (http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasCreator) for this. Labeling it 'File Creator' will also keep it general enough for oral history and other non-imaging uses. Maybe place it before Admin Notes.

**Comment by hackmastera** [comment]
multivalued?

**Comment by catlu** [comment]
Single-valued for now, please!

**Comment by hackmastera** [comment]
this field is causing an error in the show page when single-valued. I've pulled the commit for now.

**Comment by catlu** [comment]
@hackmastera, what do you think about a local list of staff names to populate choices here? Would it be worthwhile over free text?

**Comment by hackmastera** [comment]
That sounds handy. by default this field and the depositor field both populate with a user id, which is an email address. I could potentially pull user IDs out of the database so that a config file wouldn't have to be maintained.

**Comment by catlu** [comment]
What about legacy or contract file creators? I think some images will be from previous photographers or outside vendors.

**Comment by hackmastera** [comment]
We can do a config file if that works better!

Are you thinking an autocomplete or a dropdown?

**Comment by hackmastera** [comment]
(config file is easier for me to set up)

**Comment by catlu** [comment]
Cool, sounds like config file will work best (wasn't sure if we'd have to create "dummy" accounts for those users). I think dropdown will be easier for cataloging. Is it possible to retain choices as data but also make them inactive at various points?

For example, let's say the current 'file creator' dropdown features John Doe, an imaging tech. Then, eventually, John Doe's successor is John Adams. Would there be a way to remove John Doe from the dropdown list while keeping the name as data where it's been cataloged?

**Comment by hackmastera** [comment]
Yes.

**Comment by hackmastera** [comment]
Yeah, creating dummy accounts for people who don't work here would be even more work than keeping a config file up to date.

I've got the field working so I'll start on a config file. Let me know how you want it populated.
