### ISSUE TITLE
Capistrano's solr reload is coded to localhost

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#600]
It looks like the solr core reload in config/deploy.rb line 98 is hardcoded to use localhost.
We'll want to find some way to have it figure out the correct information for the solr machine being used.

**Comment by jrochkind** [comment]
maybe have cap look up the solr host from the existing solr.yml, to have one less place with duplicate config?

**Comment by hackmastera** [comment]
The problem isn't the localhost, actually. If we just change that then the new solr box doesn't get its configs. We need to change the cap config files to take the `solr` role off of the staging box and define a solr-staging box.

This continues to require the .ssh/config setup which will get unwieldy. @sanfordd and I discussed changing that practice once our architecture has settled into its new shape. IP addresses and/or domain names would then be part of the public git repo.
