### ISSUE TITLE
new crop of autograph collection thumbnail

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#614]
Center on signature/autograph rather than the center of the page

**Comment by hackmastera** [comment]
@archivistsarah can you give me a link to the object?

**Comment by hackmastera** [comment]
I think it's this one https://digital.chemheritage.org/concern/generic_works/k643b119g

**Comment by hackmastera** [comment]
collection is h702q641c

**Comment by archivistsarah** [comment]
Just confirming that's the correct image
