### ISSUE TITLE
Clean up relics of lightbox

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#632]
once new show page / viewer are merged

**Comment by jrochkind** [comment]
We may not need the derivative image labelled 'jpeg' (actually a reduced resolution jpeg) at all once we have riiif fully implemented? We still need the 'thumb' for admin pages, but I don't think they use the 'jpeg', which we created?

**Comment by hackmastera** [comment]
Good point.

I noticed the file view page was still looking to pull in something lightbox-y but not succeeding. I'm not sure whether we need viewer functionality there of some kind? I can't remember the context in which I put that in. I'd like to check on that before doing the work for this ticket though.

**Comment by jrochkind** [comment]
Not sure, but for the moment, the file view page is only for admins.

**Comment by hackmastera** [comment]
consensus at the meeting was that we don't need any way to view an image on the fileset show page.

**Comment by hackmastera** [comment]
Do not remove the derivatives generation job; we are talking about possibly moving back to those.
