### ISSUE TITLE
GeoNames autocomplete for Place field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#64]

**Comment by hackmastera** [comment]
I stuck in FAST for now but we decided to switch to VIAF if possible.

**Comment by hackmastera** [comment]
We looked at VIAF and it seemed pretty unhelpful. The first result for 'London' was 'Sweden'. Closing for now; @catlu please reopen if you want to try something besides FAST here.

**Comment by catlu** [comment]
After meeting with Lee today, she mentioned she wants to input places like universities and personal homes and offices.

FAST Geographic headings doesn't offer 'University of Chicago', but the Corporate subheadings do. But it looks like Geonames has institutions, so can we try that instead?

As for personal homes and offices, is it possible to put in a Note field similar to the Date element?

**Comment by hackmastera** [comment]
I'd rather just have her use an additional 'place' field as opposed to a note. is there a reason that wouldn't work?

**Comment by catlu** [comment]
You mean bypassing the autocomplete? Yeah, that works too.

**Comment by hackmastera** [comment]
Autocomplete could still be an option, but if she wants to have, say, one entry for "University of Chicago' and one entry for "Professor's office" then one would use the autocomplete entry and the other would not.

**Comment by hackmastera** [comment]
drop geonames back in and look at whether there are punctuation issues that we need to resolve.

**Comment by hackmastera** [comment]
depends on #126
