### ISSUE TITLE
Collection image for Alchemy category on homepage

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#640]
https://digital.chemheritage.org/concern/generic_works/9306sz691

**Comment by catlu** [comment]
additional notes from @MDiMeo:
- For a crop, I like the Sol, Venus, Mercury.
- we should change the order on the bottom row. i vote for swapping Scientific Education with Alchemy based on this since we'd otherwise have the only two black and white shots on top of each other on the left

**Comment by hackmastera** [comment]
@MDiMeo re: the order, there's also #579; I've just recorded the order there; can you edit that one if you want a different order?

**Comment by MDiMeo** [comment]
Thanks for calling my attention to the other ticket! I lost track and thought the order had already been changed. I'll take my notes on ordering to the other ticket.

**Comment by hackmastera** [comment]
@MDiMeo re: the crop, it will either:
- include a good chunk of the middle column, and possibly get part of luna, as well
- or be pretty close on Sol / Venus, but with some of venus obscured behind the label.

I don't really think we can go wrong either way but let me know if you have a preference

**Comment by MDiMeo** [comment]
I don't have a preference. Looking forward to seeing what you come up with!
