### ISSUE TITLE
Ensure GA download data is in a usable form

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#668]
Once we've deployed the new events to prod, @MDiMeo should peruse GA and ensure the data is useful.

**Comment by hackmastera** [comment]
It looks like we'll need to make some adjustments. I poked around today.

First, in terms of the UI, once you get the the events area you can choose to see event categories, event actions, or event labels. If you select an entry in one of these categories, it will filter by that selection. to clear filters look up above the chart, just below the page title 'top events'. I note that here because it took me a minute to find it.

You'll see from the below that events registered from the viewer are a bit wonky and need to be adjusted. We can definitely fix once we figure out the answers to some of these questions.

Outstanding questions include:
- What should the categories be? Currently they are `ImageView` and `Files`. Probably should be 'Works' and/or 'FileSets'
- What should the actions be? Currently they are `fileSetId` and `Downloaded`. Probably should be `view`, `download-tiff`, `download-jpeg`.
- Event label is always an id. Should it always be a work id? should it always be a file id? This is the biggest question, tied in a little bit with the question of categories. Currently not clear which they are. If we keep using both kinds, should we consider prefixing them?

The biggest question is: what needs to be logged at the work level, and what needs to be logged at the fileset level? Do we always want to log at the work level? Do we want to sometimes log an event at the work level and the fileset level? Do we ever want to log all the way down at the file level? (unlikely, since the fileset is a stand-in for the file)

Currently there are events logged when a person downloads a tiff, downloads a jpeg (only in riiif branch, not yet visible in production data), or clicks into the viewer. For the questions, think about them for each of these types of events.

Finally, do we want to add event logging to each click once in the viewer, to see every single page they clicked on? If so, should it be logged just as an interaction with the work itself or with the page (either a work or a fileset, or, geez, if a work maybe the work's representative fileset) they clicked, or both?

**Comment by hackmastera** [comment]
Is the viewer url being logged as a pageview? if so do we need to add the viewer in as an action?

Note a viewer url includes a work id and a fileset id; is it possible to lump fileset ids belonging to the same work for reporting?

**Comment by hackmastera** [comment]
@MDiMeo would like to log at the work level, as opposed to the file level. All uses of fileset ids should be changed to use the parent work id.

For consistency it therefore makes sense for a nested work to log on its parent, unless the nested work is being accessed directly (e.g. https://digital.chemheritage.org/concern/generic_works/vq27zn59x rather than https://digital.chemheritage.org/concern/generic_works/4b29b614k)

**Comment by hackmastera** [comment]
Doesn't look like the viewer url is recorded under pageviews. so we will need an event for that.

@MDiMeo I assume we want an event logged each time a viewer is opened. Do you also want an event logged each time a new image is loaded in the main viewer window? (i.e. an arrow is clicked, a different thumbnail is selected)

**Comment by MDiMeo** [comment]
@anna Not for now. I'm just going to have to report on how many open the image viewer at all. Can we log how long they stay in the image viewer?

**Comment by hackmastera** [comment]
I don't think so.
