### ISSUE TITLE
re-enable batch edit

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#67]
depends on https://github.com/projecthydra/sufia/issues/1003

**Comment by hackmastera** [comment]
I can turn the page back on by removing the following fields from the form:

* These because they are single-value and the batch edit is only written to handle multi-value fields:
 * division
 * physical_container
 * rights_holder
 * file_creator
 * admin_note
* These because they are nested fields:
 * date_of_work
 * inscription
 * additional_credit

(Note also these are removed from the batch form by default; I imagine there's some sort of use case assumption; I can't really turn these back on)
 * title
 * format
 * resource_type

We can remove these to get the form back on for the rest of the fields if that will be helpful. I will comment separately on limitations of batch edit functionality and difficulty of incorporating single-valued fields.

**Comment by hackmastera** [comment]
Batch edit has pretty limited functionality as currently implemented. Here's how it works. You select a group of records. For each of the possible fields, it clumps together all the values of that field from all the records. You can then edit the values of that field on all records as a group. The limitation is that you have to want every single value for that field to be exactly the same for each record.

For example, let's say you have two objects Cat and Dog. Cat has a subject heading 'Flicky tail' and Dog has a subject heading 'Waggy tail.' Both have subject heading 'Fuzzy' and you want to delete that one from both. You select them, go to 'edit selected', expand 'subject', and click 'remove' next to the 'fuzzy' heading, then 'save changes'. Now go look at Dog. It has subject headings for both 'flicky tail' and 'waggy tail'.

**Comment by hackmastera** [comment]
The problem with single-value fields specifically is choosing which one should represent the set of selected records. Ultimately there's no way to choose and so a list must be presented so that if that is a field the user wants to edit, they can either select an existing value for all the records or enter a new value for all the records.

This will mean there are a lot of places where the code will need to handle both cases so I'm not sure yet how time-consuming it will be.

**Comment by hackmastera** [comment]
Some fields (like identifier) are available in batch edit but are not being populated correctly. These are fields that have custom form implementations.

**Comment by hackmastera** [comment]
It's back on. Improving the interface in various ways will go into other tickets.

**Comment by atz** [comment]
This is good to know. We should try to call it something that reveals its actual behavior like "metadata normalizer".
