### ISSUE TITLE
descenders in work titles getting cut off in viewer

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#672]
See the "g" in "Tanglefoot" in this example: https://staging.digital.chemheritage.org/concern/generic_works/fn106z052/viewer/gt54kn14d

**Comment by jrochkind** [comment]
Yep, I noticed that, I plan to wait until the visual redesign post soft-launch, when the font used here will probably be changing anyway, and make sure it's resolved then.
