### ISSUE TITLE
Collections search not searching all fields

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#673]
The use case is that a researcher wants to know everything that was digitized in a Series or Box in a Collection (i.e. Beckman Historical Collection). They can search for "Box 50" or "Series X" in the general search and get hits, but if they go onto the Collection page and search just that Collection, they get no results. We haven't tested this for all fields, but we're wondering if the same metadata fields were indexed in the Collections search as were for the general search.

**Comment by jrochkind** [comment]
Are you expecting them to get a _Collection_ as a hit, or an item in that collection?

**Comment by jrochkind** [comment]
Or better yet, cutting to the chase, can you give an example or two of a result you expect to be in the result set from a particular search, but it is not showing up?

**Comment by hackmastera** [comment]
@jrochkind it sounds like this is a problem on the search box embedded in a collection show page, not the general search results.

Agree a link to a result url would be helpful, @MDiMeo

**Comment by MDiMeo** [comment]
Because there is no way to limit a search to a specific Collection via facets for Collections, we went onto the Collection page and used the Search box in there. If you search for "Series X" in the regular search with no filters, you get this: https://digital.chemheritage.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=series+X

Most of these hits are from the Beckman Historical Collection, but when I go to the BHC's Collection page and search in that box for "Series X", I get nothing: https://digital.chemheritage.org/collections/wh246s128?utf8=%E2%9C%93&cq=Series+X&sort= However, that search DOES search some fields because I do get hits for pH Meter: https://digital.chemheritage.org/collections/wh246s128?utf8=%E2%9C%93&cq=ph+meter&sort=&q=ph+meter

The use case is that a user will want to limit a search by using the Series Arrangement or Physical Container fields within a specific Collection. There may be other ways to solve this (like adding the Collections Facet), but it also flagged up for us that the Collection search doesn't appear to be searching the same fields as the general search, which is confusing.
