### ISSUE TITLE
Cache fedora images to riiif box

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#675]
This will be a first pass at making the show page primary thumbnail load faster.

- [x] Task to force riiif to preload all originals (used when starting up fresh like this, or if we need to delete the riiif cache)

- [ ] "Actor" to ping riiif to load in cache immediately after file upload

- [ ] Deal with auth, need to get riiif to load cache even for private images, bah.

**Comment by jrochkind** [comment]
Currently running a task on staging as:

     RAILS_ENV=production INTERNAL_RIIIF_URL=http://172.31.63.136 bundle exec rake chf:riiif:preload_originals

Which pings riiif server for every file set original file id to get it to download original if not already in cache. Unclear how long it will take. Running under screen.

**Comment by jrochkind** [comment]
No longer relevant, we are not pursuing riiif at present.
