### ISSUE TITLE
Primary show page thumbnail displays with incorrect / variable aspect ratio

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#676]

**Comment by hackmastera** [comment]
also fixed by #680? @jrochkind?

**Comment by jrochkind** [comment]
Not quite yet fixed by #680, will do it now!

**Comment by hackmastera** [comment]
merged into riiif branch; closing

**Comment by jrochkind** [comment]
Oops, was the problem actually occuring in master too, should I have done this to master instead? Ah well, we're pretty sure riiif is gonna get merged one way or another, probably fine for now. Hard to keep track, sorry!

**Comment by hackmastera** [comment]
Oh, I'm actually not sure. I just meant that it could be closed even though it wasn't auto-closed. I think it's fine!
