### ISSUE TITLE
Child work links to first page in parent work

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#691]
When I am in the record for a parent work that includes both child works and files like [Ramelli](https://staging.digital.chemheritage.org/concern/generic_works/4b29b614k), I can click on the thumbnail for a file and it opens to that page in the viewer. But when I click on the thumbnail for a child work I expect to be taken to that page too, but instead it goes back to the first page of the parent. For example, I clicked on the thumbnail for Plate 2, but it took me back to the cover of the book.

**Comment by jrochkind** [comment]
closed by #693
