### ISSUE TITLE
keyboard shortcuts don't work when popup is active

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#694]
Either it should be clear that it needs to be closed to start using them, or they should work when it's open.

**Comment by jrochkind** [comment]
Also popup should scroll internal content if it's too high for viewport.

**Comment by jrochkind** [comment]
and other keyboard shortcut issues, when one of the buttons is "focused", keyboard shotcuts doesn't work, and in chrome it stays focused after last click.
