### ISSUE TITLE
Add 'Division' field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#70]
Just realized there wasn't a ticket for this field yet. Populate with dropdown list (probably no more than five options):

Center for Oral History
Museum
Othmer Library of Chemical History
Archives (?)

Library specifics still have to be decided. Earlier discussion here: https://basecamp.com/1929213/projects/8498313/messages/43862786

**Comment by hackmastera** [comment]
multi-valued? application profile says yes but I wanted to double-check.

**Comment by catlu** [comment]
Good catch, should be single-valued!
