### ISSUE TITLE
Deal with background jobs

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#703]
This is an upstream issue, and may be dependent on upgrading to hyrax. @atz worked on it some so it's worth checking in with him on where things stand.

The background jobs are not idempotent, and they are not particularly reliable. Making them idempotent would be a good first step. Making them smaller would also help; sometimes they are too large. More analysis / planning is needed here.

**Comment by jrochkind** [comment]
probably not going to be doing this rewrite of a part of sufia.
