### ISSUE TITLE
Codify a QA process

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#706]

**Comment by MDiMeo** [comment]
QA processes were written in conversation with @catlu @archivistsarah and @mhpmiller. Please all, let's keep these wiki docs up-to-date or do our best to follow the steps we wrote here when we are testing staging.

End User: https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/129892353/QA+Workflow+-+EndUser

Admin Tasks: https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/129925129/QA+Workflow+-+Admin+Tasks
