### ISSUE TITLE
Social media improvements

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#711]
To be discussed further:

* better sharing tags (to show a nice big image on facebook et al, the description and source attribution we want, etc);
* GA event so we know when people click on share buttons
* maybe pinterest; maybe no google+?

**Comment by hackmastera** [comment]
related: https://github.com/samvera/hyrax/issues/1323

**Comment by jrochkind** [comment]
@MDiMeo I'd like to propose removing Google+ share button, and replacing with pinterest. Yes?

Also, is "Google Analytics event tracking click on share button" still def something we want/need?

**Comment by MDiMeo** [comment]
Yes, pintrest makes way more sense than Google+! Let's swap these.

GA Event is desired, but not needed. It is not as high a priority as fixing the end user's ability to easily share images. But I do record the number of downloads when reporting in GA and would like to eventually add social media shares.

**Comment by jrochkind** [comment]
@MDiMeo I'll guess as to how it makes sense to file in GA, with GA metadata values. Like you probably want to know which service it's being shared to, and also what work was being shared, which is a bit tricky, but I'll guess at it and we'll see how it works out.

**Comment by jrochkind** [comment]
I wonder if social share buttons should only show up for items that are 'public'?  Can't really share non-public ones, it won't work right, and nobody will be able to see it anyway!

**Comment by MDiMeo** [comment]
When I want to answer the question "how many items have been downloaded?", I go under Event Action. The action itself has a title like "download original" or "download full jpg", and I can get numbers for each type that I can either leave separated or add up together. When I want to know "Which items were downloaded the most?", I go under Event Label and get the ID number and paste it to the end of a URL to view the record. A similar set-up with Actions and Labels would work for me for social media if you can do it. At the moment, I don't necessarily need to know which objects are shared the most on each specific platform, but I would like to know which services are getting the most usage (under Actions) and which items are getting the most shares across various services (under Labels). I'm also open to other ways of doing this if I can still answer these questions. Let me know if you need me to clarify this further!

**Comment by jrochkind** [comment]
I don't really understand how the GA attributes map to your GA UI, but it sounds like you're suggesting I try to copy how downloads are being handled as closely as i can, and it'll work? With the analogy that "which size download" for downloads is like "which service shared to" for social media.

**Comment by MDiMeo** [comment]
Oh, ok. Yes, exactly, that analogy works. And now that I think about it, I don't think you'll have to touch Label because as you've added more Event Actions my Label feature with the work IDs has stayed the same.

**Comment by jrochkind** [comment]
need to set the label on these new tracking events, but i'll try to set it the same!

**Comment by jrochkind** [comment]
For some images, facebook will do a really huge image in the share:

For others, it does a smaller one. 

I think it does a smaller one when the aspect ratio is too high (higher than long) for fb to feel comfortable cropping to the big image aspect ratio. 

We could generate a derivative crop ourselves to facebook's aspect ratio, to ensure a big image. But of course our crop would kind of be guessing too, since it would be automated. It could take the top of the image, or the middle of the image. Or it's possible our image tools have some algorithms to try and guess the 'interesting' focal point, not sure. (imgix does).

**Comment by jrochkind** [comment]
tumblr also won't show a photo unless the aspect ratio is less than 3:1. https://www.tumblr.com/docs/en/share_button

**Comment by jrochkind** [comment]
https://developers.pinterest.com/docs/widgets/save/

**Comment by jrochkind** [comment]
@MDiMeo for multi-image works -- do we need/want share buttons for each page? Maybe on the viewer I guess? I guess we'll start out without this, get the sharing of the main image done first, but something to keep in mind.
