### ISSUE TITLE
Review sort options -- sort by pub date

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#712]
Likely: 

* sort: by original publication date (trick is things with multi-dates)

**Comment by hackmastera** [comment]
From user testing: "A couple of users clicked on ‘sort by relevance’ dropdown to further refine results page, but then decided to stay with current ordering because other options weren’t helpful. One remarked that sorting by date uploaded/modified wasn’t what they needed."

**Comment by jrochkind** [comment]
@MDiMeo @catlu can you confirm that "original publication date" is one we'd want to sort by? 

I suspect so. The semantics are a bit tricky. What do we do when the item has a range of dates, or multiple dates?  We need to pick one date to be where it is in the sort order. (Unless we have it in multiple places in the results, which I suspect isn't that helpful, and would be quite challenging to do anyway). 

Just pick the first one? Earliest one? Latest one? Earliest one if sorting in one direction, but latest if sorting in another?

ALSO: What current sort orderings do we NOT need from the current list? Or an be staff-only? I suspect the public may only need 'date added latest-first', and not date-added oldest first, or date-updated at all.  Staff may need some of these though. 

This ticket is a bit more challenging mainly because of spec'ing what we want, as above. Once we have it spec'd, it's not too much trouble to do, although may require a reindex.

**Comment by MDiMeo** [comment]
Yes, users do want date published. Maybe @catlu can weigh in on how to address the problem you raise above. I also think leaving "date uploaded" could be helpful for some end users (like a science blogger who quickly wants the latest images), but it should appear under publication date and relevance, which I suspect will more more useful. I think we could remove "date modified" all together, but I'm curious if @catlu or @archivistsarah use it in their workflow and would prefer to keep it on the staff end?

**Comment by catlu** [comment]
When there's a range, I think it makes the most sense to sort by the start date (and since solo dates get put in there, at least we'd be sorting the same field too). When it's multiple, sorting by earliest/latest in different directions sounds good to me--not sure how difficult that is. I do use both 'Date added' and 'Date modified', but don't really need both of the sorts (latest/oldest), as often I'll just flip to the last few pages if I'm looking for something older.

**Comment by jrochkind** [comment]
It should be do-able to leave everything we've got only for logged-in users, and show logged-in users fewer options. 

> When it's multiple, sorting by earliest/latest in different directions sounds good to me

@catlu OK, and I think that's do-able. 

But that makes me think we'd want to do the same for ranges (and don't forget multiple ranges). If you are sorting 'latest first' you might want the _end_ of the range (latest endpoint), if sorting "earliest first", you might want the start point of the range?  For similar reasoning as for multiple with different directions?  Or no, do ranges lead to different needs/uses?

@MDiMeo I think spec'd like we're heading for, this is probably 1-3 days of work.

**Comment by jrochkind** [comment]
PS: I would also suggest renaming "relevance" to "best match" or something like that.  I don't think "relevance" means much, it really means 'best match' as determined by our system. 

I would also try to make relevance _not_ the default (or maybe even not available) unless you have entered a search string -- it doesn't mean anything unless you've entered a search string.  But this latter is sort of a 'stretch' goal, depending on how quickly the rest can be accomplished. This one here about relevance unavailable unless you have actually entered a query -- I think it makes sense, but it might take more time than it's value justifies.

**Comment by catlu** [comment]
@jrochkind If it's not too tricky, that makes sense to me.

**Comment by jrochkind** [comment]
No trickier for ranges than for multiples. The algorithm would be like just taking all the dates (individual multiples and range endpoints), and indexing the earliest in one field and the latest in another. 

As we did for date facet, we are forced to simplify by ignoring 'circa' (treat it just like the same date without 'circa'), and things like that. 

Ah, one more edge case!  Works without dates at all, which happens, either because no date was entered, or date was not entered in the documented machine-recognizable format. These should show up... at beginning? At end? Depends on direction? Should not show up at all if you are sorting by date?

**Comment by catlu** [comment]
My preference would be at the end, in both directions, just because it seems like the polite thing to do if someone is specifically doing a date sort.

**Comment by MDiMeo** [comment]
This all sounds good to me. I get the point about removing "relevance" if there's no search query, but I'm not bothered by it being there in the first instance and using testing to see if it's confusing. I don't have a strong opinion between the terms "relevance" or "best match". I do think the term "relevance" has meaning and is understood by users, but I don't feel strongly about it because I'm sure best match would be fine, too. 1-3 days of work sounds worth it for this because it really does come up repeatedly!

**Comment by archivistsarah** [comment]
just popping in to agree with everything cat suggested. and that date sorting is in line with archives best practices for collection arrangement, too.

**Comment by jrochkind** [comment]
1. New sort order options added: "newest date", and "oldest date".  (records with no date sort _last_ in both directions)
2. Some sort fields renamed:  "relevance" => "best match"; "date uploaded [descending symbol]" => "recently added". 
3. Some sort fields hidden to be staff only: "date uploaded [asending]", "date modified [both]". 
4. "best match"/"relevance" only makes sense if you have actually entered a query. If you have not, we remove the "relevance" option, and make "recently updated" the default sort. 

@catlu @MDiMeo @archivistsarah  This is as of this moment in testing on staging. Can you review and see if you think it works out?
