### ISSUE TITLE
Infrastructure Monitoring

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#714]
honeybadger?

ERROR LOGS — now that we have multiple machines, would be good to have a (cloud) log server
page load PERF MONITORING — how long is it taking to return ramelli? median/99th pctnl etc. Among other things, so we can have a better idea of if a change we made actually made it worse or not. (or better!) 
other infrastructure monitoring

friendly OS-level dashboard?

**Comment by jrochkind** [comment]
Signed up for a honeybadger account. Invited all team members plus it@chemheritage as collaborating users. I will email honeybadger to see about free/reduced rate for non-commercial open source, which they do say they have. 

Asked Chuck to approve the slack integration via a helpdesk ticket.

**Comment by jrochkind** [comment]
Honeybadger tracking should be on in production as well as staging! (prod vs staging should be labelled such in honeybadger error info). 

There will probably be other honeybadger config we tweak as we go, but this is done. 

Assigning issue to @sanfordd for any infrastructure monitoring we want to do. (CPU, RAM, disk space, server up, whatever). 

I asked the people I worked with last year, and they said they used cloud-hosted https://www.datadoghq.com/ when they used to deploy directly on AWS (instead of heroku).  It looks like datadog is free for up to 5 hosts, which we might already be pushing only on production. 

Statuscake is another cloud-hosted one I've heard good things about, although it's not really focused on this use case.  https://www.statuscake.com/kb/knowledge-base/using-server-monitoring/

Or of course there are various DIY things instead of cloud-hosted. I really like cloud-hosted for monitoring and alerting based on monitoring, because you don't need to worry as much about "who monitors your monitoring/alertting" or misconfiguration or downtime in your monitoring preventing you from getting alerts.

**Comment by sanfordd** [comment]
Will be adding a new ticket for graph design.
