### ISSUE TITLE
Design -- Mostly Visual

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#718]
* Search results page
* Collection splash page
* Work show page

## Things we have not gotten to:

 * date formatting
* I would still like to argue for hiding public domain limit unless you have search box focused, and add a date constraint there too.  Relevant to #770  (requires public domain limit showing up in 'you searched for')
* masonry/gallery image-forward view (not working at all on collections page, not properly styled to be good on search results page)
* very small screen support not quite right
* "you searched for" constraints on collections page
* #769 "part of" on search results display

**Comment by MDiMeo** [comment]
Among other things, Collection Splash page should remove Visibility section and "open access" icon next to files in the list. And this icon shouldn't link to the staff log in page, as it does now. https://digital.chemheritage.org/collections/wh246s128

**Comment by jrochkind** [comment]
See also #794

**Comment by jrochkind** [comment]
@MDiMeo @catlu @archivistsarah A question:

Which of those 'alternate views' of search results do we actually need? If any? Maybe we only need the default one?


![screen shot 2017-09-05 at 4 31 09 pm](https://user-images.githubusercontent.com/149304/30082123-a568808a-9257-11e7-985f-6b01c5d0d924.png)

Customizing even the default view, as I'm trying to do, is somewhat harder if I need to keep alternate views working. Also every additional alternate view we have is an additional thing to spend some design attention on, since all of the non-default ones are currently kind of messy too.

**Comment by archivistsarah** [comment]
I do like the masonry view (chance to look at images without a block of text) but I never, ever use the slideshow or the gallery.

**Comment by catlu** [comment]
I also never use the slideshow and rarely masonry, but gallery would be my preferred default view if it had way less metadata preview.

**Comment by archivistsarah** [comment]
I use masonry primarily because it doesn't have the lengthy metadata, not because of the image layout -- so Cat's idea would work for me, too!

**Comment by jrochkind** [comment]
Sounds like you both agree you/users want/need a single additional image-forward "result display type", with very little metadata.  Yes? The "masonry" view at present has only title, and that only when you mouse-over (doesn't work for touch screens, but). 

Are you both agreeing that a view type with only image and title would suffice, and is needed?

**Comment by MDiMeo** [comment]
I agree with the comments above: just masonry view, but with less metadata. Drop Description, Subject and Genre.  I agree we need the title, and elsewhere we said that the search results page should also say if it's a part of another item (based on usability testing). For the kind of research questions I ask, I know I would also want to see "maker" and "date" on a quick glance. I could be talked into dropping those if it will be too much text, but I do think those fields tend to be shorter than Description and Subject.

**Comment by MDiMeo** [comment]
OK, see ticket #769 for where we mentioned also adding Part of to search results page.

**Comment by hackmastera** [comment]
What is the use case for masonry view? I'm not sure it's research. The primary view is focused on research, so do we need another view that's research-oriented but slightly different?

I personally use masonry when I just want to get a visual overview of what we have, or to look for something pretty. I would think the use case would be for someone making a slide deck, e.g.

Whatever the use case is, let's compare it against our personas to decide whether it's important enough to warrant using that space on the page and maintaining the functionality. Actually, it's probably better to look at the personas first, and ask whether the primary view meets all the articulated needs, but that's sort of a semantic distinction. If we think an image-forward view is important, we probably want to attempt to highlight it somehow, since I think currently it's easily overlooked. Did anyone try it in user testing? Perhaps the sort of task that would lead to it wasn't really there, but I am curious whether anyone even saw it.

**Comment by jrochkind** [comment]
Everything on the "default" view is important on that view, or it wouldn't be there; the image-forward view is going to have less metadata than the default view, of course, that's what makes it image-forward, right? And have less metadata is also what cat and sarah have suggested would make it useful to them. 

But yes, we have two questions:

1) Is an "image forward" view important enough to our use cases and personas to allocate development time and page space to right now (thanks anna). If so: 

2) Understanding the use cases for this view (perhaps using the personas), what is the minimum metadata needed to support these use cases?  Because the more metadata on the page, the less it is "image forward" and the less useful it is that way (such as sarah mentioning she uses 'masonry' _because_ it has less metadata, and cat saying she wished 'gallery' had less).   I suspect title alone probably suffices, but I don't know.
