### ISSUE TITLE
First subject field doesn't autocomplete

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#719]

**Comment by jrochkind** [comment]
Hmm. We have a pretty much completely local implementation of the autocomplete (that predates me), that is no doubt based on original stuff from hydra-editor... but the code is awfully weird. The weirdness probably comes from hydra-editor originally, but it's hard to tell what it's doing, and it's not doing what one would think it's doing. 

I'll get to the bottom of it eventually, but this whole thing probably needs to be rewritten and/or un-forked from hydra-editor eventually.
