### ISSUE TITLE
explore other iiif servers

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#732]

**Comment by hackmastera** [comment]
Looking into [Cantaloupe](https://medusa-project.github.io/cantaloupe/). I have so far found 1 site using it in production: http://collections.ed.ac.uk/coimbra/record/97367; I've asked them for follow-up info on performance and their hardware specs.

I've also found a mention of performance in [a gh issue](https://github.com/medusa-project/cantaloupe/issues/125#issue-240032603)

**Comment by jrochkind** [comment]
Nice issue think @hackmastera . Looks like it's basically the same issue we think we're running into with riiif, cantelope may not fix it. Although might if you use 'tiled tiff' or jp2 as source image (which might work with riiif too).

**Comment by hackmastera** [comment]
Well we're having 2 issues with riiif so it's still possible cantaloupe will solve one of them  (the disk i/o one). hopefully using gm or one of the other processor options that cantaloupe makes available will help with the other.

**Comment by hackmastera** [comment]
Notes on the cantaloupe setup:

- I had to install ruby on the box in order to run the delegate script (extension points are provided via jruby) (@sanfordd)
- The delegate script currently has a hard-coded value for the fedora base url. I'm not sure if there's a way to move this to some config somewhere; we may just have to live with it.
- There are 2 files we'd probably want under version control; I guess with the build scripts?
  - cantaloupe.properties
  - delegates.rb

**Comment by hackmastera** [comment]
searched around the [iiif google group](https://groups.google.com/forum/#!forum/iiif-discuss) and found out the current list of iiif servers is here: https://github.com/IIIF/awesome-iiif#image-servers

**Comment by hackmastera** [comment]
potentially useful for cookies-based authorization in cantaloupe. https://robots.thoughtbot.com/how-to-share-a-session-between-sinatra-and-rails

**Comment by hackmastera** [comment]
Thread on iiif google group re: others using cantaloupe: https://groups.google.com/forum/#!searchin/iiif-discuss/cantaloupe%7Csort:relevance/iiif-discuss/xgW9FH-H3bM/O2xhcLm7AgAJ

AIC is currently testing it.
Yale center for British Art in production.

Meanwhile, we've wrapped up our testing. closing.
