### ISSUE TITLE
Text for Download Button

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#737]
When you click the "Download" button, the text "original image" should be changed to "Download original image". 

[This is based on usability testing. Users are not clicking on that, and their eye is drawn to the comment below it that more download options are coming soon, leading them to believe they can't do anything yet.]

**Comment by jrochkind** [comment]
Right before soft launch we had to revert to an older version of our code that doesn't always have the latest and greatest.  Once we're back on latest version of code, the menu will look like this:

![screen shot 2017-07-27 at 11 36 49 am](https://user-images.githubusercontent.com/149304/28679021-eeeb6d4c-72bf-11e7-9c19-69adff619e6b.png)

"More coming soon" already gone. 

My idea was there will be two sub-menus for entire work "Download all pages" (or something like that), with one or more zip/PDF options, and "Download this page" with at least two maybe more (original and full-res JPG) this-page-only options. 

Any guesses as to whether screenshot above will still need changes?  The actual option could be changed to "Download original image" even though it's under a heading "Download this image", I don't think that would necessarily be unreasonable.

**Comment by MDiMeo** [comment]
Thanks for clarifying that this is related to the older code. How far along are we till we have two sub-menus for the Download? In the meantime, I don't feel strongly about the various options. I have a slight preference for "Download this image" being the standalone text without an additional heading for now, but if this will make integrating additional menus harder in the future then you can leave it as the screenshot above looks.

**Comment by jrochkind** [comment]
Two sub-menus of course requires us to have all-page zip/pdf download options, which is currently included in #710 in milestone "before thanksgiving".  I have no ETA other than that, haven't begun working on it at all. 

It's easy to change the the text/layout for now, until we have that.

**Comment by jrochkind** [comment]
But we will _hopefully_  have a Download Original Image as well as Download Full-Res JPEG option by Sep 1.

**Comment by hackmastera** [comment]
For now there's only one option; remove the heading and call it "Download original image"
