### ISSUE TITLE
Rights statement icons are formatted incorrectly on IE

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#743]
IE version 11 on my PC, assuming that's the same across other users' computers.

They look weird and smushed:

![rights1](https://user-images.githubusercontent.com/11876037/28888271-f994ce14-778d-11e7-9ff3-70a956e6997d.png)

**Comment by jrochkind** [comment]
I think maybe IE needs width and height specified in CSS for the SVG, whereas other browsers take height and adjust proportionally. but that might not be it.

**Comment by hackmastera** [comment]
fine in ie10

**Comment by jrochkind** [comment]
Weird, it's not always for me. Either way, I think maybe IE just needs CSS `height` along with the `width` that's already there. FF/Chrome scale proportionally if height is unset, but IE in some cases does not. Since these icons are square, just height set equal to width already set should do it.
