### ISSUE TITLE
"my works" link visible when not logged in

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#746]
public users viewing a work can see a link to "my works" in the breadcrumbs above the image on the work show page. Since they're not logged in, clicking on it just kicks them to a log-in screen. 

Can we get rid of this link for anyone not logged in?

**Comment by hackmastera** [comment]
@archivistsarah can you give more steps to reproduce? I clicked 'browse all' then selected the first result. The only breadcrumb I see is 'back to search results'.

**Comment by archivistsarah** [comment]
Aha. This only happens when going from a collection landing page to a work. Start here and click on anything: https://digital.chemheritage.org/collections/wh246s128

Also happens with our artificial collections/focus areas like this one: https://digital.chemheritage.org/focus/scientific-education

**Comment by hackmastera** [comment]
thanks @archivistsarah! got it.
