### ISSUE TITLE
Users click 'browse all' instead of search submit button

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#760]
Rearrange elements in page to make these more distinct.

Consider placement of 'browse collections' at the same time.

**Comment by MDiMeo** [comment]
Possibly a design like BHL, which has Browse very separate from Search. http://www.biodiversitylibrary.org/ Maybe we could have options to browse by Recently Added, Collections, and Date.

**Comment by MDiMeo** [comment]
NYPL has Browse to the side of the search bar and a drop menu for browsing by "Items, Collection, Divisions". Their homepage design also includes far more thumbnails as previews for each featured section and the option to "see more". https://digitalcollections.nypl.org/

**Comment by hackmastera** [comment]
We've decided to remove this button entirely; reimplement the functionality
