### ISSUE TITLE
50% of users tested didn't scroll down front page

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#761]
- Decreasing size of the hero image would make it more likely that users would see content below.
- Color of 2nd content area same as color of footer. Would a different color help?
- 2nd content area has no header. Would adding a header help this? Would probably be good, regardless. "Popular Topics"?
- Subnavigation that pops people around the page?

**Comment by jrochkind** [comment]
Why do we want more percent to scroll down?

**Comment by MDiMeo** [comment]
This is a good question worth discussing. We spent time building curated selections to showcase collection highlights and reinforce the institution's brand, and I think the content below the fold does convey some of our strengths to the user. Many people reported that they felt confused by the scope and purpose of the site, and they went to the About and FAQ pages to try finding that information. Redesigning the page slightly to make sure they see some of this other content might help answer some of these questions, especially for the casual or first-time user. On the other hand, there were some users who just started by putting a search term relevant to them in the box and searched. These users who have a clear task in mind would probably not have used browse as an entry point into collections in the first place, so I'm less worried about them not having scrolled down. But I do think this could serve as a possible entry point for some of the other behaviors we identified in the user personas (and confirmed with usability testing.)

**Comment by jrochkind** [comment]
Hmm. This makes me think maybe we _aren't_ that happy with the home page design we got from 2010, after user-testing, and a complete home page redesign is needed, rather than just trying to tweak it. Maybe.

**Comment by hackmastera** [comment]
@jrochkind yeah I wondered the same thing; seems like it's worth considering.

**Comment by hackmastera** [comment]
Example: NYPL site changes the hero image aspect (without resizing) if you resize your window vertically https://digitalcollections.nypl.org/

**Comment by jrochkind** [comment]
With #905 done, do you want to close this, move it, or what, @MDiMeo ?

**Comment by jrochkind** [comment]
@MDiMeo what do you want to do with this ticket?

**Comment by MDiMeo** [comment]
Yes, this works for now. Let's close it - thanks!
