### ISSUE TITLE
Rewrite 'about' and 'FAQ' content

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#763]
Several users read the About page and FAQ first, but found them boring or too technical. Didn’t feel the content was written for them and didn’t care about the Collections policy. Links leaving the Digital Collections site confused at least one user.

**Comment by MDiMeo** [comment]
Consider headings for Technical Details and Acknowledgements.

**Comment by MDiMeo** [comment]
This is the Stanford example of the more technical About page that I was thinking of in today's meeting. https://bv.stanford.edu/en/about I see they have headings and a secondary navigation, but the introductory test is more user friendly and general.

**Comment by MDiMeo** [comment]
I rewrote the About page and had it approved by Communications. Please delete the current text and replace it with this: 

**About**
The Chemical Heritage Foundation’s Digital Collections offer highlights from our library, archives, and museum collections. Our chronology ranges from the Roman Empire to the 21st century, and the materials include everything from fine art to rare books and from scientific objects to photographs. 
The purpose of CHF’s Digital Collections is to manage, preserve, and provide access to our digital assets all in one location. Although the Digital Collections include only a small portion of our entire collection, new material is added every day. See our [Collections page](https://www.chemheritage.org/collections) for more information about our library, archives, and museum. 


**Copyright**
Possession of a digital reproduction of CHF’s collection materials does not constitute permission to publish, exhibit, or distribute. In most instances CHF does not hold the copyright to its materials and cannot grant or deny permission to use them. 

CHF staff makes every effort to inform patrons of copyrights and other restrictions that may apply to the works by providing a link to RightsStatements.org or Creative Commons in the Rights field in the object’s metadata record. Items we believe to be free of copyright and in the public domain are clearly identified. However, patrons are solely responsible for determining the copyright status of any materials they wish to use, investigating the owner of the copyright, and obtaining permission for the intended use.

The U.S. Copyright Law contains an exception for the so-called fair use of copyrighted materials for the purposes of teaching, scholarship, research, criticism, commentary, and news reporting. Patrons are solely responsible for determining whether their intended use of a copyrighted work is fair and for responding to any claims of copyright infringement that may arise from use of the material. For more information on copyright and fair use, please refer to the [U.S. Copyright Office website](https://www.copyright.gov/).


**Technical Summary**
The Digital Collections are built on the open-source technology stack [Samvera ](https://samvera.org/)(formerly Project Hydra), composed of Ruby on Rails, Solr, Blacklight, and Fedora 4. All of [our code is freely available](https://github.com/chemheritage/chf-sufia) on GitHub via an Apache 2.0 license.


**Acknowledgments**
We would like to acknowledge the generous support of the Arnold and Mabel Beckman Foundation and Robert W. Gore. This project was made possible in part by the Institute of Museum and Library Services grant SP-02-16-0014-16.

**Comment by MDiMeo** [comment]
FAQ page edits (requested and approved by copy editor):
On Question 4, please change the answer to this:
Possession of a digital reproduction of CHF’s collection materials does not constitute permission to publish, exhibit, or distribute. In most instances CHF does not hold the copyright to its materials and cannot grant or deny permission to use them.  CHF staff makes every effort to inform patrons of copyrights and other restrictions that may apply to the works by providing a link to [RightsStatements.org](http://rightsstatements.org/en/) or Creative Commons in the Rights field in the object’s metadata record. Additional information about the Rights Statement is provided by clicking on the link in the Rights field in an object’s metadata record. If you have a question not answered by the information provided with the image, feel free to e-mail us at digital@chemheritage.org.

NOTE: As per CHF guidelines, any links to external websites, such as rightsstatements.org in this example, should open in a new window. This should also be done for the About page.
