### ISSUE TITLE
Gather facet examples from outside our domain

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#765]
- Are facets sticky?
- How are sticky facets communicated between searches?
- Are facets initially collapsed or expanded?
- How are facets presented visually?

Note: explore mobile as well as full-width

**Comment by hackmastera** [comment]
Some users were confused on how to start a new search from a results page. They would put something new in the search box and didn’t realize they had to “x” out of the existing facet limits. One thought zero results meant we had nothing and another user thought they had to keep returning to the home page.

**Comment by hackmastera** [comment]
Next steps:

In evaluating these examples and moving to reorganize our own, also consider options to make our facets stand out visually:

"Many users did not notice or use sidebar facets. They completed all tasks by entering different keyword combinations into the search box and giving up if there were no satisfying search results."

**Comment by archivistsarah** [comment]
facets for the knitting & crochet pattern search on Ravelry.com. this interface and database uses A LOT of filters, but also it's for a knowledgeable, niche audience so doesn't have the same needs as we do.

1st image: blank search. note "jump to a filter" which is necessary because there are A LOT of filters (about 5 screen lengths' worth), number of results within each filter
![ravelry-blank-search](https://user-images.githubusercontent.com/25084902/29532725-7c79951a-867c-11e7-887a-8375b74888dd.gif)

2nd image: how nested filter categories work
![ravelry-cardigan-filter](https://user-images.githubusercontent.com/25084902/29532759-aaae5592-867c-11e7-9265-2df6584bfe89.gif)

3rd image: searching within filtered results (filters are sticky). note that the search box suggests using a filter.
![ravelry-baby-cardigan-searc](https://user-images.githubusercontent.com/25084902/29532779-cecb3fa8-867c-11e7-8435-0d5c0632a983.gif)

**Comment by MDiMeo** [comment]
Here's a screenshot of facets within Home Depot. There is a search box within facets, then one outside of facets.
![homedepotfacetsandsearch](https://user-images.githubusercontent.com/11823009/29622253-ee5fad84-87f0-11e7-9ef4-dd31bbf2ba83.jpg)

When I try to conduct a new search for "Olympus Paint", I type it into the search box at the top. The filters for my previous "lightbulb" search are not sticky.
![homedepotnewsearch](https://user-images.githubusercontent.com/11823009/29622377-41d3c202-87f1-11e7-89da-4610aa641019.jpg)

**Comment by catlu** [comment]
NYPL digital collections:

Facets are initially collapsed (except date range) and sticky, and when used, are labeled as a "keyword filtered search." The keyword and filter/facet stickies are separated out near the top:

![nyplfacets1](https://user-images.githubusercontent.com/11876037/29629072-8ed527c6-8805-11e7-9c8c-9a0e7ff11455.PNG)

When expanded, there is a "more" option, which further expands the list to the right. There's no A-Z sort, but there's a search function which acts like a ctrl+f search.

![nyplfacets](https://user-images.githubusercontent.com/11876037/29629176-e0edf3f8-8805-11e7-86f8-1d1df84a2b97.PNG)

**Comment by catlu** [comment]
Google images put these facet keyword buttons in bright colors, and when selected, whites them out:

![capture](https://user-images.githubusercontent.com/11876037/29629558-434d987c-8807-11e7-90b3-05d1fbcecf6b.PNG)

Google shopping puts filters into a breadcrumb trail:

![capture1](https://user-images.githubusercontent.com/11876037/29629605-69c32288-8807-11e7-9fc6-419a1ba89ef5.PNG)

**Comment by catlu** [comment]
Zappos facets are sticky checkboxes, and lists them all in their own scrolling boxes:

![capture](https://user-images.githubusercontent.com/11876037/29629785-fdfd8ad8-8807-11e7-8e0b-92f4ce528928.PNG)

**Comment by jrochkind** [comment]
> "Many users did not notice or use sidebar facets. They completed all tasks by entering different keyword combinations into the search box and giving up if there were no satisfying search results."

This is a pretty common finding in usability testing I have seen before at other libraries. It could be because they were all using blacklight-based stuff too and the facets aren't noticed. It could also be just that users don't really care about facets and don't really want to use them.

**Comment by MDiMeo** [comment]
All designs proposed in this ticket would radically change the way we currently do facets and are not feasible for the short-term. We hope to have corrected some usability issues with the latest design refresh, which makes both the overall page structure and the facet browse bar much clearer and cleaner. Closing this ticket for now, but we can open a new ticket if we find that facets are still confusing upon further usability testing.
