### ISSUE TITLE
Add 'Part of' to search results metadata display

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#769]
"Within the results page for the date facet 1700-1799, one users didn’t understand why plates from a single book were appearing out of order or how to find the book as a whole. (Plate 2 appears above Plate 1 for the book and the rest are out of order.]"

**Comment by jrochkind** [comment]
@MDiMeo @catlu So, let's say there's a work that is public, and it has a parent it is "part of" which is _not_ public....  is it desirable/important the parent not be listed as "part of" at all?  

Or, the sort of simple implementation would be the parent is listed, but when you click on it you get an access denied message or whatever (prob a login screen actually if you aren't logged in). 

This may be a situation we never intend to do intentionally (yet?), but any way the data can be will probably happen at least accidentally at some point.

**Comment by MDiMeo** [comment]
I think the situation you're describing would be rare, but @catlu, please confirm that. In the case that it remains rare or accidental, I'm okay with the simple implementation you recommend where the user gets an access denied message. But if we think this is a typical situation then I think it would be desirable to not list part of because it could be frustrating or confusing for end users.

**Comment by jrochkind** [comment]
If it's preferable to not show the parent if it's not public, I'll go for that, see if I can make it happen.

**Comment by MDiMeo** [comment]
I think it is desirable. It seems analogous to our choice to hide child works that don't have completed metadata rather than leaving the file there as a placeholder and giving the access denied message.

**Comment by catlu** [comment]
Confirming that it would be pretty rare or accidental.

**Comment by jrochkind** [comment]
Okay, I have a prototype on staging. I want to clean up the code a bit, but can you check it out and give feedback? It has the potential to slow down search results being returned a bit, but I don't think it is much. I should probably actually measure it.

**Comment by catlu** [comment]
I think it looks pretty great! I did a search for 'ramelli' and didn't experience a noticeable slow down in results being returned.

**Comment by jrochkind** [comment]
Actually timing, it seems to add from 3-5ms to our response time. Which honestly is enough to matter (at least in a normal app where you don't really want to go over 100ms if you can afford it; ours already approaches and goes over 1s), but we can afford it cause we need the feature and it's the best we can do in this stack right now.

**Comment by jrochkind** [comment]
@MDiMeo @catlu okay I styled it more like the "additional titles", which actually matches how it's styled on the 'show' page (it matches 'additional titles' there too, and is right below them there too), and it probably should have been done that way in the first place. 

(Even though I agree the previous styling looked nice for certain records!)
