### ISSUE TITLE
release a sufia version that will allow dependency upgrades

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#786]
we're on 0.11.2; current version is 1.1.0.

changelog https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md
hyrax update (doesn't look like there were any changes necessary) https://github.com/samvera/hyrax/commit/773a80db98034765c34e5987d8525736fc32641b

**Comment by hackmastera** [comment]
Turns out we can't do this unless we want to release sufia with this dependency bumped up:

https://github.com/samvera/sufia/blob/master/sufia.gemspec#L38

**Comment by jrochkind** [comment]
Gah. I found that it could use a more accepting dependency spec for rails-almond too, if we're gonna do another sufia release with dependencies relaxed.

**Comment by jrochkind** [comment]
i think this definitely isn't soft-launch milestone. Should we close as won't fix, or leave it for later? @hackmastera did you notice any carrierwave bugfixes/improvements we really wanna get?

**Comment by jrochkind** [comment]
looks like we'll need it for rails 5.1. Don't know if we can do 5.1 on sufia 7.3 anyway.

**Comment by jrochkind** [comment]
crap, do we need it for rails 5 too, even though sufia 7.3 theoretically supports rails 5?

**Comment by hackmastera** [comment]
we need to upgrade carrierwave to upgrade rails? sufia master is currently failing CI; this is a yak.

**Comment by hackmastera** [comment]
No, there weren't any features in particular it just looked like an easy upgrade and it has been out for a long time.

**Comment by jrochkind** [comment]
The maintenance story of this stack is ridiculous. Sufia is failing CI? Gah. 

Okay, I say we do a PR to sufia that fixes this dependency, also the rails-almond dependency, also any other dependencies we notice that are locked to a minor version when they probably should be locked to a semver major. And then release a sufia patch release. 

This is now a blocker for #545, which is in thanksgiving milestone.

**Comment by hackmastera** [comment]
Sufia 7.4.0 released https://github.com/samvera/sufia/releases/tag/v7.4.0
