### ISSUE TITLE
upgrade passenger

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#788]
`NoMethodError: undefined method 'call' for nil:NilClass Did you mean? caller` in `at_exit`

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53196/faults/34484267)

**Comment by hackmastera** [comment]
We got this on production at 6:40 am this morning; no one was deploying at that time. refs #785

**Comment by jrochkind** [comment]
I believe this is a passenger bug. 

https://github.com/phusion/passenger/issues/1730

It looks like we'd have to upgrade to passenger 5.0.24 or later to fix. we are at 5.0.10.

**Comment by sanfordd** [comment]
Fixed with an upgrade to 5.0.30, change made to the groupvar file in ansible that needs to be committed to make sure future machines have this build.
