### ISSUE TITLE
Add "Credit" field to metadata template

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#79]
At this stage, the new "Credit" field can be a free-text with no controls. It should be repeatable and should appear under the Rights field.

**Comment by hackmastera** [comment]
predicate needed! @catlu

**Comment by catlu** [comment]
@hackmastera, would this work? http://schema.org/creditedTo

**Comment by catlu** [comment]
Just noting here we're going with this: http://bibframe.org/vocab/creditsNote.html

**Comment by hackmastera** [comment]
@MDiMeo I'm putting it below "Rights Holder" since that seems to pair with "Rights."

**Comment by hackmastera** [comment]
@MDiMeo Also @catlu kept calling it "credit line" and we named it that; if that is horrible and wrong it's her fault ;)
