### ISSUE TITLE
adjust rights facet

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#796]
Maybe: Change rights facet to be single-value "public domain" toggle

refs #709; may actually be just one issue

**Comment by hackmastera** [comment]
Currently text of this facet is "Public Domain Mark 1.0" -- It sounds like we want to change that to just "Public Domain" and make it the only possible facet value. @MDiMeo please confirm?

**Comment by MDiMeo** [comment]
Yes, I agree. Change it to just say "Public Domain"

**Comment by MDiMeo** [comment]
Also: I'd like to either always have this facet expanded or do some UI work to display this one a bit differently, maybe kind of like The Met has done, where it's not a facet but instead appears as a checkbox under the facets: http://www.metmuseum.org/art/collection

**Comment by jrochkind** [comment]
we can do a checkbox. under the facets, or next to the search box. I think there's another issue already for putting it next to the search box?  Just a bit of work.

**Comment by hackmastera** [comment]
We'll see how well #709 addresses the usability issues. @MDiMeo will bring to committee.

**Comment by MDiMeo** [comment]
Since adding the Public Domain check box I have not spotted any additional issues related to copyright in my usability testing. So, I'm closing this.
