### ISSUE TITLE
OPAC languages for 'Language' field

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#80]
Afrikaans
Arabic
Bulgarian
Catalan
Chinese
Croatian
Czech
Danish
Dutch
English
Esperanto
Estonian
Finnish
French
Galician
German
German, Middle High
Greek, Ancient (to 1453)
Greek, Modern (1453-)
Hebrew
Hungarian
Icelandic
Indonesian
Italian
Japanese
Latin
Latvian
Norwegian
Polish
Portuguese
Romani
Romanian
Russian
Serbian
Slovak
Slovenian
Spanish
Swazi
Swedish
Tahitian
Tereno
Thai
Turkish
Ukrainian
Yiddish

**Comment by hackmastera** [comment]
@catlu remind me how we're doing this? dropdown or autocomplete?

**Comment by catlu** [comment]
Since there's so many, let's do autocomplete.
