### ISSUE TITLE
footer layout broken in ie10

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#807]
![screen shot 2017-08-28 at 3 49 24 pm](https://user-images.githubusercontent.com/845363/29790637-854d8732-8c08-11e7-9fd4-ff9c2c253419.png)

**Comment by jrochkind** [comment]
Did we maybe actually decide we were only supporting IE11?  The viewer is totally broken on IE10 too, but I know I had it working on _some_ IE before. Checking in IE11.

**Comment by jrochkind** [comment]
yeah, IE10 doesn't really do flexbox (it half-way does a previous version). You can sort of get this to work anyway with auto-prefixer, but now I'm remembering we decided not to, just to call IE11 our base.

**Comment by jrochkind** [comment]
IE10 no longer receives security updates from MS. https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by hackmastera** [comment]
It seems like maybe we did decide not to support ie10. I just looked at our stats and we've only had 1 ie10 user since we opened the firewall. I'm not sure whether that decision is documented, though, or where it should be documented. @MDiMeo?

**Comment by hackmastera** [comment]
@jrochkind @MDiMeo here's a reference to the no-ie-10 decision https://github.com/chemheritage/chf-sufia/pull/618#issuecomment-310184969 -- closing, and I'll close the other ie10 issues I opened!
