### ISSUE TITLE
Add facet for 'Exhibition' field

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#811]

**Comment by hackmastera** [comment]
@MDiMeo needs to be prioritized

**Comment by MDiMeo** [comment]
@catlu Can you let the museum know that the field is there and that we hope to create the facet/link before the public launch but cannot guarantee it?

**Comment by catlu** [comment]
@MDiMeo yep!

**Comment by catlu** [comment]
Not sure if this is part of the same ticket--feel free to make a new one if not: Exhibition field isn't currently searchable.

**Comment by jrochkind** [comment]
I think maybe Anna finished this before she left. @catlu is Exhibition field currently searchable? Anything left to do on here?

**Comment by catlu** [comment]
@jrochkind It's searchable! Still needs a facet though.

**Comment by jrochkind** [comment]
The decision has been made to add a facet for it?  OK, I'll change the name of this ticket to "add facet for exhibitions".

**Comment by jrochkind** [comment]
Can relevant decision-makers specify what order it should be in the facet list? @MDiMeo @catlu

**Comment by MDiMeo** [comment]
@clu set the order before, so I will defer to her. I would prefer close to the bottom since it applies to so few of our objects.

**Comment by MDiMeo** [comment]
@catlu (sorry!)

**Comment by catlu** [comment]
no worries @MDiMeo I just looked up an earlier reference:

Appear below Department on metadata edit and show page as well as facets.

**Comment by jrochkind** [comment]
reindex and enabled.
