### ISSUE TITLE
Homepage text to show live number of digital objects

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#829]
Change "over 4,000" so that a live number is shown, similar to what is done at the NYPL.

**Comment by jrochkind** [comment]
This should include "child works" as separate works? So for instance, if there's a manuscript with 10 plates taken out as separate child works, that's 11 "items"?  That is indeed the easiest way to do it.

**Comment by MDiMeo** [comment]
Yes! If it shows up in the search results (as child works do), it should be included.

**Comment by jrochkind** [comment]
Cool. I am assuming just the count of _public_ works though, correct me if I'm wrong.

**Comment by MDiMeo** [comment]
Yes! Public only.
