### ISSUE TITLE
Change all instances of text reading CHF or Chemical Heritage Foundation

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#831]
Rebranding requires us to say Science History Institute. Change homepage and check all collections pages. This should be launched on Feb. 1, 2018 and not before!

**Comment by jrochkind** [comment]
It's not just home page and collections pages, we have CHF/Chem Heritage in lots of places. default HTML titles and other prompts and legends, email subjects (currently only sent to admins I guess), etc.  Hard to find by just a search, since we use "CHF" in class and variable names that do _not_ really need to be changed (at least not on any deadline) too. 

Then there's the name of our github repo and any other cloud accounts too, which may or may not matter.

**Comment by MDiMeo** [comment]
I would imagine we'll be making these as separate tickets, no? But you can clump it all into one if that's better for you. For example, I was planning to make a new one for the Credit Line field once we have that, but the new text hasn't been approved yet.

**Comment by jrochkind** [comment]
okay that's fine. I don't think we have a list of all the places the name CHF/Chemheritage appears, I think the task is really _finding_ them.

**Comment by MDiMeo** [comment]
OK, here's my first stab at finding all instances of CHF and Chemical Heritage Foundation on our site:
- Header and Footer
- Homepage: sub-heading above introductory text
- About: many instances in the first two paragraphs under About and under Copyright
- FAQ: Email address for digital@chemheritage.org will have to change throughout this page. Also references to the name in the answers to questions 3, 4, 5, 7, 8, and 10.
- Contact: Change email address for digital@chemheritage.org.
- Digital Collections Policy: Currently linked via our FAQ page. Has Chemical Heritage Foundation and CHF throughout.
- Eventually, we'll want to tackle our GitHub repo name, or at least the Read Me file attached to it. I mention it here because we do link to this in our About page.
- Metadata change to Credit Line field with new text approved by Digital Collections Committee.
- Featured Topics: Scientific Education description says "Museum at CHF"; Science on Stamps mentions "CHF's archives"; Instruments & Innovation says "Museum at CHF"
- Presently, none of the Collections descriptions make reference to CHF. However, by Nov. 3, curators have agreed to edit existing descriptions and provide content for collections with no descriptions. We'll have to check these as they come in.

I believe I checked all pages of our site! If others find additional references to CHF/Chemheritage, please note them here.

**Comment by jrochkind** [comment]
@MDiMeo Email address changes, "FAQ: Email address for digital@chemheritage.org " -- what will that change to?  Can we count on the new email address being available when we role out Feb 1, we should change it in the branch to be rolled out then?

**Comment by jrochkind** [comment]
@MDiMeo 

> Featured Topics: Scientific Education description says "Museum at CHF"; Science on Stamps mentions "CHF's archives"; Instruments & Innovation says "Museum at CHF"

Please specify exactly what these should be changed to.

**Comment by jrochkind** [comment]
Also, need general guidance on how to replace "CHF".  For instance, on policy page: "Since the Digital Collections will draw from several departments across CHF..."...  "across the Institute"? "across the Science History Institute"? Other?

**Comment by MDiMeo** [comment]
I just got an approved Naming Conventions sheet from Zack and added that to our Basecamp: https://3.basecamp.com/3311666/buckets/3284131/uploads/807363475

Looks like "across the Institute" is a good replacement for CHF. Museum at CHF should be changed to "the Institute's museum" and CHF's archives will be "the Institute's archives".

**Comment by MDiMeo** [comment]
New URL is sciencehistory.org. (DNS for chemheritage currently points to with and without the www., but Chuck wasn't positive if we'd still do both after the change over. More later when we know...)

New email is digital@sciencehistory.org.

Email and web are scheduled to change over Feb. 1st, but some internal changes will be made the weekend prior.

**Comment by jrochkind** [comment]
We have a bunch of RDF URIs that go like `http://chemheritage.org/ns/collection-thumb`. 

It is going to be very difficult to change them, as they are in fedora.

**Comment by jrochkind** [comment]
@MDiMeo Will the catalog be at `http://othmerlib.sciencehistory.org`?

**Comment by jrochkind** [comment]
@MDiMeo confirm we'll have `digital-tech@sciencehistory.org` too?

**Comment by sanfordd** [comment]
We will not be changing any of the bucket names in AWS since it requires making a new bucket and copying over all data before erasing the old bucket. If we do want to fix the bucket names we'll use DNS names.

**Comment by jrochkind** [comment]
Some in-fedora data will need to be changed to have new domain name and other language. 

AFTER rebrand rollout is successful, we will need to run "rake chf:rebrand" on jobs-prod server, to change fedora data. Will take a few hours to run.

**Comment by jrochkind** [comment]
@MDiMeo The only remaining things are "Collections descriptions", and two things we decided not to do before launch:  the github names; and RDF predicate URLs. 

So nothing in here for me anymore. Shall we close this, or leave it open for "Collections descriptions"?
