### ISSUE TITLE
[CHF Digital Collections/production] ArgumentError: You attempted to set the property `state' of 1j92g7979 to an enumerable value. However, this property is declared as singular.

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#832]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53196/faults/34534387)

**Comment by catlu** [comment]
I went into the edit metadata view of br86b4223, relationships tab, to add 1j92g7979 as a child work. After adding, and saving, I got an error page (think it was 500 internal server error, but I clicked away kind of fast). Went back to Browse all view, and both records looked fine and the relationship showed up.

**Comment by jrochkind** [comment]
Did we just add any new properties? If so those seem likely culprits. exhibitions?

**Comment by hackmastera** [comment]
@jrochkind there is apparently a property `state`. Maybe related to the workflow stuff?

**Comment by catlu** [comment]
Not sure if related, but I noticed an error with br86b4223. I set it to Public access, but it's currently still CHF.

**Comment by jrochkind** [comment]
but why would any changes we made recently do that?  We haven't touched any of that. I guess it might not be a result of the deploy, just a coincidence?

**Comment by jrochkind** [comment]
@hackmastera you noticed the other error that happened about the same time, yes? https://app.honeybadger.io/projects/53196/faults/34534360

**Comment by hackmastera** [comment]
seems possible this is the first time @catlu has done this since we got honeybadger; maybe we've been missing it all this time.

**Comment by hackmastera** [comment]
@jrochkind I missed that other one; my eyes brushed over it because it looked like the at_exit one we've been getting.
