### ISSUE TITLE
[CHF Digital Collections/production] ActionView::Template::Error: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#833]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/presenters/chf/file_set_presenter.rb: representative_file_id
    line 59 of [PROJECT_ROOT]/app/views/curation_concerns/base/_chf_image_viewer.html.erb: block (2 levels) in _app_views_curation_concerns_base__chf_image_viewer_html_erb___3631974451799782840_29352840
    line 41 of [PROJECT_ROOT]/app/views/curation_concerns/base/_chf_image_viewer.html.erb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53196/faults/34534360)

**Comment by hackmastera** [comment]
This one looks like it could be just a matter of timing; maybe someone tried to view the record before it was indexed?

I wonder if that should be a warning instead of an error.
