### ISSUE TITLE
"my collections" breadcrumb showing up for public users

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#843]
similar to https://github.com/chemheritage/chf-sufia/issues/746 (closed)

clickable "my collections" breadcrumb appearing at the top left of collection pages for users who are not logged in. Happens when accessing a collection from most places in digital collections (featured collection link on front page, relationship on a work show page, collections list page), EXCEPT for when you get to a collection through a search result.

**Comment by MDiMeo** [comment]
Issue #885 should address this if it's still happening.
