### ISSUE TITLE
No Collection Relationships confusing

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#844]
Users commented that 'There are no collection relationships’ on top of page is confusing. Consider reorganizing the page so that this isn't on top. Or discuss hiding this field when there's no content the way we do with other fields

**Comment by jrochkind** [comment]
yup, plan to refresh this page, and this was already on the list. I don't think there needs to be a separate "Relationships" section at all, and I think empty "relationships" should not show up, just like empty ordinary values don't.
