### ISSUE TITLE
Change Date > Start label

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#85]
How about 'Individual/Start'?

**Comment by hackmastera** [comment]
What about 'date' and 'end date'?

**Comment by catlu** [comment]
I like that. @MDiMeo, what do you think? Does it take away some of the confusion for precise dates or is 'end date' still iffy?

**Comment by MDiMeo** [comment]
I liked this at first, but I'm wondering if it would be more confusing to have end without start? What about "Date or Start Date"? Or just leaving it "Start Date", and then in the Help Icon you can say that if it's a single date, it should go into the Start Date field?

**Comment by hackmastera** [comment]
We'll address this issue in tooltips. @catlu will edit.

**Comment by catlu** [comment]
Okay @hackmastera, I submitted a pull request. Hope I did it correctly.
