### ISSUE TITLE
New User Account: Joel Klein

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#853]
@jrochkind will document how to make a new user account for JKlein@chemheritage.org and @sanfordd will run the task. Please complete this today or tomorrow in preparation for his meeting. Let me know once it's completed so that I can email Joel to change his password.

**Comment by jrochkind** [comment]
To create a new user account, from a production server run:

     RAILS_ENV=production bundle exec rake chf:user:create[email@chemheritage.org]

The user will then use the 'reset password' feature to get an email to set their own password. If this doesn't work for some reason (sendio) and it's urgent, we can create a password for them -- but we _really_ don't want to know their password, or to have passwords being sent around in cleartext emails. So it's preferable to have them set their own password using the 'reset password' feature. 

To make an existing user an admin as well:

         RAILS_ENV=production bundle exec rake chf:admin:grant[email@chemheritage.org]

@sanfordd can you try this ASAP and let us know if it worked?

**Comment by jrochkind** [comment]
@MDiMeo should Joel have admin-level access, currently just had by Digital Collections team members?
