### ISSUE TITLE
Work inaccessible, giving internal server error

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#856]
https://digital.chemheritage.org/concern/generic_works/rx913q554

Comes up in search:
https://digital.chemheritage.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=2008.033.045_001.tif&filter_public_domain=0

In the same batch, two other filesets didn't finish processing: 
https://digital.chemheritage.org/concern/parent/k3569489x/file_sets/fq977v358
https://digital.chemheritage.org/concern/parent/k3569490p/file_sets/1z40kt44b

**Comment by MDiMeo** [comment]
@jrochkind This isn't super high priority because there's other work to be done, but it would help with the curators' workflow if you can look into this in the following week or two. @catlu wasn't sure if this was related to the #852 . She said in the past that Anna would "rerun them" but we weren't sure if that was a rake task that @sanfordd could do or not.

**Comment by jrochkind** [comment]
Hmm, yeah, I wish we knew exactly what Anna was doing when "rerunning them".  Seems like it's more than creating derivatives, missing derivatives wouldn't give an error. Maybe I'll try asking @hackmastera a favor to tell us.

**Comment by jrochkind** [comment]
https://app.honeybadger.io/projects/53196/faults/34889976

**Comment by jrochkind** [comment]
@catlu you should be able to access this work now. "Corrupted" works missing images might still happen, haven't fixed that but this particular problem with "corrupted" works being _inaccessible_ should be fixed. 

https://digital.chemheritage.org/concern/generic_works/rx913q554

It is still missing an image. Can you now use the admin UI to upload the missing image again? I guess perhaps using the 'versions' tab?

**Comment by catlu** [comment]
Thanks @jrochkind! As long as I can access it, I should be able to fix the missing image.
