### ISSUE TITLE
Items need DZI and thumbnails

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#857]
For work: https://digital.chemheritage.org/concern/generic_works/rx913q529--

Fileset without thumbnail and DZI: https://digital.chemheritage.org/concern/parent/rx913q529/file_sets/n296wz608

Child work without thumbnail and DZI:
https://digital.chemheritage.org/concern/generic_works/bg257f64n

Child work without thumbnail only:
https://digital.chemheritage.org/concern/generic_works/vm40xs12q

This based off a comment in #852 by @catlu

**Comment by jrochkind** [comment]
Okay, I believe some of the _originals_ are missing from fedora, so I can't simply use techniques to create dzi and thumbs -- I need to figure out why the originals are missing and what to do about it 

Not really sure where to start, will try asking anna for advice as a favor.

**Comment by catlu** [comment]
I just noticed this with another work (https://digital.chemheritage.org/concern/generic_works/tt44pn34n) right before I clicked save. Usually when the file is done uploading it shows the total file size, this one also showed as completed but the file size showed as 0 kb. May be happening on the upload end? Wonder if this is a case where it makes sense to delete and reupload.

**Comment by jrochkind** [comment]
@catlu I think you took care of all of these yourself, and some of these id's are no longer in the repo (because you took care of it by deleting them and restarting). 

Are there any items you know about that currently need derivatives generated? If so, can you give me ID's? If not, I'll close this ticket!

**Comment by catlu** [comment]
Nope, I think we're all set here!
