### ISSUE TITLE
Record errors

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#86]
http://staging.hydra.chemheritage.org/files/0c483j36g

http://staging.hydra.chemheritage.org/files/8s45q876k

**Comment by catlu** [comment]
There are also a few other broken links from Hillary and Sarah.

**Comment by hackmastera** [comment]
It looks like it's 
https://github.com/ruby-rdf/rdf-turtle/issues/13

Which has been resolved in the hydra stack here: https://github.com/projecthydra/ldp/pull/55

Will try updating relevant gems.
