### ISSUE TITLE
Modify date object model to use originally-desired predicates

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#87]
Bug fix https://github.com/projecthydra/active_fedora/commit/137c6524069d82c516c53900d0de0c12b8f1ada0  should mean we can model this in a way that actually makes sense. Will have to pin to this commit in Gemfile.

see also:
* https://github.com/chemheritage/chf-sufia/issues/49
* https://github.com/chemheritage/chf-sufia/issues/23

maybe we never actually chose the right predicates?

**Comment by catlu** [comment]
Yeah, I think the predicates are worth revisiting for this model. I remember what was on the table were dcterms:created/issued, but let's check in about it again.

**Comment by hackmastera** [comment]
@catlu, cool. The actual date object is a EDM.TimeSpan. So we either need a predicate that accepts that in its range [1] or we need to revisit the date object itself [2]. Or of course we can just use our imaginary CHF namespace.

predicates used in the date object (in case that's relevant) are:
EDM.begin
EDM.end
CRM.P79_beginning_is_qualified_by
CRM.P80_end_is_qualified_by
SKOS.note

[1] It looks like dcterms predicates didn't have the right range.
[2] My sense is that this is unlikely to be fruitful; the way the object itself is modeled requires that type, if i remember correctly, and I feel like it would be hard to find alternate start / end predicates. But I could be wrong!

Maybe VRA will solve everything for us.

**Comment by catlu** [comment]
@hackmastera, which is the predicate that points to the date object itself?

**Comment by hackmastera** [comment]
@catlu we don't have one yet. Initially we had date of work and date of publication; they were DC.date and DC.issued. But they weren't going to be usable because of the range issue with EDM.timespan.

**Comment by hackmastera** [comment]
Discussed; we will use DC11.date
