### ISSUE TITLE
Add "Staging" to Header on Staging Server

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#877]
Some ideas we discussed in Slack:

jrochkind [10:48 AM] 
I can add a big header that says STAGING or something. I can base it off the info in local_env.yml that tells us it’s staging. Add a github issue for it?

[10:49] 
maybe replace the logo in the header bar with the word “STAGING”?

**Comment by jrochkind** [comment]
Fixed by 5ca3ac7b34db9
