### ISSUE TITLE
Image file doesn't download (on Staging)

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#878]
On my iPhone using Safari, when I hit download, I get a white screen with a small empty box on top.

When @archivistsarah tried down download on her Android, she got the error message that it failed to download "due to an unknown error".

When I try to download on my Windows Desktop using Chrome, it looks like the file is downloaded. However, when I click on the Tiff, Photoshop cannot open it. It gives me the error message "Could not complete your request because it is not the right kind of document."

If this is related to @jrochkind's new code, then this is a blocker that must be fixed before we deploy code to production. However, @sanfordd is looking into whether this is related to the code change or if this is related to the data update he just did to staging.

**Comment by sanfordd** [comment]
Fixed, the issue was linked to the data migration. The move introduced an incorrect path on some of the fedora data. The path was fixed and all data has been merged correctly.
