### ISSUE TITLE
Clean-up Collections breadcrumbs

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#885]
If a non-logged-in user navigates to an item show page within a Collection or Featured Topic, they get a truncated version of the title that is not clickable. Logged-in users see a breadcrumb trail, but even that may not be particularly helpful. Seeing the title repeated up here is particularly confusing when you're not logged in because you can't tell it's supposed to be part of a breadcrumb trail and because users are used to seeing the "Back to Search Results" link appear in that place if they navigate to the item through the search results page.

Consider how to clean-up breadcrumbs or remove them all together for consistency and clarity.

**Comment by MDiMeo** [comment]
OK, this doesn't just happen with Collections or Featured Topics. I also got it when I was clicking around within a parent work with children, opening the viewer and bouncing between the child and parent works. Sometimes the the truncated title is even a hyperlink, but it just seems to reload the same item show page without the breadcrumb title being hyperlinked. Weird behavior.

**Comment by MDiMeo** [comment]
Notes from user testing on 2/7/2018:
- All three users used the "Back to search results" button instead of the back button on the browser. 
- During this test, all users searched instead of browsing, so no one stumbled upon the broken breadcrumbs mentioned in the ticket above. 
- When asked if they would like breadcrumbs, they hypothetically said yes, but no one gave a strong use case for why or how.
- Consider user testing further with a task that will force someone to stumble upon one of the broken breadcrumbs mentioned above. Or, change broken breadcrumbs within Collections to say "back to results" (or similar) since in these cases you are not going back to _Search_ results, but to a hierarchy of browse results.

**Comment by eddierubeiz** [comment]
OK -- I did [some work](https://github.com/sciencehistory/chf-sufia/pull/1034) on this. The new behavior is:
- If you're logged in, the breadcrumbs function as they used to.
- Otherwise, all breadcrumbs except the "Back to Search Results" one are suppressed.
