### ISSUE TITLE
Eddleman Collection thumbnail

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#891]
Eddleman Collection was previously made private, but now it can be public since new works were added to the collection. Here are my suggestions for a thumbnail crop, feel free to choose from here or from the collection itself @MDiMeo: 

https://digital.chemheritage.org/concern/generic_works/mk61rh526
https://digital.chemheritage.org/concern/generic_works/7s75dc890
https://digital.chemheritage.org/concern/generic_works/5t34sk17b

**Comment by MDiMeo** [comment]
Thanks @clu!  I like Scholar Interrupted (second in the list) and would love a crop that also captures the book. Of the three options, I think it's the brightest and crispest. My second pick would be An Alchemist in his Studio (last one) since it has the distillation equipment.

**Comment by catlu** [comment]
Cropped file is rf55z7692_full.tiff.
