### ISSUE TITLE
Add inscription field to tooltips

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#90]
@catlu here are instructions for editing the tooltips directly in the code base (without ever leaving the github site) and submitting your edits as a pull request!

1. click the 'fork' button anywhere in the chemheritage/chf-sufia project. select your own user account to fork the project there.
1.  once it's finished, you'll see you are looking at a fork of the project under your username. navigate to the file which is config/locales/en.yml
1. You'll see some action buttons to the right just above the text of the file. click the little pencil to edit.
1. make your changes.
1. Below the file, fill out a commit message. It should start with a capital letter and sound like a present-tense command (e.g.: 'Add tooltip for inscription field') -- The commit message basically reads as if it completes the sentence "I want to ___ so I will apply this commit."
1. It's always best practice to submit your change as a pull request, so select that radio box. and then submit (you can name the branch or not as you prefer).
1. on the next page click "create pull request"
1. You'll then see your pull request! It's probably not a bad idea to mention to me that you've done this -- at least until I make sure any notifications are coming through effectively.

Let me know if you have any questions! I can walk through it with you in person if you like.

**Comment by catlu** [comment]
Awesome, thanks! Can't wait to try this out later.

**Comment by catlu** [comment]
@hackmastera and I decided that a better way to do this would be to bypass the forking to own project step. Will migrate the documentation here to wiki.

**Comment by catlu** [comment]
@hackmastera, I moved stuff here: https://chemheritage.atlassian.net/wiki/display/HDC/Instructions+for+Editing+Metadata-Related+Configurations+in+GitHub

Please feel free to review/edit new instructions.

**Comment by hackmastera** [comment]
fixed in PR #122
