### ISSUE TITLE
add 'additional credit line' field

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#91]
repeatable, with drop-downs for standard language, e.g. 'Photographed by'.

**Comment by hackmastera** [comment]
@catlu unfortunately we need a new predicate for either this or the original credit line (which is currently using Bibframe.creditsNote)

**Comment by catlu** [comment]
Would http://schema.org/creditedTo work?

**Comment by hackmastera** [comment]
I don't think so -- that has a domain of MusicRelease and a range of Organization or Person.

**Comment by catlu** [comment]
Ok, then I say we use the Bibframe predicate for the Additional Credit, and use a chf:credit for the generic CHF line.

**Comment by hackmastera** [comment]
@catlu is 'Photographed by' the only use case so far?

**Comment by catlu** [comment]
Yep. I think there could be other use cases, but no one else feels strongly about them so far.

**Comment by hackmastera** [comment]
@catlu Guess what! I implemented this as a nested attribute. That means
 1. we should continue using the bibframe predicate for the universal credit line field (it has a range of literal) and
 1. we should think about what we want for predicates / object types for the nested attribute. currently i'm using:
  * generic_file -> chemheritage.hasCredit -> credit_object
  * credit_object -> type -> chemheritage.credit
  * credit_object -> chemheritage.hasCreditRole -> 'photographer'
  * credit_object -> FOAF.name -> 'Name'
  * credit_object -> SKOS.prefLabel -> 'Photographed by Name'

**Comment by catlu** [comment]
This makes sense. Can we use chemheritage.hasCreditRole with multiple roles down the line?

Also, I think the actual names will be the same few--could we use a local list similar to File Creator?

**Comment by hackmastera** [comment]
You want it to be a dropdown?

Yes we can add more roles as needed.

**Comment by catlu** [comment]
Yeah, let's do dropdown.

The names I know of for photographer credit are:

Douglas Lockard
Gregory Tobias
Mark Backrath
Penn School of Medicine
Will Brown

(taken from Museum digital assets Access database)

**Comment by hackmastera** [comment]
the list for dropdown will be universal; i.e. if we add another 'role' in the future it will use the same master list. 

At least, unless we change the way it's implemented :)

**Comment by catlu** [comment]
Cool, works for me.
