### ISSUE TITLE
use 'credit line' field to set universal CHF credit

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#92]
should display in form but not be editable.
value should be set on object creation.

**Comment by hackmastera** [comment]
@MDiMeo @catlu what is the universal value to sue? "Courtesy of the Chemical Heritage Foundation"?

**Comment by hackmastera** [comment]
I used "Chemical Heritage Foundation Collections" which I found in some documentation provided for a DCC meeting.

**Comment by catlu** [comment]
The most general line in the style guide (after they cite all the departments) is CHF Collections, so I think the above works for us.

**Comment by MDiMeo** [comment]
According to the DCC Minutes from 9.2.2015: "RB and EM agreed to something like "Courtesy of CHF Collections" as blanket for all collections". Can we go with that? Obviously, this will be changing before we go live anyway because we won't be CHF anymore...!

**Comment by hackmastera** [comment]
sure i can use that instead.

**Comment by catlu** [comment]
I don't remember if we ever came to a decision in DCC (I think the use cases were more speculative than current), but I'm curious if we want to give users the option to remove the CHF credit?

**Comment by hackmastera** [comment]
@catlu can you put this on a new ticket?
