### ISSUE TITLE
rebrand DNS changes

### ISSUE THREAD

**Issue by jrochkind** [chemheritage/chf-sufia#938]
Make sure our host(s) respond at sciencehistory.org domain names. (Just app host? Does it matter for any others?)

Possibly add redirects for chemhistory.org domain names to new ones?

**Comment by sanfordd** [comment]
- [ ] Check SSL certificates with IT
- [ ] Adjust redirects 
- [ ] Update hostnames

**Comment by sanfordd** [comment]
Spoke with IT, working out a few details but it should be smooth.

**Comment by sanfordd** [comment]
The redirects need to be set up when we're ready to go, @jrochkind noticed a caching issue with the old hydra name to check out.

**Comment by sanfordd** [comment]
Officially changed over to digital.sciencehistory.org
