### ISSUE TITLE
Feedback from Communications Web Team

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#948]
- [x] Download  and View look like one big button. Maybe a little white between like on the current site? Also, maybe sea-green like on the viewer and to contrast with all the linked text? 
 

- [ ] I’m having a hard time seeing the borders between the buttons in the image viewer, especially on the Windows PC. I think it would be nice to have them stronger.

**Comment by jrochkind** [comment]
eliminated borders entirely on viewer instead of making them stronger. I think it works.
