### ISSUE TITLE
Revise live number count on home page

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#951]
Change live number of items that appears on the homepage so that it also counts the number of Collections. This should mean that the number on the home page matches the number of results you get from a blank search.

**Comment by jrochkind** [comment]
@MDiMeo Becuase of how the Sufia code I was using to do this works, this is actually somewhat of a pain. But it can be done. Just verifying that this is still wanted even though we're above 5k on home page already.

**Comment by MDiMeo** [comment]
@jrochkind While it's less urgent since we hit 5k, yes, this is still wanted. Ron wants us reporting on the higher number and  this change would address user confusion as to why the two total counts don't match.
