### ISSUE TITLE
Download problem for record with special character Φ

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#957]
Here's the email from a research fellow who contacted @archivistsarah :

> I’ve been making heavy use of the digital collections as I make a chronological listing of pH meter and Spectrophotometer models.
> 
> I encountered an odd problem though. The 1980s line of pH meters was named phi, only using the Greek letter. When I go to download a picture of the (phi)10, I get this message:
> 
> InvalidArgumentHeader value cannot be represented using ISO-8859-1.response-content-dispositionattachment; filename="beckman_Φ10_ph_6m311p405_th83kz633_dl_medium.jpg”147C099487B97847uXnt619Dfx0aPvKnHr3wgImxufzgbLAgutlFuPj5oV26GoVgINZoq2qUQ6gm0A3uFJoTMRcfMjk=
> 
> I think this means you can’t put a Greek letter in a filename.
> 
> Here’s the record link:
> https://digital.chemheritage.org/concern/generic_works/6m311p405

Looks like the original TIFFs download fine, it's just the JPGs which take the filenames from the title. I also tried it with this symbol ♂ and it had the same issue so looks like special characters are a problem.

**Comment by jrochkind** [comment]
interesting bug! thanks for the report. will prioritize getting this fixed.

**Comment by archivistsarah** [comment]
I'm just manually updating the few files I have that this effects, since the research fellow needs access to them soon.

**Comment by jrochkind** [comment]
@catlu @archivistsarah do you know or can you guess what work/file this is, so I can test? Or an example file? 

Or, maybe better/easier, can you find or create one on staging for me that exhibits the problem?

Hey, we're still beta until Feb 1. :)

**Comment by catlu** [comment]
I'll make one on staging now too.

**Comment by archivistsarah** [comment]
Work titles that should be on staging:

Beckman Φ71 pH Meter
Beckman Φ10 pH Meter
Beckman Model Φ71 pH Meter
Beckman Φ10 pH Meter (different one)
Beckman Φ line of pH meters
Beckman Model Φ21 pH Meter
Beckman Model Φ11 pH Meter
Beckman Model Φ40 & Φ45 pH Meters
Beckman Model Φ71 pH Meter
Beckman Model Φ72 pH Meter
Beckman Model Φ40 pH Meter
Beckman Model Φ10 pH Meter
Beckman φ72 pH meter, with dramatically illuminated glassware in the background
Beckman φ71 and φ31 pH Meters and φ12 pH/ISE meter

**Comment by catlu** [comment]
Thanks @archivistsarah !
