### ISSUE TITLE
works to be deleted

### ISSUE THREAD

**Issue by archivistsarah** [chemheritage/chf-sufia#960]
[beckmandeletions_1-22-2018.txt](https://github.com/chemheritage/chf-sufia/files/1653224/beckmandeletions_1-22-2018.txt)

**Comment by jrochkind** [comment]
hmm, some of them may have been deleted, but it wound up more troublesome than i thought, so still working on ensuring the rest are.

**Comment by jrochkind** [comment]
@archivistsarah hey, just curious, how did you create that file? With what software?

It's... very strange. I can rescue it, but it's got lots of weird bytes in it I've got to remove.

**Comment by jrochkind** [comment]
Ah, you saved it in UTF-16 somehow. OK. Curious how you did that!

**Comment by archivistsarah** [comment]
Sorry about that! It was an excel csv file I saved as a txt file

**Comment by jrochkind** [comment]
No problem, but I'm still curious what happened. Saved as a txt file how? From Excel?

**Comment by archivistsarah** [comment]
Yep. Save as --> select txt from extension/file type list

**Comment by jrochkind** [comment]
Okay, those 231 works should be deleted from production. 

Attaching the log output of my delete task for the records, although the first 187 works were previously deleted in yesterday's more amateurish attempt that was not logged. 
[delete_log.txt](https://github.com/chemheritage/chf-sufia/files/1660434/delete_log.txt)

**Comment by jrochkind** [comment]
@archivistsarah I'm not sure what Excel does, but if you see any way to select "encoding: UTF-8" as an option in future Excel "save as"/"export" commands, please choose it. :)

**Comment by archivistsarah** [comment]
sure thing!
